### ISSUE TITLE
Implement disk throttle limits for VMs

### ISSUE THREAD

**Issue by maran** [canonical/lxd#10982]
As far as I can tell there is currently no support for QEMU's throttling of disk devices yet. I want to attempt to implement this but I'm running into some issues that I would like to discuss before I commit to a certain direction.

QEMU's supports quite a few [throttling options](https://github.com/qemu/qemu/blob/master/docs/throttle.txt). Initially I was hoping to implement these directly in the blockdev-add monitor command but sadly I found that throttling is not supported via this call. The alternative method would be to use `block_set_io_throttle` via QMP in `addDriveConfig` so that the limits get added after the drive config has been created. I obviously don't know the code-base that well so if there is a better place to implement it please let me know.

Now the other question is about configuration. For the cgroups implementation limits.write limits.read limits.max is being used but this doesn't really cover all the cases that QEMU supports. I would prefer to have all the knobs available so that for instance I can set both iops and bps limits at the same time. Therefor I would prefer to have a configuration option such as `read.iops`, `read.bps`, 'write.bps` etc. I would also love to implement burst supports which adds even more configuration options (iops_max_length etc.)

I think this should work both on root disk devices as additional volumes that are attached to the VM. (the latter does not accept limits.* at all at the moment). 

Please let me know how I should proceed.

**Comment by tomponline** [comment]
@maran I would suggest that before you start, maybe have a look through the code and suggest what and where you're planning to make the changes, in case we can provide any insight/suggestions.

**Comment by tomponline** [comment]
Also any proposed config and API changes.

**Comment by tomponline** [comment]
This was implemented in https://github.com/canonical/lxd/pull/13002
