### ISSUE TITLE
Containers using OVN networks get different IPs on reboot

### ISSUE THREAD

**Issue by peppepetra** [canonical/lxd#11658]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04 (Jammy)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-71-generic
   * Snap Microcloud version: 0+git.f6e4e40 rev. 407
   * Snap LXD version: 5.13-cea5ee2 rev. 24758
   * Snap Microovn version: 0+git.1177d40 rev. 86
   * Storage backend in use: Snap Microceph version 0+git.fdf6d5e rev. 338 

# Issue description

OVN assigns IPs sequentially. That means if I create two containers then delete one and stop/start the other one, the latter changes IP.

# Steps to reproduce

 1. `lxc launch ubuntu:22.04 test-sticky-ip`
     `lxc launch ubuntu:22.04 test-sticky-ip-2`  
```
| test-sticky-ip   | RUNNING | 10.47.208.3 (eth0)  |      | CONTAINER | 0         | host3 |
+------------------+---------+---------------------+------+-----------+-----------+-----------------+
| test-sticky-ip-2 | RUNNING | 10.47.208.4 (eth0)  |      | CONTAINER | 0         | host2 |
```

 2. `lxc delete  test-sticky-ip --force`
 3. `lxc stop test-sticky-ip-2` 
 4. `lxc start test-sticky-ip-2`
 5. Result `test-sticky-ip-2` get IP previously allocated for `test-sticky-ip`
 ```
 | test-sticky-ip-2 | RUNNING | 10.47.208.3 (eth0)  |      | CONTAINER | 0         | host2 |
 ```

**Comment by nishant-dash** [comment]
Hello,

I have a scenario where I am using juju deployed on LXD vms in a microcloud setup and rebooting a single vm mutliple times does not result in an ip change but rebooting a physical host results in almost every vm on that host getting a new ip, even with `volatile.eth0.last_state.ip_addresses` being set.

Versions:
- lxd: 5.21.1-10f4115
- microovn: 22.03.3+snap0e23a0e4f5
- microceph: 0+git.4a608fc
- microcloud: 1.1-04a1c49

**Comment by tomponline** [comment]
Reproducer:

```
lxc launch ubuntu:noble guest1
lxc stop guest1
lxc launch ubuntu:noble guest2
lxc start guest1
```

The key difference is that the 2nd instance wasn't started for the first time until after the 1st instance was stopped.

So it was then allocated the next free IP, which was the one guest1 had released when it was stopped.

When guest1 is started again, it tries to use its old IP, but is unable to because guest2 has taken it.

This is working as intended because the sticky IPs feature was best-effort sticky IPs, not automatic guaranteed static IP allocation.
