### ISSUE TITLE
lxd recover: add support for storage buckets

### ISSUE THREAD

**Issue by casperan** [canonical/lxd#11704]
...this is general, so distribution & other environment information have been omitted.

# Issue description

lxd recover currently does not include storage buckets, that would be nice to have.

and it could scan the filesystem and automatically restore all buckets or a selection.

on a side note, this would be nice to have for storage pools and volumes too, so the user need not remember or need to mount and explore the filesystem manually to recall the names.

**Comment by casperan** [comment]
When attempting to create a bucket that exist in a storage pool but wasn't restored in lxd's database with lxd recover, "btrfs subvolume create ..." will fail.

lxc storage bucket create kube test
Error: Failed creating storage bucket: Failed to run: btrfs subvolume create /var/snap/lxd/common/lxd/storage-pools/kube/buckets/test: exit status 1 (ERROR: target path already exists: /var/snap/lxd/common/lxd/storage-pools/kube/buckets/test)

are there any other options than to manually mount the host partition and prune the bucket folder ?

**Comment by tomponline** [comment]
Please can support requests/questions go to https://discuss.linuxcontainers.org/ rather than conflating the github issue with questions. Thanks

If you don't need the bucket's data then it would be easier to remove the directory, you can enter the snap's mount namespace using:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt
mount
```

From there you should be able to see the storage pool mount and remove what you need.

**Comment by tomponline** [comment]
@MusicDin one thing we need to evaluate with regards to bucket naming in the storage pool (and/or adding backup.yaml) is the ceph radosgw s3 storage driver, as that doesnt have scope for backup.yaml, as there's nowhere to store it. Equally for custom volumes, the root directory of the volume is passed to the instance (or is a block device), so I'm thinking about perhaps having a separate per-pool backup volume that would contain the files for volumes and buckets perhaps.

I think we'd want to think about this more and come up with a design, so a good first step feels like doing the storage layer rename to include project, so at least basic recovery is possible.

**Comment by MusicDin** [comment]
@tomponline very good point. I will focus on the patch of bucket names to make the recovery possible, and we can figure out the recovery of access keys later.

**Comment by stgraber** [comment]
@tomponline in the Ceph side, we can pull the keys back from Ceph though, no?

**Comment by tomponline** [comment]
> @tomponline in the Ceph side, we can pull the keys back from Ceph though, no?

Quite possibly. I wonder if we can do the same for minio

**Comment by tomponline** [comment]
The other thing that's on my mind with this is that local buckets are backed by special storage volumes, so we should check if pool level volume settings (like filesystem) are inherited by the bucket storage volume. If they are then a requirement on recovering a bucket would also be to recover the storage volume settings. So custom volume recovery and bucket recovery are somewhat linked. 

If the volume cannot be mounted then the minio data nor a backup.yaml can be accessed. 

This potentially lends criedance to having a per pool recovery volume with the volume and bucket backup files in there.

Lots to think about.

**Comment by stgraber** [comment]
This is thankfully a somewhat limited problem, basically just LVM in this case.
The kernel can handle filesystem detection and once we do get into the volume, a backup.yaml at the root would provide the rest.
For dir, zfs and btrfs, we can always access the volume and for Ceph, it's using radosgw.

I'd certainly prefer we use the backup.yaml approach for the custom volumes too, it'd make things a lot simpler overall, but it's sadly not as easy there as we've unfortunately made it so the custom volume data is immediately at its root. Block custom volumes, just like the upcoming iso custom volumes also make this harder as they don't have somewhere to hold the backup.yaml.

Having a per-pool file or volume for that does avoid this issue but it also makes it far more likely that corruption would lead to a loss of that volume, whereas with the per-volume metadata approach, complete loss of all pool data is far less likely.

**Comment by tomponline** [comment]
Lets do a first pass of this issue by getting the bucket volumes renamed as a patch to always include the project name, and then add basic recovery, then leave this issue open so we can tackle to backup.yaml based restoration next.
