### ISSUE TITLE
Add a `lxc cluster group add` command

### ISSUE THREAD

**Issue by stgraber** [canonical/lxd#11726]
We currently have `lxc cluster group assign` which replaces the full set of groups for a member with a new set of groups.
We also have `lxc cluster group remove` which lets you remove a cluster member from a group.

But we don't have a `lxc cluster group add` to just add a cluster member into a specific group.

**Comment by tomponline** [comment]
Could we also alias `set` to `assign` too? This would line up nicely with our other commands.

**Comment by stgraber** [comment]
Hmm, no, because if we ever add key/value config to groups, we won't be able to get our usual set of set/unset/show/edit

**Comment by tomponline** [comment]
Ah yes true.

**Comment by ibilalkayy** [comment]
I can try out this but as a beginner, I have to go through some resources and then understand it properly so that I can implement this feature by adding the `lxc cluster member add`

**Comment by stgraber** [comment]
Hey there, assigned it to you.

For this one, you basically will only need to touch `lxc/cluster_group.go` where you'll find the current `cmdClusterGroupAssign` logic. You'll want to duplicate that as `cmdClusterGroupAdd` and make it so that instead of just replacing the current set of groups for the specified member, it instead appends to its current list.

**Comment by taltrums** [comment]
Hi, wanted to understand on how to debug after making changes, is there any doc regarding it, I could not find any instructions for that in [CONTRIBUTING.md](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md), also can i look into this if @ibilalkayy is not working on this. Thanks

**Comment by ayush0801** [comment]
I request the addition of the ```lxc cluster group add``` command to conveniently add a cluster member to a specific group without replacing all groups. This feature would enhance cluster group management in LXC. As a beginner, I will need time to study and understand the codebase before implementing this functionality. Your guidance and suggestions would be appreciated.
