### ISSUE TITLE
LXD documentation requires reference diagram of networking

### ISSUE THREAD

**Issue by grebennikov** [canonical/lxd#11742]
Current state of the docs https://linuxcontainers.org/lxd/docs/latest/networks/ doesn't explain the layout and connectivity between the networks internal/external (for OVN).
It would be great to have a reference diagram so that brand new user of LXD/Microcloud can understand how to set up networking.

**Comment by Ayushpanditmoto** [comment]
Do you have any videos related to this or any reference i can work on this issues

**Comment by tomponline** [comment]
@ru-fu is your plan to have this available by LXD 6.1?

**Comment by ru-fu** [comment]
> @ru-fu is your plan to have this available by LXD 6.1?

It's planned for this cycle.

**Comment by tomponline** [comment]
@ru-fu can we close this now that the ovn network diagrams are in the docs?

**Comment by ru-fu** [comment]
Yes, covered in https://documentation.ubuntu.com/lxd/en/latest/reference/network_ovn/#ovn-networking-architecture
