### ISSUE TITLE
The documentation isn't comprehensive enough when it comes to manipulation with the devices.

### ISSUE THREAD

**Issue by grebennikov** [canonical/lxd#11747]
It'd be great if there was an article or tutorial that explains the manipulation with all device types in one place.
Currently there is a section that explains the block devices attachment and creation, but as an example there is no such section for nics.

There are lots of "how to" questions in the discourse such as https://discuss.linuxcontainers.org/t/how-to-add-a-network-interface-in-lxc/437

They ideally should be converted into docs.

**Comment by stgraber** [comment]
All the device types are covered in https://linuxcontainers.org/lxd/docs/latest/reference/devices/ with individual pages for each of them which usually do have some examples.

**Comment by tomponline** [comment]
There is top-level section on device adding/configuring/removing here:

https://linuxcontainers.org/lxd/docs/latest/howto/instances_configure/#configure-devices

**Comment by stgraber** [comment]
@ru-fu can you think of something actionable here for our docs?

**Comment by ru-fu** [comment]
We should probably add some example commands, that would surely help.

But I'm not 100% sure which section you mean for block devices attachment and creation - can you provide a link @grebennikov ?

**Comment by realdmitchell** [comment]
I wouldn't say 'not comprehensive is a problem' there are things that are _unclear_.  (i.e) scattered information. And some options in LXD have become like

-  User needs some insider knowledge to know where to ask or search
-  Cryptic error message


For example, resize a container 
https://discuss.linuxcontainers.org/t/cant-see-mountpoints-of-created-containers/9562/8


A typical user would think type the following command is OK.

`lxc config device set ldap-server1 root size=50GiB`

(the error message is 
https://discuss.linuxcontainers.org/t/cant-see-mountpoints-of-created-containers/9562/7

`Error: The device doesn't exist`

)

but the correct command has to be

`lxc config device override ldap-server1 root size=50GiB `

How can user know this (easily)?

Example 2:

No easily accessible information on backup a container. Yes, the optimal way would be to install another lxd and do it there.  

https://discuss.linuxcontainers.org/t/backup-the-container-and-install-it-on-another-server/463/23

Overall... to be honest I don't know how to solve this. 

- May be some how document a list of basic options (for non-power users).

**Comment by tomponline** [comment]
> `Error: The device doesn't exist`

What LXD version are you using by the way, in the current version the equivalent command would get you an error in the form of:

```
lxc config device set v1 eth0 ipv4.address=192.168.1.1
Error: Device from profile(s) cannot be modified for individual instance. Override device or modify profile instead
```

**Comment by tomponline** [comment]
Some people find consuming how-to videos more helpful, and we have a YouTube channel here:

https://www.youtube.com/lxd-videos

Some relevant videos:

Backups: https://www.youtube.com/watch?v=IFOZpAxckPo

There are several videos covering each device type that may be of use: https://www.youtube.com/playlist?list=PLddduKsl-KEhleT9VTR4hbtlNdtMr6cFd

**Comment by realdmitchell** [comment]
> Error: Device from profile(s) cannot be modified for individual instance. Override device or modify profile instead

This is better. At the same time, may be it would be worth pondering if some basic things like resize, network are DIRECTLY doable rather then edit profile or use override etc. (i.e) use override as a default for these basic things. (Again this is not connected to this issue but ) may be you experts can ponder over whether some essential things should fall back as user-friendly or may be 'rigid but secure'.

**Comment by tomponline** [comment]
I think it could get quite confusing to introduce special exceptions from the foundational profiles concept when doing `lxc config device set`, as in the long run that would get harder to learn which settings are consistent with the concept and which are "special".

One popular request that was added a few release ago is the ability to override specific device config at instance create time so you don't have to create the instance and then do (potentially multiple) `lxc config device override` commands.

This can be done by using the `--device` or `-d` flags on `lxc init` or `lxc launch`.
There is also the `--storage` or `-s` flags and the `--network` or `-n` flags which indicate which storage pool and network (for eth0) the instance is configured to use, for example:

```
lxc launch ubuntu:jammy c1 -s mypool -d root,size=20GiB -n mynetwork
```

See also https://linuxcontainers.org/lxd/docs/master/howto/instances_create/#instances-create

**Comment by realdmitchell** [comment]
I understand your points and agree wholeheartedly. But somehow I feel somethings are NOT intuitive with lxc (lxd) commandline. (Sorry). And I also understand if one does a constant deepdive into lxd (like using it every week then it becomes OK but if one leaves it for some months one forgets it).

Example:

Very intuitive. Easy.

`lxc config set  vm1  boot.autostart 0
`
Not intuitive

`lxc config device add vm1 shared disk source=/home/shared/ path=/dest/
`

```
lxc config device override vm1 root size=200GiB
lxc config device set  vm1 root size=200GiB
```

For the above 2 commands an average user may expect a syntax like this...

`lxc config device vm1 set root size=200GiB
`

Again, I wish not to be a PITA. May be it is the me! (May be you can look at ZFSlinux project. Despite having tons of options some how it feels manageable. Again sorry for comparing and being rude.)

Once again thanks for the amazing product.

**Comment by tomponline** [comment]
@ru-fu has created issues to improve the documentation in our internal tracker:

- https://warthogs.atlassian.net/browse/LXD-404 - for adding more examples is definitely a good idea.
- https://warthogs.atlassian.net/browse/LXD-408 - since overriding isn't mentioned at all in the docs so far.

So I'll close this issue now.
