### ISSUE TITLE
Bridge creation fail with error 'Error: Can't parse a version'

### ISSUE THREAD

**Issue by Josue-T** [canonical/lxd#11902]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.0-9-amd64
   * LXC version: 5.0.2-1
   * LXD version: 5.0.2-5
   * Storage backend in use: btrfs

# Issue description

When the system have a locale different than 'en', the creation of bridge fail. It's because of dnsmasq version parsing issue.
After trying to understand what is happening in the code it's related to theses following part of code: https://github.com/lxc/lxd/blob/master/lxd/dnsmasq/dnsmasq.go#L114-L115

The issue is that with `english` locales the result of the command `dnsmasq --version` return this:
```
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```

But in french the result is different:
```
Version de Dnsmasq 2.89  Copyright (c) 2000-2022 Simon Kelley
Options à la compilation IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile

Ce logiciel est fourni sans AUCUNE GARANTIE.
Dnsmasq est un logiciel libre, il vous est permis de le redistribuer
sous les termes de la licence GPL (GNU General Public License), version 2 ou 3.
```
And in others language it's could be also different. But in the code it's expected that are always the same spaces between the version and the start of string.

# Steps to reproduce

 1. Set your locale to an other language than English.
 2. Try to create a bridge with ` lxc network create lxcbr0 --type=bridge`
 3. See that it will fail with `Error: Can't parse a version`.

# Workaround

For now unitl the issue is fixed the issue could be fixed by adding this line in the systemd unit of `lxd.service`:
```
Environment=LANGUAGE=en:en_GB
```
By this dnsmasq will be called with the "english" language.

**Comment by tomponline** [comment]
This sounds very similar to https://github.com/lxc/lxd/issues/6109 which was fixed by https://github.com/lxc/lxd/pull/6111 in 2019.

This runs the `dnsmasq --version` command with these environment vars:

```
append(os.Environ(), "LANG=C.UTF-8", "LANGUAGE=en")
```

Can you confirm what you get if you run please:

```
LANG=C.UTF-8 LANGUAGE=en dnsmasq --version
```

**Comment by tomponline** [comment]
Also can you try:

```
LANG=C LANGUAGE=en dnsmasq --version
```

**Comment by Josue-T** [comment]
> Also can you try:
> 
> ```
> LANG=C LANGUAGE=en dnsmasq --version
> ```

Hello, both return the correct English version:

```
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```

**Comment by tomponline** [comment]
Hrm, strange, I wonder if that fix somehow is missing from LXD 5.0.2, although I doubt it. I'll check...

**Comment by tomponline** [comment]
Yes it is in LXD 5.0.2

**Comment by tomponline** [comment]
Are you running snap or deb package?

**Comment by Josue-T** [comment]
Hello,

I'm using debian package. here are the the result of `dpkg -l | grep lxd`:

```
ii  lxd                                           5.0.2-5                                 amd64        Powerful system container and virtual machine manager - daemon
ii  lxd-agent                                     5.0.2-5                                 amd64        LXD guest agent
ii  lxd-client                                    5.0.2-5                                 amd64        Powerful system container and virtual machine manager - client
```

**Comment by tomponline** [comment]
Hopefully @simondeziel change will fix this issue, but we can reopen if it doesn't.
