### ISSUE TITLE
Duplicate IP addresses on LXD virtual machines, after importing from export archive

### ISSUE THREAD

**Issue by pcgeek86** [canonical/lxd#11907]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 
   * LXC version: 5.13
   * LXD version: 5.13
   * Storage backend in use: dir

# Issue description

After exporting an LXD virtual machine ("original"), a user imports the archive into a new virtual machine ("new") with a different name. The original VM that was exported is **not** deleted. When both the original and new VMs are started up, they both share the same IP address, leading to networking conflicts between the VM instances.

# Proposed Enhancement

1. Throw a warning to the user, during an import operation
2. Warning should indicate that duplicate unique IDs are detected
3. Warning should provide corrective actions that the user can take

# Steps to reproduce

 1. Create a VM `lxc launch --vm images:ubuntu/23.04 u01`
 4. Export the VM `lxc stop u01; lxc export u01 u01.tar.gz;`
 5. Import the archive to a new VM `lxc import u01.tar.gz u02`
 6. Make sure both VMs are started `lxc start u01; lxc start u02;`
 7. Observe duplicate IP addresses `lxc list`

**Comment by tomponline** [comment]
@roosterfish the main issue with this one is why does it allow the container to be started when it has the same volatile mac address as the other instance.

**Comment by roosterfish** [comment]
@tomponline I am wondering if we want to block the start of two VMs in general if they have an identical `volatile.uuid`?

**Comment by roosterfish** [comment]
> @roosterfish I dont think we want to block the import, as then its harder to fix, but why is the instance being allowed to start if it has a conflicting MAC, that is the part im not understand right now.

The conflicting function is `instance.IsSameLogicalInstance()`. The MAC/address checks get skipped since the volatile UUID is equal for both original VM and clone.

**Comment by tomponline** [comment]
Ah OK, makes sense.

In  that case I think we should update `IsSameLogicalInstance()` to check whether the either of the supplied instance names match the name generated by `MoveTemporaryName`. If one of them does then there is a temporary copy being made, if not, then its not the same logical instance.
