### ISSUE TITLE
Cluster group PUT fails

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#11943]
# Required information
 * LXD version: 5.15

# Issue description

The `PUT` endpoint for `1.0/cluster/groups/:name` fails with the error message `NodeClusterGroup not found` when adding cluster members to a group that was initially created without any members. See below for two consecutive requests, where the 2nd request produces the failure.

This is a regression in 5.15. With LXD 5.0.2 the error is not happening and the cluster members in the group are updated successfully.

# Steps to reproduce

1. create
```
curl 'https://localhost:8443/1.0/cluster/groups' \
  --data-raw "{\"name\":\"foo\",\"description\":\"\",\"members\":[]}"
```

succeeds with `{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":null}`

2. update

```
curl "https://localhost:8443/1.0/cluster/groups/foo" \
  -X 'PUT' \
  --data-raw '{"name":"foo","description":"","members":["local"]}'
```

fails with `{"type":"error","status":"","status_code":0,"operation":"","error_code":404,"error":"NodeClusterGroup not found","metadata":null}`

**Comment by tomponline** [comment]
@roosterfish please can you take a look at this, as you've been working in the cluster groups code recently. Thanks
