### ISSUE TITLE
Lxc wont start after adding GPU

### ISSUE THREAD

**Issue by Modyng** [canonical/lxd#11959]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 & 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:5.15
   * LXD version:5.15
   * Storage backend in use:

# Issue description

When i add GPU to my lxc virtual machine, it wont start!

# Steps to reproduce

 1. lxc launch ubuntu/20.04 u1 --vm
 2. lxc exec u1 bash
 3. sudo apt update && sudo apt install pciutils -y && lspci -nnn | grep -i nvidia
 4. exit
 5. lxc stop v1
 6. lxc info --resources | less
 7. lxc config device add ubuntu gpu0 gpu gputype=physical pci=0000:01:00.0
 8. lxc start u1

Hi, i followed the Youtube video on how to setup LXC VM with GPU on the official page but when i add the GPU PCI device to the VM, it wont start up!

I've tried it with Ubuntu 20.04/22.04 as a basic(native) systems and then installed lxc Ubuntu 20.04/22.04 as the images but in all cased even with different GPUs [ one with GTX 850 and the others with two 1080i ] and none of them works as expected!

I've installed the lxc using $ snap install lxc
and then initialized it as default parameters $ lxc init

```
here is the $ lxc info --resources
GPUs:
Card 0:
NUMA node: 0
Vendor: Intel Corporation (8086)
Product: 4th Gen Core Processor Integrated Graphics Controller (0416)
PCI address: 0000:00:02.0
Driver: i915 (5.19.0-46-generic)
DRM:
ID: 0
Card: card0 (226:0)
Control: controlD64 (226:0)
Render: renderD128 (226:128)
Card 1:
NUMA node: 0
Vendor: NVIDIA Corporation (10de)
Product: GM107M [GeForce GTX 850M] (1391)
PCI address: 0000:01:00.0
DRM:
ID: 1
Card: card1 (226:1)
Control: controlD65 (226:1)
Render: renderD129 (226:129)

here is the configs: $ lxc config edit ubuntu
devices:
gpu0:
gputype: physical
pci: “0000:01:00.0”
type: gpu
```

is there any other info needed?

Thanks
Best regards

**Comment by tomponline** [comment]
@gabrielmougard fancy taking a look at this one?

**Comment by gabrielmougard** [comment]
Yes of course (plus, this perfectly match my config!)

**Comment by tomponline** [comment]
I saw it and thought of you :)

**Comment by Modyng** [comment]
@tomponline @gabrielmougard 
Thanks for the prompt reply!

just ask for additional info if needed (:

**Comment by Modyng** [comment]
One Note is that in the video (min 11:05), https://www.youtube.com/watch?v=1i45zTu42i0
https://piped.qdi.fi/watch?v=1i45zTu42i0&t=667

he adds the device before stopping the VM (just exited, he uses V4.18) but not on 5.15 we need first to stop the VM and then add the device ( gpu ) to the VM, which results in broken pipeline!

**Comment by tomponline** [comment]
Hey @gabrielmougard did you confirm this was an issue?

**Comment by gabrielmougard** [comment]
@tomponline I confirm

**Comment by gabrielmougard** [comment]
@tomponline I'm pretty sure the problem happens inside `DeviceDriverOverride` in `pci.go`. I'm still trying to understand what is going on

**Comment by gabrielmougard** [comment]
Not only this bug happens but after stopping the instance, I can't even delete it and after that my whole lxd daemon seems to be broken...

**Comment by gabrielmougard** [comment]
In my situation (Ubuntu 20/04, RTX 3070 Ti), I noticed that I had two Xorg processes running on my card (I used `nvidia-smi` to check if there were any running processes used by the card), I suspect that when `DeviceUnbind` is called (because in this case, the GPU device is of type physical so we unbind the device from the host when the device is started at instance startup), the device unbind path `/sys/bus/pci/devices/<SLOT_NAME>/driver/unbind` cannot be written because the there are existing running processes used by the device driver. But instead of returning an error, `os.WriteFile` is blocking... 

@Modyng do you have any processes running on your GPU ? A graphical engine like Xorg like me for example ?

**Comment by Modyng** [comment]
@gabrielmougard 
Hi, Sorry for the late reply!

No no process using the GPU!
my laptop has two graphics ( one is the built-ins (intel) and the other is the GTX850)


but after adding GPU to the V1 system, it stucks there!
it wont start

but it works for the containers! i can add gpu to the containers built by the lxc (u1)

Thanks

**Comment by mharvilla** [comment]
This exact same issue is still occurring for me. First, I stop the VM. Secondly, I add the physical GPU, and then when I go to restart the VM, it just hangs. Furthermore, I cannot then delete the VM unless I restart the host. I can confirm that I have no processes running on the GPU (e.g., nvidia-smi shows `No running processes found`).

I am running LXD version 5.21.2 LTS on Ubuntu 24.04.

Is there any resolution for this? @gabrielmougard @tomponline As @Modyng mentioned, the VM attachment goes just fine with containers, but we are interested in using VMs.

**Comment by tomponline** [comment]
Is the GPU unused on the host, as LXD must unbind it from the host to pass it to a VM, so it cannot be being used with an existing display.

**Comment by mharvilla** [comment]
@tomponline I stopped gdm3, killing the display, and then ssh'd into the machine from another computer and verified that nvidia-smi showed "No running processes found". I assumed that was sufficient for verifying that the GPU was unused on the host, but maybe not. The thing I'm planning to do next is replace Ubuntu with Ubuntu Server.

**Comment by mharvilla** [comment]
FYI - I resolved this by ensuring that NVIDIA drivers are completely removed from the host machine before trying to assign a GPU to a VM. @tomponline Is this an expected requirement?

**Comment by tomponline** [comment]
Yes that would likely help, I've tended to blacklist them, but removing achieves the same effect.
