### ISSUE TITLE
LXD network forwarding port rule doesn't work with 0.0.0.0 listen address

### ISSUE THREAD

**Issue by pcgeek86** [canonical/lxd#11975]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04 LTS Jammy Jellyfish
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.15.0-76-generic`
   * LXC version: 5.13
   * LXD version: 5.13
   * Storage backend in use: zfs

# Issue description

When I create a network forwarding rule, using `0.0.0.0` as the listening address, the network traffic is not forwarded to the LXD virtual machine.

If I create a forwarding rule, using the actual IPv4 address assigned to the host's network adapter, then the forwarding rule works.

# Steps to reproduce

 1. Run LXD VM `lxc launch --vm ubuntu:lunar u01`
 2. Install NGINX web server `lxc exec u01 -- apt-get install nginx --yes`
 3. On the LXD host, create forwarding rule
 4. Test connectivity to the NGINX service, from the host

```
lxc network forward create lxdbr0 0.0.0.0
lxc network forward port add lxdbr0 0.0.0.0 tcp 45522 <vmIP> 80
```

```
curl http://localhost:45522
```

**Comment by tomponline** [comment]
Yes that wont work as firewall dnat rules wont work on the wildcard address. We should block those addresses.
