### ISSUE TITLE
Debian 11 image update : no name resolution for new instance

### ISSUE THREAD

**Issue by LionelHoudelier** [canonical/lxd#11976]
* Distribution: PureOs 10 (Debian 10 based)
 * Distribution version: amd64
 * LXC version: 5.14
 * LXD version: 5.14 with snap
# Issue description
After new instance of debian/11 tonight, just after image update from images repository, no internet connection. 

# Steps to reproduce
 1. lxc launch images:debian/11 myinstance --storage <pool_name>
 2. set profile
 3. restart
 4. IP is correct but no internet
 5. ping: google.com: Temporary failure in name resolution
With debian/10 and debian/12 no problem !

CAUSE: the file /etc/resolv.conf is empty

SOLUTION :
After adding the nameserver like for new debian 10 or 12, the problem gets solved.

**Comment by tomponline** [comment]
The images from `images:` remote are maintained by the https://www.linuxcontainers.org project.
Please can you report this issue at https://github.com/lxc/distrobuilder/issues

Thanks
