### ISSUE TITLE
Allow to overwrite devices on "lxc import"

### ISSUE THREAD

**Issue by Shu-Duan** [canonical/lxd#12000]
# Required information

 * Distribution: Ubuntu
 * Distribution version: focal
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.60
   * LXC version: 5.0.2
   * LXD version: 5.0.2

# Issue description

If I want to export an LXD container from machine A and then import it into machine B.
It is very easy to encounter import failures due to different configurations.
For example, if the `type: disk` is set, but the source path does not exist on machine B.
I have noticed issue [#10114](https://github.com/canonical/lxd/issues/10114), but I believe it does not apply to most cases.
I hope to add a device parameter to override the configuration.
If needed, I can provide a PR. Thanks.

**Comment by tomponline** [comment]
This is a duplicate of https://github.com/canonical/lxd/issues/11889
