### ISSUE TITLE
lxd recover: Failed checking volumes on pool "data": Failed parsing backup file

### ISSUE THREAD

**Issue by StormYudi** [canonical/lxd#12010]
* Distribution: Ubuntu
 * Distribution version:  Ubuntu 22.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-76-generic
   * LXC version: 5.15
   * LXD version: git-afc1356, 2023-07-13 (25239) 
   * Storage backend in use: zfs

# Issue description

Hi, After fixing #11984 , here I am again...
I continued to use the `lxd recover` tool to recover my data, but now I have encountered a new error:
```
linyu@rvh-1:~$ sudo lxd recover
This LXD server currently has the following storage pools:
Would you like to recover another storage pool? (yes/no) [default=no]: yes
Name of the storage pool: data
Name of the storage backend (btrfs, ceph, cephfs, cephobject, dir, lvm, zfs): zfs
Source of the storage pool (block device, volume group, dataset, path, ... as applicable): data
Additional storage pool configuration property (KEY=VALUE, empty when done): zfs.pool_name=data
Additional storage pool configuration property (KEY=VALUE, empty when done): 
Would you like to recover another storage pool? (yes/no) [default=no]: 
The recovery process will be scanning the following storage pools:
 - NEW: "data" (backend="zfs", source="data")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]: 
Scanning for unknown volumes...


Error: Failed validation request: Failed checking volumes on pool "data": Failed parsing backup file "/var/snap/lxd/common/lxd/storage-pools/data/containers/bt564613/backup.yaml": open /var/snap/lxd/common/lxd/storage-pools/data/containers/bt564613/backup.yaml: no such file or directory

```

Any idea? Thank you.

# Steps to reproduce

 1. Throw away my os disk
 2. Try `lxd recover`
 3. Here I am..

**Comment by tomponline** [comment]
Does the ZFS dataset in question have a `backup.yaml` file if you mount the dataset manually?

**Comment by StormYudi** [comment]
I am sorry for my bad zfs & lxd knowledge.
but `bt564613` is just a normal container I created from the centos image. not a block volume created by myself like before.

**Comment by StormYudi** [comment]
Same as I posted before: [https://pastebin.ubuntu.com/p/5XySMgKrjj/](https://pastebin.ubuntu.com/p/5XySMgKrjj/)

I tried `sudo mount -t zfs data/containers/bt564613 /mnt` just now, it seems there is no backup.yaml inside.

```
root@rvh-1:/mnt# ls
metadata.yaml  rootfs  templates
```

**Comment by tomponline** [comment]
Thanks, so that is the issue then. LXD won't be able to perform a recovery if that file is missing.

Do your other instances have a backup.yaml file present?

Is this an issue you can reproduce?

**Comment by StormYudi** [comment]
Yes, I tried another container, 
```
root@rvh-1:/# mount -t zfs data/containers/bt927577 /mnt
root@rvh-1:/# cd /mnt
root@rvh-1:/mnt# ls
backup.yaml  metadata.yaml  rootfs  templates
```

but the container reports error is only 121K
```
data/containers/bt564613                                                             121K  1.58T      839M  legacy
```

Maybe it's broken? and I am going to delete this dataset and try again.

**Comment by tomponline** [comment]
Yes looks like that dataset is missing data somehow.

**Comment by StormYudi** [comment]
I delete that dataset and things are going forward, good sign.
but another problem right here of command `lxd recover`, Could you please take a look for me?
```
Error: Failed validation request: Failed checking volumes on pool "data": Instance "bt370613" in project "default" has no instance information in its backup file
```

It is broken again? Its dataset available space is 0B: 
```
NAME                                                                                          USED  AVAIL     REFER  MOUNTPOINT
data/containers/bt370613                                                            4.66G     0B     2.43G  legacy
```
But I can see tons of snapshots of this container in `zfs list -t all`, I don't know if they are related.

**Comment by tomponline** [comment]
How long has this zfs pool had LXD containers on it, are some of these quite old?

**Comment by StormYudi** [comment]
At least from 2021, I mounted its dataset, but backup.yaml is empty right there.

**Comment by tomponline** [comment]
Do any of your instances have a backup.yaml file?

**Comment by StormYudi** [comment]
I tested a few of them, and they all have a normal backup.yaml file, I can't test all instances because there are too much(~100).

**Comment by tomponline** [comment]
OK so looks like just the odd one or two are corrupted somehow.

**Comment by tomponline** [comment]
Normally the backup.yaml file is written by LXD at instance create time, start time and when its updated.

**Comment by StormYudi** [comment]
okay, I will try to recover data from them and remove their dataset and retry, thanks

**Comment by tomponline** [comment]
I'll close for now. Thanks
