### ISSUE TITLE
Failed to enable LXD ui

### ISSUE THREAD

**Issue by natalytvinova** [canonical/lxd#12038]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info":
 [lxc-info.txt](https://github.com/canonical/lxd/files/12081733/lxc-info.txt)

# Issue description

LXD fails to enable the UI

# Steps to reproduce

`
sudo snap remove lxd --purge
sudo snap install lxd --channel latest/edge
sudo snap install microceph --channel quincy/stable
sudo snap install microovn --channel latest/stable
sudo snap install microcloud --channel latest/edge
sudo snap refresh --hold lxd
sudo snap refresh --hold microcloud
$ sudo microcloud init
Using address "172.27.44.169" for MicroCloud
Limit search for other MicroCloud servers to 172.27.44.169/23? (yes/no) [default=yes]: 
Scanning for eligible servers ...

 Selected "node07ob44" at "172.27.44.170"
 Selected "node09ob44" at "172.27.44.172"
 Selected "node08ob44" at "172.27.44.171"

Would you like to set up local storage? (yes/no) [default=yes]: 
Select exactly one disk from each cluster member:

Select which disks to wipe:

 Using "/dev/disk/by-id/scsi-SATA_KINGSTON_SM2280S_50026B725A030D60" on "node06ob44" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_KINGSTON_SM2280S_50026B725A0BBDEB" on "node07ob44" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_KINGSTON_SM2280S_50026B725A030CDC" on "node08ob44" for local storage pool
 Using "/dev/disk/by-id/scsi-SATA_KINGSTON_SM2280S_50026B725A030BF0" on "node09ob44" for local storage pool

Insufficient number of disks available to set up distributed storage, skipping at this time
Configure distributed networking? (yes/no) [default=yes]: no
Initializing a new cluster
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroOVN is ready
 Local MicroCeph is ready
Awaiting cluster formation ...
 Peer "node08ob44" has joined the cluster
 Peer "node09ob44" has joined the cluster
 Peer "node07ob44" has joined the cluster
Cluster initialization is complete
MicroCloud is ready
sudo snap set lxd ui.enable=true
$ sudo snap restart --reload lxd
Restarted.
$ curl -k https://127.0.0.1:8443
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 
[dmesg.log](https://github.com/canonical/lxd/files/12081712/dmesg.log)

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 
[lxd.log](https://github.com/canonical/lxd/files/12081708/lxd.log)

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue):
[lxc-monitor.log](https://github.com/canonical/lxd/files/12081753/lxc-monitor.log)

**Comment by tomponline** [comment]
Because the UI shares the same starting URL as the LXD REST API there is HTTP user-agent detection for "Gecko" that redirects the `/` request to `/ui/`.

```
curl -k -I -H "User-Agent: Gecko" https://127.0.0.1:8443/
HTTP/2 301 
content-type: application/json
location: /ui/
date: Tue, 18 Jul 2023 14:57:45 GMT
```

Also please note that the LXD UI is not currently LXD cluster aware so using it with MicroCloud is likely to not be a good experience.

**Comment by lotusorrose** [comment]
same on firefox, microsoft edge browsers
