### ISSUE TITLE
Volatile internal state is determined only on snap start

### ISSUE THREAD

**Issue by masnax** [canonical/lxd#12074]
Currently, LXD sets some state information via the [daemon.start](https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft/commands/daemon.start) hook that is set up to run when systemd starts LXD [here](https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft.yaml#L71-L77). This file has several `if` blocks whose conditions are volatile, but LXD will not pick up a change until the next time the snap starts.

In particular, this has caused problems for setting up a LXD cluster with microcloud, so microcloud is now restarting LXD before bootstrapping or joining a cluster. But this is not the most elegant solution.

This problem isn't limited to microcloud either. For example, installing microceph or microovn on a system with an existing LXD setup will result in an error as LXD will not create the appropriate symlinks until a restart:
```bash
# Setup for ceph
echo "==> Setting up ceph configuration"
if [ "${ceph_builtin:-"false"}" = "true" ]; then
    mkdir -p "${SNAP_COMMON}/ceph"
    ln -s "${SNAP_COMMON}/ceph" /etc/ceph
elif [ -e "/var/snap/microceph" ]; then
    ln -s /var/snap/microceph/current/conf/ /etc/ceph
else
    ln -s /var/lib/snapd/hostfs/etc/ceph /etc/ceph
fi
```

There's also other parts of `daemon.start` that may or may not support changing over time: 
```bash
## Handle SSL certs
if [ -e "/var/lib/snapd/hostfs/etc/ssl" ] && [ -e "/var/lib/snapd/hostfs/usr/share/ca-certificates" ]; then
    ln -s "/var/lib/snapd/hostfs/etc/ssl" "/etc/ssl"
    mountpoint -q "/usr/share/ca-certificates" || mount -o ro,bind "/var/lib/snapd/hostfs/usr/share/ca-certificates" "/usr/share/ca-certificates"
else
    ln -s "/snap/core22/current/etc/ssl" "/etc/ssl"
fi

# FIXME: Setup the "lxd" group
if [ "${daemon_group:-"lxd"}" = "lxd" ] && ! getent group lxd >/dev/null 2>&1; then
    echo "==> Creating \"lxd\" group"
    if grep -q "^group.*extrausers" /etc/nsswitch.conf; then
        nsenter -t 1 -m groupadd --system --extrausers lxd || true
    else
        nsenter -t 1 -m groupadd --system lxd || true
    fi
fi
```

----

Ideally, LXD should be able to update this information before it tries to access it (e.g. determining whether to use `microceph` or the hostfs `ceph`). However, this means we need to either incorporate some of this information out of the snap and into `go`, or we need to add some snap actions that let us tell the snap to refresh the volatile subset of `daemon.start`. In my opinion, the latter would be a much cleaner solution, but I'm not sure how much flexibility snapcraft can give us here.

**Comment by tomponline** [comment]
This was solved with snap interfaces right @masnax ?

**Comment by masnax** [comment]
Yes, this was before I knew about content interfaces :)
