### ISSUE TITLE
Canonical LXD Documents Page has many Markdown artifacts in it - should get cleaned up!

### ISSUE THREAD

**Issue by bmullan** [canonical/lxd#12116]
_This new Canonical Documents Page for LXD_ was moved from _**linuxcontainers.org**_ to here:
**[LXD Server and Client](https://github.com/canonical/lxd/blob/main/doc/operation.md#lxd-server-and-client)**

There are _a lot of _Markdown "artifacts"_ in it _that do not read well in a Browser_ and should get cleaned up!

**Comment by ru-fu** [comment]
Please look at the documentation output, not the source: https://documentation.ubuntu.com/lxd/en/latest/operation/

**Comment by ru-fu** [comment]
Please look at the documentation output, not the source: https://documentation.ubuntu.com/lxd/en/latest/operation/
