### ISSUE TITLE
Protect/Lock VMs or Containers from starting

### ISSUE THREAD

**Issue by TumTumTom** [canonical/lxd#12110]
# Required information

-- Feature Request --

 * Distribution: Ubuntu
 * Distribution version: 2204
 * The output of "lxc info" or if that fails:
   * LXD version: 5 Stable
   * Storage backend in use: ZFS Local storage

# Issue description

I want to create VM templates with Windows and Linux and lock them to prevent starting. It will mess up my sysprep configuration. Think of lxc start --all.  It is not (yet) possible to create or convert VMs to templates in LXD. For now, a lock that prevents starting would suffice.

https://discourse.ubuntu.com/t/is-it-possible-to-lock-an-instance/37496/5?u=tomvb

# Steps to reproduce

 1. Step one - Create VM with Windows and sysprep the VM
 2. Step two - lxc start VM name
 3. Step three - Oops, i dont want to start the VM with sysprep, I want to clone the VM with sysprep.

**Comment by tomponline** [comment]
Yes, thanks!

The linked forum thread proposes `security.protection.start` instance setting for this, with the default (unset) value meaning `true`.

**Comment by arvganesh** [comment]
Hi @tomponline. I'm a student from the University of Texas at Austin interested in looking into this issue as a part of my virtualization class (CS 360V). What's the status of this issue?

**Comment by arvganesh** [comment]
Hi @tomponline, do you think I need a Windows machine to look into this issue?

**Comment by qianzhangxa** [comment]
@tomponline I see the PR #13454 has been closed, can I work on this issue by creating another PR?

**Comment by tomponline** [comment]
Hi @qianzhangxa that would be great thanks!

**Comment by qianzhangxa** [comment]
@tomponline I am trying to set up my own LXD development env on a Ubuntu 22.04 VM, I followed the steps at https://documentation.ubuntu.com/lxd/en/latest/installing/#install-lxd-from-source and built LXD binaries successfully. When I manually ran the LXD daemon, there were some warnings:

```
$ sudo -E PATH=${PATH} LD_LIBRARY_PATH=${LD_LIBRARY_PATH} $(go env GOPATH)/bin/lxd --group sudo 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup blkio, disk I/O limits will be ignored 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup blkio.weight, disk priority will be ignored 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup CPU controller, CPU time limits will be ignored 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup CPUacct controller, CPU accounting will not be available 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup CPU controller, CPU pinning will be ignored 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored 
WARNING[2024-07-25T11:04:48+08:00]  - Couldn't find the CGroup network priority controller, per-instance network priority will be ignored. Please use per-device limits.priority instead 
WARNING[2024-07-25T11:04:48+08:00] Instance type not operational                 driver=qemu err="KVM support is missing (no /dev/kvm)" type=virtual-machine
```

Can you please please let me know why there were such warnings? And will they affect the functionalities of LXD?

Sorry I think I should have posted the above question in https://discourse.ubuntu.com/c/lxd/126, but after I login Discourse, I do not find the new topic button which is a bit weird, maybe I do not have the permission yet?

![image](https://github.com/user-attachments/assets/f60e25c4-64ab-4792-9bc1-5b4e624a9c66)

**Comment by tomponline** [comment]
> Can you please please let me know why there were such warnings? And will they affect the functionalities of LXD?

This shouldn't affect your ability to work on lock feature, it just means you cant launch VMs as your host doesn't have KVM support. Containers should work fine though.

**Comment by qianzhangxa** [comment]
@tomponline How about those cgroup related warnings? Will that affect the container functionalities of LXD?

**Comment by tomponline** [comment]
Not for development of this feature
