### ISSUE TITLE
Containers is not start in alpine linux

### ISSUE THREAD

**Issue by ne-vlezay80** [canonical/lxd#12123]
# Required information

 * Distribution: Alpine Linux
 * Distribution version: 3.18.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.43-0-virt
   * LXC version: 5.0.2
   * LXD version: 5.0.2
   * Storage backend in use: dir

# Cjntainer is not start in alpine linux
After upgrade alpine linux lxd containers is not start.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
/home/nevlezay80 # lxc info --show-log gw
Name: gw
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2023/06/22 11:14 UTC
Last Used: 2023/08/06 07:07 UTC

Log:

lxc gw 20230806070755.479 ERROR    conf - ../src/lxc/conf.c:lxc_map_ids:3701 - newuidmap failed to write mapping "newuidmap: Target process 2134 is owned by a different user: uid:0 pw_uid:0 st_uid": newuidmap 2134 0 100000 65536
lxc gw 20230806070755.479 ERROR    start - ../src/lxc/start.c:lxc_spawn:1788 - Failed to set up id mapping.
lxc gw 20230806070755.479 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:878 - Received container state "ABORTING" instead of "RUNNING"
lxc gw 20230806070755.482 ERROR    start - ../src/lxc/start.c:__lxc_start:2107 - Failed to spawn container "gw"
lxc gw 20230806070755.482 WARN     start - ../src/lxc/start.c:lxc_abort:1036 - No such process - Failed to send SIGKILL via pidfd 45 for process 2134
lxc 20230806070800.611 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20230806070800.611 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:128 - Failed to receive file descriptors for command "get_state"

**Comment by ne-vlezay80** [comment]
This problem is related to the fact that, lxd running from root and group lxd.
Problem solved after starting lxd from group root.

**Comment by tomponline** [comment]
Thanks!
