### ISSUE TITLE
Weblate info needs to be updated

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12121]
https://hosted.weblate.org/projects/linux-containers/lxd/#information still has some bits pointing to linuxcontainers.org and the account name is probably confusing at this point.

**Comment by tomponline** [comment]
I'm not sure if that's possible without splitting the organization but ill check.

**Comment by tomponline** [comment]
Updated info https://hosted.weblate.org/projects/lxd/lxd/#information
