### ISSUE TITLE
lxd-migrate should not just tell the user that instance name is incorrect and quit

### ISSUE THREAD

**Issue by m0nkey-br4in** [canonical/lxd#12130]
lxd-migrate version 5.15

Name of new instance is the second question it asks you in the process of migration, then it makes you go through the motions of configuring everything, then finally you press `1` to begin the transfer process and get this:
`"Error: Invalid instance name: Name can only contain alphanumeric and hyphen characters"`
And then it exits.

I had some choice words to say about the designer of this UI interaction. Since I've cooled down a bit, all I can say is that the program shouldn't behave like this. It should tell you about incorrect name right after you enter it, and it shouldn't just quit, it should let you change it.

**Comment by tomponline** [comment]
Yeah I think we should certainly make improvements to the user experience in lxd-migrate, some ideas come to mind:

-     Better client side validation.
-     Command flags to allow it to run in non-interactive mode.
-     Allow talking to local LXD server over unix socket.
