### ISSUE TITLE
Support USB-BUS id & DeivceID to attach usb device to container

### ISSUE THREAD

**Issue by bigtrouble** [canonical/lxd#12147]
# Issue description
I have some phones of the same model, will be added to different containers.
but their **VendorId** and **ProductId** are the same.
With the current options I have no way of identifying them.

**lsusb**
```
Bus 002 Device 002: ID 05e3:0626 Genesys Logic, Inc. Hub
Bus 001 Device 010: ID 18d1:4ee7 Google Inc. Nexus/Pixel Device (charging + debug)
Bus 001 Device 007: ID 18d1:4ee7 Google Inc. Nexus/Pixel Device (charging + debug)
....
....
```
Perhaps it can only be identified by USB-BUS-ID & Device ID.

---
By the way, I found the options following ：
Key         | Type      | Default           | Description
:--         | :--       | :--               | :--
`gid`       | int       | `0`               | Only for containers: GID of the device owner in the instance
`mode`      | int       | `0660`            | Only for containers: Mode of the device in the instance
`productid` | string    | -                 | The product ID of the USB device
`required`  | bool      | `false`           | Whether this device is required to start the instance (the default is `false`, and all devices can be hotplugged)
`uid`       | int       | `0`               | Only for containers: UID of the device owner in the instance
`vendorid`  | string    | -                 | The vendor ID of the USB device

**Comment by bigtrouble** [comment]
When using VirutalBox more conditions can be used for filtering, 
hope lxd can support them too.
Serial will be more useful when using Android phone.
---
![image](https://github.com/canonical/lxd/assets/7983171/320e67e2-b3e5-4b43-9bbc-ee6aefbf9446)

**Comment by tomponline** [comment]
Fixed by https://github.com/canonical/lxd/pull/13419
