### ISSUE TITLE
Shutdown Windows VMs with lxd stop command

### ISSUE THREAD

**Issue by TomTomvB** [canonical/lxd#12141]
# Required information

Feature request / ACPI

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  5.15.0-78-generic
   * LXC version: 5.0.2
   * LXD version: 5.0.2
   * Storage backend in use: ZFS 

# Issue description

1. Installed Windows Server 22 in Virtual Machine with ISO
2. Installed the latest virtio drivers in Windows
3. Need to update the host with Ubuntu 22.04 and have to stop all VMs
4. All VM's turned off with lxc stop --all **except** the Windows VMs with VirtIO drivers.

How can I turn of Windows VMs without connecting to it?

**Comment by tomponline** [comment]
`lxc stop <instance>` already issues ACPI shutdown request. I wonder if the windows OS is not responding for some reason.

**Comment by tomponline** [comment]
I just tried this with a windows 11 VM I had on LXD and issuing `lxc stop <instance>` caused Windows to shutdown and stop cleanly.

**Comment by tomponline** [comment]
Did you use distrobuilder to generate your Windows ISO?

https://linuxcontainers.org/distrobuilder/docs/latest/tutorials/use/#repack-windows-iso

**Comment by tomponline** [comment]
Please let us know if you continue to experience this.
