### ISSUE TITLE
documention is ordered alphabetically

### ISSUE THREAD

**Issue by eslerm** [canonical/lxd#12155]
All docs are listed in alphabetical order. As an example, the [getting_started](https://documentation.ubuntu.com/lxd/en/latest/getting_started/) page lists subpages alphabetically instead of a logical order:

- [Access the UI](https://documentation.ubuntu.com/lxd/en/latest/howto/access_ui/)
- [Contribute to LXD](https://documentation.ubuntu.com/lxd/en/latest/contributing/)
- [Get support](https://documentation.ubuntu.com/lxd/en/latest/support/)
- [Initialize LXD](https://documentation.ubuntu.com/lxd/en/latest/howto/initialize/)
- [Install LXD](https://documentation.ubuntu.com/lxd/en/latest/installing/)

It makes more since to list Install LXD before Initialize LXD.

---
Document: getting_started.md

**Comment by tomponline** [comment]
FWIW I agree that in this specific example of the getting started page the ordering of the links don't really guide the user through a normal LXD experience (i.e install, initialize, access the UI, get support, contribute).

**Comment by eslerm** [comment]
Thank you for looking into this.

Please feel free to change the title to something more appropriate.

The resulting work of ordering the previous website can be found [here](https://web.archive.org/web/20230531030912/https://linuxcontainers.org/lxd/docs/latest/getting_started/). Sections beyond `getting_started` may be clearer with re-ordering as well.

**Comment by ru-fu** [comment]
> The resulting work of ordering the previous website can be found [here](https://web.archive.org/web/20230531030912/https://linuxcontainers.org/lxd/docs/latest/getting_started/). Sections beyond `getting_started` may be clearer with re-ordering as well.

Btw, you can switch to the old navigation by selecting "Switch to topical navigation". No need to go through the web archive.

**Comment by eslerm** [comment]
Thank you! [That looks great!](https://documentation.ubuntu.com/lxd/to/latest/index_topical/)

**Comment by tomponline** [comment]
@ru-fu is this still relevant? Or should it be closed?

**Comment by ru-fu** [comment]
This can be closed.
