### ISSUE TITLE
LXD 5.15 fails to determine resources

### ISSUE THREAD

**Issue by morphis** [canonical/lxd#12153]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2.0-26-generic #26~22.04.1-Ubuntu 
   * LXC version: 5.0.2
   * LXD version: 5.15-002fa0f
   * Storage backend in use:

# Issue description

Trying to determine resources on a Thinkpad T14 Gen 2 fails with the following error:

```
$ lxc info --resources
Error: Failed to retrieve network information: Failed to add device information for "/sys/class/net/wwan0/device": Failed to read "/sys/class/net/wwan0/device/device": read /sys/class/net/wwan0/device/device: is a directory
```

# Steps to reproduce

 1. Run `lxc info --resource`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by mihalicyn** [comment]
@morphis
Hi Simon, couldn't you also provide this info:
```
ls -la /sys/class/net/
ls -la /sys/class/net/wwan0
ls -la /sys/class/net/wwan0/device
ip -d link
```

For a PCI device "device" is [always a file](https://github.com/torvalds/linux/blob/99d99825fc075fd24b60cc9cf0fb1e20b9c16b0f/drivers/pci/pci-sysfs.c#L49), not a directory. So I need this info to understand your system configuration.

(you can send me this info privately in MM to not post MAC addresses and stuff here publicly or remove all sensitive data from output)

**Comment by skatsaounis** [comment]
I am facing the same issue with slightly newer versions.

LXD installed with snap: `5.17-e5ead86`
Kernel version: `6.2.0-32-generic`

**Comment by tomponline** [comment]
@skatsaounis please can you supply the info @mihalicyn asked in https://github.com/canonical/lxd/issues/12153#issuecomment-1702489290

**Comment by skatsaounis** [comment]
@tomponline I already did privately. I am monitoring this issue and if more information is required I will gladly provide it.

**Comment by tomponline** [comment]
Thanks!

**Comment by skatsaounis** [comment]
Actually, I can share some info here after investigating myself. My laptop has a SIM module for mobile broadband. As it can be seen, this device consists of 3 devices:

```
# ll --time-style='+' /sys/class/net/wwan0/device/
total 0
drwxr-xr-x 7 root root    0  ./
drwxr-xr-x 3 root root    0  ../
lrwxrwxrwx 1 root root    0  device -> ../../../0000:08:00.0/
-r--r--r-- 1 root root 4096  index
drwxr-xr-x 3 root root    0  net/
drwxr-xr-x 2 root root    0  power/
lrwxrwxrwx 1 root root    0  subsystem -> ../../../../../../class/wwan/
-rw-r--r-- 1 root root 4096  uevent
drwxr-xr-x 3 root root    0  wwan0at0/
drwxr-xr-x 3 root root    0  wwan0at1/
drwxr-xr-x 3 root root    0  wwan0mbim0/
```

Additionally, the information that lxd is expecting to find is one `/device` directory deeper:

```
# cat /sys/class/net/wwan0/device/device/device 
0x7560
```
