### ISSUE TITLE
Remove edk patch from snap once next stable release is out

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12166]
See https://github.com/tianocore/edk2/commit/c1e853769046b322690ad336fdb98966757e7414

See also https://github.com/canonical/lxd-pkg-snap/pull/134#issuecomment-1684006511

**Comment by simondeziel** [comment]
> See [tianocore/edk2@c1e8537](https://github.com/tianocore/edk2/commit/c1e853769046b322690ad336fdb98966757e7414)

https://github.com/tianocore/edk2/commit/c1e853769046b322690ad336fdb98966757e7414 says:

> Older linux kernels have problems with phys-bits larger than 46,
> ubuntu 18.04 (kernel 4.15) has been reported to be affected.

But 18.04 is out of regular support so maybe we can proceed now?

**Comment by tomponline** [comment]
We still need to support booting guests with older kernels.

**Comment by tomponline** [comment]
@mihalicyn can we close this now?

**Comment by tomponline** [comment]
@mihalicyn can we close this now?

**Comment by mihalicyn** [comment]
Yes, we can, because we have dropped this patch already as it's included in the upstream tree.
