### ISSUE TITLE
Ceph storage create pool has a possibility of deleting exist pool

### ISSUE THREAD

**Issue by yo004192** [canonical/lxd#12163]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-78-generic
   * LXC version: 5.15
   * LXD version: 5.15
   * Storage backend in use: ceph

# Issue description
If someone try to create a ceph storage which has the same name as an exist one, the exist pool may be deleted

here checks whether ceph pool is exist
[check pool](https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L153)

the osdPoolExists() checks pool exist by cmd return
[osdPoolExists 1](https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph_utils.go#L49)

This means if there’s a temp error (network jitter or any other reason) about ceph while osdPoolExists() querying, lxd will try to create pool.
And if the error fix at a short time, lxd will create fail beacuse of the name of pool is exist, and delete the exist pool by revert?

# Steps to reproduce

 1. create a pool named ‘remote3’: lxc storage create remote3 ceph --verbose
 2. change my ceph key to a wrong value
 3. create a pool named ‘remote3’ again: lxc storage create remote3 ceph --verbose
 4. set correct ceph key immediately, and ‘remote3’ will be delete by lxd.
Deleting will also happen even if I set ctrl+C to stop lxd commend after step 3. If I do this, there’s even no error log on my terminal

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
The reverter only has the pool removal added to it after pool creation command succeeds:

https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L154-L167

Are you saying that the pool creation command succeeds even if the pool already exists?

**Comment by yo004192** [comment]
> 
yes.
Follow my step, I tried to log out cmdline and ret value in golang, there's no errors on TryRunCommand() create cmd.
I also tried use ceph directly like "ceph --name client.admin --cluster ceph osd pool create remote3 32", even if it returned "pool 'remote3' already exists", the return of cmd is 0 (use "echo $?" to get return value).

**Comment by yo004192** [comment]
> The reverter only has the pool removal added to it after pool creation command succeeds:
> 
> https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L154-L167
> 
> Are you saying that the pool creation command succeeds even if the pool already exists?

yes.
Follow my step, I tried to log out cmdline and ret value in golang, there's no errors on TryRunCommand() create cmd.
I also tried use ceph directly like "ceph --name client.admin --cluster ceph osd pool create remote3 32", even if it returned "pool 'remote3' already exists", the return of cmd is 0 (use "echo $?" to get return value).

**Comment by yo004192** [comment]
> > The reverter only has the pool removal added to it after pool creation command succeeds:
> > https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L154-L167
> > 
> > Are you saying that the pool creation command succeeds even if the pool already exists?
> 
> yes. Follow my step, I tried to log out cmdline and ret value in golang, there's no errors on TryRunCommand() create cmd. I also tried use ceph directly like "ceph --name client.admin --cluster ceph osd pool create remote3 32", even if it returned "pool 'remote3' already exists", the return of cmd is 0 (use "echo $?" to get return value).

It can also be reproduced easily by setting here into true
https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L153

**Comment by gabrielmougard** [comment]
@tomponline naively looking at this for the first time and I thought, couldn't we have some kind of exponential backoff inside `osdPoolExists` with a given number of retries ? That way, we avoid returning an error straight away (if the issue is 'temporary'). And we return an error if we reach the end of the retry counter.. Would it work ?

**Comment by tomponline** [comment]
What we need is for `osdPoolExists()` to return a bool and an error and then differentiate between an error in verifying whether a pool exists compared to a pool definitely not existing.

Even better would be to modify the https://github.com/canonical/lxd/blob/c77ee90f5032f862e4a514bed76ee736693ba64d/lxd/storage/drivers/driver_ceph.go#L154-L167 call somehow to fail if the pool already exists.

**Comment by gabrielmougard** [comment]
I agree. So we'd have no choice but to parse the stdout of this command as the exit code seems to be zero for an existing pool..

**Comment by tomponline** [comment]
I would check the options available for that command first before resorting to that.

**Comment by gabrielmougard** [comment]
I made a few test with a minimal microcloud (with 3 microceph nodes) config. With an existing `lxd_remote` pool, doing :

```
# Let's try to create a pool of 2 PGs
$ microceph.ceph osd pool create lxd_remote 2
pool 'lxd_remote' already exists
$ echo $?
0
```
I inspected the `osd pool create <pool_name>` options but none of them enable a 'strictier' behaviour so that the return code could be something else than 0. Only `osd pool get <pool_name> ..` returns a code 2 when a pool definitely not exist.
