### ISSUE TITLE
Error running "lxd init --minimal" on Ubuntu 23.04

### ISSUE THREAD

**Issue by thatLeaflet** [canonical/lxd#12167]
I'm new to building snaps and just had a really confusing issue. The crux of the issue is that running "lxd init --minimal" will return the following error on Ubuntu 23.04
```
Error: Failed to connect to local LXD: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied
```

Initially I thought this was a sudo issue, but running the command as sudo did not work. Eventually I tried running the same command in a 22.04 LTS VM and everything worked fine and I was able to build the gnome-calculator snap. However, I tried running the same command in a freshly created 23.04 VM and it also failed like it did on my host 23.04 PC.

Running kernel 6.2.0-27-generic and here's some system info:
```
Name                       Version                     Rev
bare                       1.0                         5
core18                     20230530                    2785
core20                     20230622                    1974
core22                     20230725                    858
lxd                        5.15-002fa0f                25112
snapd                      2.59.5                      19457
```

**Comment by tomponline** [comment]
@thatLeaflet are you still experiencing this issue?

**Comment by thatLeaflet** [comment]
Yes, it's also occuring in the 23.10 beta. A simple chmod 777 on the socket fixed the issue, but I imagine that solution has security implications.

**Comment by tomponline** [comment]
How are you install the snap you build?

**Comment by thatLeaflet** [comment]
```
sudo snap refresh
sudo snap install lxd
```
Then I run the actual command
```
lxd init --minimal
```
This issue was reproducible on all the Ubuntu 23.04+ VMs and actual installations I've tried it on, all clean installs.

**Comment by tomponline** [comment]
So you're not building snaps, just installing them?

**Comment by thatLeaflet** [comment]
I installed lxd to build snaps, but building core22 snaps fails because lxd isn't initialized. Once lxd is initialized, like I managed to do by doing chmod 777 on the socket, snaps were able to be built.

**Comment by tomponline** [comment]
Your user needs to be part of the lxd group before it can access the LXD socket.

**Comment by thatLeaflet** [comment]
I didn't need to do anything with groups on 22.04 LTS, it worked out of the box.

When I was troubleshooting the issue on 23.04+, I came across [this](https://discourse.ubuntu.com/t/easy-multi-user-lxd-setup/26215) which suggested all I had to do to get it working is to run `snap set lxd daemon.user.group=users`. But that didn't work. I also tried doing it the system way with `adduser` and that didn't work.

If you have any specific way you want me to test the issue, I can try.

**Comment by tomponline** [comment]
What does `groups <your user>` show?

**Comment by thatLeaflet** [comment]
`leaflet : leaflet adm cdrom sudo dip plugdev users lpadmin`

**Comment by tomponline** [comment]
You need to add your user to the lxd group to access the socket

**Comment by tomponline** [comment]
https://documentation.ubuntu.com/lxd/en/latest/installing/#manage-access-to-lxd
