### ISSUE TITLE
`lxc --help` hides a "random" set of commands

### ISSUE THREAD

**Issue by ru-fu** [canonical/lxd#12175]
When you run `lxc --help`, some commands are missing from the list. These can be displayed by adding `--all`, but it seems quite random which commands are hidden, namely:

- init
- manpage
- monitor
- pause
- query

It makes sense to me to hide the manpage command, but all others (maybe except for the pause command?) are frequently used and should not be hidden imo.

Also, the `lxc manpage` command does NOT have a `--all` flag, so it isn't possible to generate documentation for hidden commands.

**Comment by victoitor** [comment]
I've been using `lxc shell` and it doesn't show up even with `--all`

**Comment by ru-fu** [comment]
Afaik, `shell` is an alias and not a command, which would explain this.

But it's probably worth a discussion whether it should be hidden or not.

**Comment by victoitor** [comment]
It's not present in `lxc alias list` either. It is quite hidden.

**Comment by simondeziel** [comment]
> It makes sense to me to hide the manpage command, but all others (maybe except for the pause command?) are frequently used and should not be hidden imo.

Someone just inquired about `lxc pause` in `#lxd` :)

**Comment by monstermunchkin** [comment]
cobra doesn't support generating docs for hidden commands. It calls the `IsAvailableCommand()` for every command, and only generates the docs if this is true. However, all hidden commands return `false` so there's nothing we can do there.

**Comment by ru-fu** [comment]
Guess that means we should "unhide" them. ;)

**Comment by tomponline** [comment]
Unhiding `pause`, `freeze` (alias of pause) and `init` make sense to me as they operate on an instance and are not debugging tools.

I agree `manpage` should stay hidden.

I think `query` really should stay hidden, that is a very dangerous command that is very easy to do real damage to your LXD database and should only be needed when doing guided debugging.

As for `lxc monitor` I am on the fence.

**Comment by ru-fu** [comment]
> I think `query` really should stay hidden, that is a very dangerous command that is very easy to do real damage to your LXD database and should only be needed when doing guided debugging.

We're telling people to use `lxc query` to test the API: https://documentation.ubuntu.com/lxd/en/latest/rest-api/
And I'm also using `lxc query` for all API instructions. 
Why is it dangerous?

**Comment by tomponline** [comment]
> > I think `query` really should stay hidden, that is a very dangerous command that is very easy to do real damage to your LXD database and should only be needed when doing guided debugging.
> 
> We're telling people to use `lxc query` to test the API: https://documentation.ubuntu.com/lxd/en/latest/rest-api/ And I'm also using `lxc query` for all API instructions. Why is it dangerous?

You're absolutely right, sorry I was thinking of `lxd sql query`.

Yes in that case lets unhide it.

**Comment by tomponline** [comment]
So lets just have `manpage` as hidden.
