### ISSUE TITLE
resources.GetStorage() resturns the wrong serial nr for disks

### ISSUE THREAD

**Issue by gabriel-samfira** [canonical/lxd#12209]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04

# Issue description

I stumbled across this issue while trying to commission a node in MAAS. For context, MAAS has the [host-info](https://github.com/maas/maas/tree/master/src/host-info) binary that gathers system information and which leverages the `resources` library in LXD.

While commissioning, the `smartctl-validate`  tests fail due to the fact that the disks MAAS says should be there (after running the `machine-resources` binary), cannot be found. This seems to happen because there is a mismatch between what MAAS thinks the serial is and what `lsblk` sees as the serial.  The current implementation in the lxd `resources` package seems to return the `WWN`.

The `resourced.GetStorage()` function [returns the wrong serial number](https://github.com/canonical/lxd/blob/main/lxd/resources/storage.go#L86C24-L88) on systems where both `ID_SCSI_SERIAL` and `ID_SERIAL_SHORT` are set, and where they differ (such as a `HPE ProLiant DL385 Gen10 Plus v2` - and others I suspect).

To work around this, I copied the way [`util-linux` handles serial numbers](https://github.com/util-linux/util-linux/blob/8e89dd8bacbd110cd6fea9baab176993fe5270b9/misc-utils/lsblk-properties.c#L122-L128). Namely, look for the following keys, in order:

* `SCSI_IDENT_SERIAL`
* `ID_SCSI_SERIAL`
* `ID_SERIAL_SHORT`
* `ID_SERIAL`

# Steps to reproduce

 1. Attempt to run the MAAS `smartctl-validate` tests on a machine where:

```bash
udevadm info --export-db | grep "SCSI_IDENT_SERIAL\|ID_SCSI_SERIAL\|ID_SERIAL_SHORT"

E: SCSI_IDENT_SERIAL=S6MKNA0Wxxxxx
E: ID_SERIAL_SHORT=5002xxxxxxxx
```

yields different results for `SCSI_IDENT_SERIAL` and `ID_SERIAL_SHORT`.

More info:

```bash
root@ubuntu:~# ls -l /dev/disk/by-id/wwn-0x5002xxxxxxxx
lrwxrwxrwx 1 root root 9 Sep  3 14:21 /dev/disk/by-id/wwn-0x5002xxxxxxxx -> ../../sdh
root@ubuntu:~# lsblk -o +SERIAL /dev/sdh
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS SERIAL
sdh    8:112  0   7T  0 disk             S6MKNA0Wxxxxx
```

**Comment by tomponline** [comment]
@gabrielmougard please can you look into this when you can, it seems similar to the issue you looked at wrt to device names recently. Thanks

**Comment by gabriel-samfira** [comment]
might be related to this as well: https://bugs.launchpad.net/maas/3.2/+bug/1967322
