### ISSUE TITLE
lxc list shows duplicate entries for containers, one that's running and one that's stopped.

### ISSUE THREAD

**Issue by jonoinnz** [canonical/lxd#12224]
Hi LXD Team,

Firstly, thank you for a great product and the support.

Not sure if this is a bug in 5.17 or if something went wrong in our cluster.

# Required information

driver: lxc
  driver_version: 5.0.3
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.4.0-120-generic
  os_name: Ubuntu
  os_version: "20.04"
  storage: zfs
  storage_version: 0.8.3-1ubuntu12.13

# Issue description

We've upgraded from 5.15-x to 5.17-e5ead86, After the update  one of the nodes in the cluster has duplicate entries for the containers:

root@lxdvm-gen2-minio-01.uat-01.example.com:/var/snap/lxd/common/lxd/database# lxc list|grep -i minio
| mcon-minio-web-customer-01-uat-01-example-com                  | RUNNING | 172.16.147.6 (eth0)  |      | CONTAINER | 0         | lxdvm-gen2-minio-01.uat-01.example.com             |
| mcon-minio-web-customer-01-uat-01-example-com                  | STOPPED |                      |      | CONTAINER | 0         | lxdvm-gen2-minio-01.uat-01.example.com             |

lxd sql global "SELECT * FROM instances" does not show the duplicates.

lxc stop will stop the running container, and then lxc start will start the one that was running before. How do we get rid of the duplicate?

# Steps to reproduce

Upgraded from 5.15 to 5.17

Regards,
Jonathan

**Comment by jonoinnz** [comment]
Yep:

root@lxdvm-gen2-minio-01.uat-01.example.com:/var/snap/lxd/common/lxd/database# lxc query /1.0/instances|grep minio
        "/1.0/instances/mcon-minio-web-customer-01-uat-01-example-com",
        "/1.0/instances/mcon-minio-web-customer-01-uat-01-example-com",

**Comment by tomponline** [comment]
Please can we see the output of:

```
lxd sql global "SELECT * FROM instances"
```

Thanks

**Comment by tomponline** [comment]
Also, does this happen on all cluster members or only some of them?
I.e. do you get different output if you run `lxc list` on different cluster members?

**Comment by monstermunchkin** [comment]
@jonoinnz since you're using zfs, what does your storage config look like?

**Comment by monstermunchkin** [comment]
@jonoinnz Does the problem persist even after a cluster restart?

**Comment by jonoinnz** [comment]
> lxd sql global "SELECT * FROM instances"

root@lxdvm-gen2-minio-01.uat-01.example.com:/var/snap/lxd/common/lxd/database# lxd sql global "SELECT * FROM instances"|grep -i minio
| 18 | 1       | mcon-minio-web-customer-01-uat-01-example.com      | 2            | 0    | 0         | 2022-09-07T02:34:29.656934444Z | 0        | 2023-09-06T23:45:57.908316304Z |             | 1          | 0001-01-01T00:00:00Z |

**Comment by jonoinnz** [comment]
> Also, does this happen on all cluster members or only some of them? I.e. do you get different output if you run `lxc list` on different cluster members?

Yep, happens on all of the cluster members.

**Comment by jonoinnz** [comment]
> @jonoinnz Does the problem persist even after a cluster restart?

Just restarting the node in the cluster that has the containers running that are showing as duplicates?

**Comment by jonoinnz** [comment]
> @jonoinnz since you're using zfs, what does your storage config look like?

lxc storage list
+-------+--------+-------------+---------+---------+
| NAME  | DRIVER | DESCRIPTION | USED BY |  STATE  |
+-------+--------+-------------+---------+---------+
| local | zfs    |             | 79      | CREATED |
+-------+--------+-------------+---------+---------+

Containers are stored in ZPOOL/lxc/containers

**Comment by monstermunchkin** [comment]
> Just restarting the node in the cluster that has the containers running that are showing as duplicates?

Either that, or all cluster members. I'm just curious if this is a temporarily bad state of one or more cluster members, or if this persists across cluster restarts.

**Comment by jonoinnz** [comment]
> > Just restarting the node in the cluster that has the containers running that are showing as duplicates?
> 
> Either that, or all cluster members. I'm just curious if this is a temporarily bad state of one or more cluster members, or if this persists across cluster restarts.

It's a bit of a tricky one, we will have the schedule outages as this is production. We will schedule it and I will update here with the results.

**Comment by tomponline** [comment]
`systemctl reload snap.lxd.daemon` will reload LXD without restarting instances.

**Comment by monstermunchkin** [comment]
@jonoinnz any news on this? Does the problem still persist?

**Comment by jonoinnz** [comment]
Apologies for the delay in checking, I have restarted the the instances with the reload and am happy to report that the duplicates are gone. Thank you to everyone for the support, keep up the great work.

**Comment by tomponline** [comment]
OK thanks we will close this for now and if you see it again in LXD 5.18 please advise. Thanks
