### ISSUE TITLE
colorscheme on documentation.ubuntu.com

### ISSUE THREAD

**Issue by omani** [canonical/lxd#12244]
it boggles my mind how any human can come up with this colorscheme:
![2023-09-12-172043_948x692_scrot](https://github.com/canonical/lxd/assets/3346207/ae6953c0-8136-4cc0-9017-cc99d8483904)

can anyone read this text? especially the blue colored text?

**Comment by ru-fu** [comment]
You can switch to the light theme by clicking the "moon" icon in the upper right-hand corner:
![image](https://github.com/canonical/lxd/assets/11227796/da3648e6-36f8-4efa-8438-79a773567848)

I'm not a fan of dark mode myself and find the light mode much easier to read, but some people prefer the dark theme. I guess it depends on your device (and your preference, of course).
