### ISSUE TITLE
LXD 5.0 panics when setting `rbac.api.url` is not authorized

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12261]
While testing https://github.com/canonical/lxd-ci/pull/5 I ran into a panic with LXD `5.0/edge` snap. After switching to the `rbac-user` remote, trying to set `rbac.api.url` causes a panic:

```
...
# lxc remote switch rbac-user
# lxc config set rbac.api.url https://services.monstermunchkin.dev/rbac
panic: assignment to entry in nil map

goroutine 1 [running]:
main.(*cmdConfigSet).Run(0xc00024a730, 0x0?, {0xc00022f120?, 0x2, 0x2})
	/build/lxd/parts/lxd/src/lxc/config.go:604 +0x5d4
github.com/spf13/cobra.(*Command).execute(0xc00024c900, {0xc00022f0c0, 0x2, 0x2})
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/build/lxd/parts/lxd/src/lxc/main.go:276 +0x1a38
```

Snap info:

```
# snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-cf3f355  25275  5.0/edge  canonical✓  -
```

I could **not** reproduce the issue with the `latest/edge` snap:

```
# lxc remote switch local
# lxc config set rbac.api.url https://services.monstermunchkin.dev/rbac
# lxc remote switch rbac-user
# lxc config set rbac.api.url https://services.monstermunchkin.dev/rbac
Error: not authorized

# snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-b3fd3c8  25641  latest/edge  canonical✓  -
```

**Comment by tomponline** [comment]
Can you retest this once I've finished back porting the next LTS release as we are part way through and I know there are some rbac changes pending. If you see this on latest/edge or 5.0/candidate then its an issue.

**Comment by simondeziel** [comment]
This was on `5.0/edge` already. If you still have more rbac fixes to backport, I'll happily wait and retest.

**Comment by tomponline** [comment]
Yeah I'm still part way through back porting changes so we will see if its fixed once I'm done.

**Comment by simondeziel** [comment]
I tried reproducing the issue with the same 5.0/edge rev as before and couldn't as trying to change the config brings up the SSO login page. So unfortunately, I can no longer reproduce with the old rev nor the new one, sorry.

**Comment by tomponline** [comment]
I'm not quite following you I'm afraid, can you pass the single sign on and then try changing the config again?

**Comment by simondeziel** [comment]
No that's the thing. After authenticating, I'm denied access. Before it wouldn't even get then and simply crash IIRC.
