### ISSUE TITLE
Loki logs should include an `instance` label indicating which LXD server generated the event

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12290]
As part of #12279, it was identified that Loki logs would be more useful if they could include an `instance` label indicating which server sent the log. This is akin to the Prometheus `instance` label that indicates which server was scraped by Prometheus. The difference being that LXD pushes to Loki so it needs to self-report its `instance` label.

**Comment by monstermunchkin** [comment]
Loki events already contain an instance label. It might be omitted for non-cluster servers, but cluster members should set this.

https://github.com/canonical/lxd/blob/2d8481712055d0cbb3bd952e25a1df469939990d/lxd/loki/loki.go#L235-L244

**Comment by monstermunchkin** [comment]
I can confirm that the location label is set correctly when running a cluster, therefore I'm closing this for now.

**Comment by simondeziel** [comment]
@monstermunchkin you mentioned the `location` label which reports what's the cluster member that is involved with the event, that's fine and works already.

However, the goal of an `instance` label is to identify which LXD server streamed that log to Loki. This is something you need irrespective of using a cluster or not. Say for example I configure Loki at home and tell my 3 standalone LXD servers to stream to Loki. How could I tell which log event originate from which server? That's where the `instance` comes in. This is really like the `instance` label for Prometheus that let's you know which LXD server was scrapped but with Loki, this needs to be self-reported as that's a push model, not pull like Prometheus.

**Comment by tomponline** [comment]
I think we've used hostname in non-clustered environments for something similar in the past (although memory isn't serving me specifically what atm).

**Comment by simondeziel** [comment]
Yeah, the hostname (a FQDN?) would do. For consistency, the label should still be called `instance` however. Otherwise it becomes confusing.

**Comment by tomponline** [comment]
https://github.com/canonical/lxd/blob/8a78b655ba2dc9e5fa72deb8b6b101baa53b9c8f/lxd/api_1.0.go#L259-L270
