### ISSUE TITLE
Improper Loki event types

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12292]
# `loki.labels` config

`lxc config set loki.labels="baz"` causes the following event to be logged:

```
# logcli query -t '{app="lxd"}'
2023-09-21T17:02:41Z {app="lxd", location="none", type="lifecycle"} requester-protocol="unix" requester-username="root" action="config-updated" source="/1.0" requester-address="@" config-updated
```
`lxc monitor` also shows this `config-updated` event:

```
INFO   [2023-09-21T17:02:41Z] Action: config-updated, Source: /1.0, Requestor: unix/root (@)
```

However it feels like it belongs to `type=logging`.

# `core.https_address` config

`lxc config set core.https_address :443` causes the following events to be logged:

```
# logcli query -t '{app="lxd"}'
2023-09-21T17:04:22Z {app="lxd", location="none", type="logging"} level="info" Update network address
2023-09-21T17:04:22Z {app="lxd", location="none", type="logging"} level="info" context-socket="[::]:443" context-type="REST API TCP socket" Binding socket
2023-09-21T17:04:22Z {app="lxd", location="none", type="lifecycle"} action="config-updated" source="/1.0" requester-address="@" requester-protocol="unix" requester-username="root" config-updated
```

Here again, `lxc monitor` shows those:

```
INFO   [2023-09-21T17:04:22Z] Action: config-updated, Source: /1.0, Requestor: unix/root (@) 
INFO   [2023-09-21T17:04:22Z] Binding socket                                socket="[::]:443" type="REST API TCP socket"
INFO   [2023-09-21T17:04:22Z] Update network address 
```

The `config-updated` event of `type=lifecycle` would probably be better with `type=logging`. This is especially true considering that `lifecycle` events should also include a `name` and `project` which makes no sense for a core config.

**Comment by tomponline** [comment]
Yeah if they are not instance related they should be logging I think.

**Comment by monstermunchkin** [comment]
> Yeah if they are not instance related they should be logging I think.

I strongly disagree. There are plenty of lifecycle events not related to instances: https://github.com/canonical/lxd/tree/main/lxd/lifecycle.

**Comment by tomponline** [comment]
@monstermunchkin mmm, I see your point. But it does seem strange, what in your view is the definition of "lifecycle"? 
Is that a user requested action or instance state change?
What would be the boundary between lifecycle vs logging? 

I feel like we should write down a definition of this to help us in the future.

**Comment by tomponline** [comment]
@monstermunchkin also it looks like theres some inconsistency between `lxc config set loki.labels` and `lxc config set core.https_address`, does former only logs lifecycle and the latter logs a logging and lifecycle event?

**Comment by monstermunchkin** [comment]
> But it does seem strange, what in your view is the definition of "lifecycle"?
>  What would be the boundary between lifecycle vs logging?

I'd say lifecycle events should be generated when things are created, updated, renamed, or deleted. That's what's being done already. Also, this action should be done.

Logging is for everything else, I'd say.

> also it looks like theres some inconsistency between lxc config set loki.labels and lxc config set core.https_address, does former only logs lifecycle and the latter logs a logging and lifecycle event?

Here I don't see any inconsistency. `Binding socket` or `Update network address` are no lifecycle events.

**Comment by tomponline** [comment]
@simondeziel are you happy to close this?

**Comment by simondeziel** [comment]
I was mistakenly thinking that `lifecycle` events were only for instances but @monstermunchkin corrected me so yeah, this can be close as is.

With @monstermunchkin we also discussed a number of changes that should make all `lifecycle` events (not just those instance-related) more useful in the future. Jira/GitHub ticket forthcoming.

**Comment by tomponline** [comment]
Github please
