### ISSUE TITLE
Installing a VPN app breaks LXD - re-opening

### ISSUE THREAD

**Issue by just-doks** [canonical/lxd#12309]
# Issue description

Previous issue - https://github.com/canonical/lxd/issues/12306

The steps described in the linuxcontainers forum thread - [link](https://discuss.linuxcontainers.org/t/help-help-help-cgroup2-related-issue-on-ubuntu-jammy-with-mullvad-and-privateinternetaccess-vpn/14705/18) - did not help with the iVPN client.

Running command `sudo umount /sys/fs/cgroup/net_cls` doesn't break vpn connection, but who knows what it breaks and the effect resets after reboot. So it's a quick one-time method but not a solution.

Also, stopping VPN client's systemd service helps, but it breaks the client itself and resets after reboot.
Disabling service helps even after reboot, but it still breaks VPN client.
Deleting service is a terrible idea as reinstalling vpn app doesn't return it.

I believe, you can change something in LXD code to avoid this issue for all VPN clients.
Or at least come up with a more universal solution that will persist after a reboot and will not break the VPN application.

**Comment by tomponline** [comment]
Hi @just-doks it looks like this vpn client software is incorrectly setting up the net_CLS (which is from cgroupv1) into a cgroupv2 tree (which is what your operating system uses), which is invalid for lxc (what lxd uses for containers).

See https://github.com/mullvad/mullvadvpn-app/issues/3651 for more info.

This would be best reported on the VPN clients support site so they can avoid this issue or improve docs on how to work around this issue in a pure cgroupv2 environment.

Also we generally prefer support posts to go to the forum so we can triage them and decide whether they are a code issue or not.

https://discourse.ubuntu.com/c/lxd/support/149

Closing this as not something lxd is in a position to change.
