### ISSUE TITLE
docs: Main API specification (Swagger) is not loading

### ISSUE THREAD

**Issue by nbejansen** [canonical/lxd#12318]
The Swagger API specification is not loading on the page. 

Browsers tested:
* Edge
* Chrome
* Brave

---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/api/*

**Comment by tomponline** [comment]
@ru-fu please can you take a look at this?

**Comment by tomponline** [comment]
@nbejansen if its of any use, the yaml file for the API is here:

https://github.com/canonical/lxd/blob/main/doc/rest-api.yaml
