### ISSUE TITLE
slow lxc list

### ISSUE THREAD

**Issue by knutov** [canonical/lxd#12315]
Ubuntu 20.04 and 22.04

5.15 or 6.2 HWE kernels

`lxc list` became extremely slow with lxd 5.17.

With 5.15 and before it was instant. With 5.17 it is usually slow:

```
time lxc list
...
real    0m4.167s
user    0m0.034s
sys     0m0.311s
```

3-5 containers per server. Modern cpu (E3 v3, E3 v6, E-2288G, etc), the same problem. Cluster is not used, but few servers are linked each other via `lxc remote add` for containers migration.

What additional info is needed to debug this situation?

**Comment by tomponline** [comment]
Which storage pool type are you using?

**Comment by knutov** [comment]
zfs 2.1.6, 2.1.9, 2.1.12 on server grade ssd and nvme disks.

**Comment by tomponline** [comment]
Is `lxc ls --fast` quicker?

**Comment by tomponline** [comment]
Also is `lxc info <instance>` for all/specific instances?

**Comment by tomponline** [comment]
Is `lxc ls` still slow if the containers are stopped?

**Comment by tomponline** [comment]
Can you also refresh to LXD 5.18 using:

```
sudo snap refresh lxd --cohort="+"
```

And check if its still an issue on LXD 5.18.

**Comment by knutov** [comment]
Every second `time lxc list --fast` is slow:

```
real    0m0.070s
user    0m0.034s
sys     0m0.027s


real    0m1.564s
user    0m0.008s
sys     0m0.732s


real    0m0.142s
user    0m0.027s
sys     0m0.073s


real    0m1.779s
user    0m0.032s
sys     0m0.901s


real    0m0.529s
user    0m0.013s
sys     0m0.331s


real    0m1.325s
user    0m0.060s
sys     0m0.612s
```

Can not stop containers to test speed with all stopped.

What exactly in `lxc info ` is needed? I see nothing special here, example output is 

```
Name: c11
Status: RUNNING
Type: container
Architecture: x86_64
PID: 10507
Created: 2023/08/27 17:49 MSK
Last Used: 2023/09/03 02:34 MSK

Resources:
  Processes: 178
  Disk usage:
    root: 63.38GiB
  CPU usage:
    CPU usage (in seconds): 58337
  Memory usage:
    Memory (current): 1.09GiB
    Memory (peak): 1.37GiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
...

I use routed network for all containers.

```
# snap refresh lxd --cohort="+"
error: cannot refresh "lxd": snap "lxd" has running apps (lxc), pids: 4159450
# snap refresh lxd
snap "lxd" has no updates available
```

I'm on latest/stable channel

**Comment by tomponline** [comment]
what does `snap info lxd` show?

**Comment by tomponline** [comment]
I meant was `lxc info <instance>` also being slow to return intermittently?

**Comment by knutov** [comment]
`snap info lxd`:

```
...
tracking:     latest/stable
refresh-date: 28 days ago, at 19:47 MSK
channels:
  latest/stable:    5.17-e5ead86  2023-08-30 (25505) 184MB -
  latest/candidate: 5.18-762f582  2023-09-22 (25748) 189MB -
...
```

`time lxc info ...` varies: from 0.5s but usually slow too - 2.5..3.5 seconds

**Comment by tomponline** [comment]
OK, can you try refreshing to `snap refresh lxd --channel=latest/candidate` (and then you will be able to switch back to latest/stable as LXD 5.18 is being rolled out and they are equivalent currently).

**Comment by mihalicyn** [comment]
@knutov you can collect very useful data from `sudo strace -t -T -s 1000 -e 'trace=!nanosleep,clock_gettime' -f -p $(pidof lxd) -o lxd.strace.log`. Then check `lxd.strace.log` and find which syscalls are taking a lot of time when you do `lxc list`.

Warning (if you care about that). If you decide to post `lxd.strace.log` there be careful as this output can contain sensitive information about your system like IP addresses, MAC addresses, etc.

If you find a "hot spot" in the strace output where a lot of time was wasted you can post only this part.

**Comment by knutov** [comment]
`lxc list` is now fast mostly any run with 

```
latest/stable:    5.18-762f582  2023-09-27 (25748)
```

But some times it is still slow like 0.250s vs 0.115s, or 1.5s on first launch in a while.

Even with `--fast` it tooks 3.5s in rare cases.

ps: I see nothing odd and nothing specific slow in strace log. Is there some tool to find interesting parts from this output?

**Comment by simondeziel** [comment]
I wonder if the situation persisted with releases after 5.18? Maybe it's time to close this one?

**Comment by tomponline** [comment]
Lets close for now, but will reopen if @knutov is still experiencing issues.

**Comment by knutov** [comment]
```
for i in `seq 10`; do time lxc list --fast 2>&1 |grep -E 'real|user|sys'; done

real    0m0.114s
user    0m0.030s
sys     0m0.057s

real    0m0.134s
user    0m0.043s
sys     0m0.040s

real    0m0.127s
user    0m0.043s
sys     0m0.054s

real    0m0.108s
user    0m0.041s
sys     0m0.038s

real    0m0.110s
user    0m0.047s
sys     0m0.032s

real    0m0.109s
user    0m0.042s
sys     0m0.039s

real    0m0.140s
user    0m0.032s
sys     0m0.051s

real    0m0.095s
user    0m0.060s
sys     0m0.021s

real    0m0.122s
user    0m0.032s
sys     0m0.046s

real    0m0.110s
user    0m0.032s
sys     0m0.041s
```

Delta time spreading looks large to me, but it is not large to be a problem.

```
tracking:     latest/stable
refresh-date: 48 days ago, at 08:38 MSK

6.2.0-39-generic #40~22.04.1-Ubuntu

# zfs version
zfs-2.2.2-5lowjoel1~ubuntu22.04.1
zfs-kmod-2.2.2-5lowjoel1~ubuntu22.04.1
```
