### ISSUE TITLE
Bundle LXD UI in LXD 5.0 LTS snap

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12339]

**Comment by gibmat** [comment]
To clarify, is this bundling lxd-ui in the snap, or in the source release?

**Comment by tomponline** [comment]
In the snap. I'll change the tittle to be clearer. Thanks

**Comment by tomponline** [comment]
https://github.com/canonical/lxd-pkg-snap/commit/805486c87dc7d4dacef300b6f47e6ac6d4a8592a
