### ISSUE TITLE
Prometheus `/metrics` endpoint changes

### ISSUE THREAD

**Issue by MrDaGree** [canonical/lxd#12333]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 5.0
   * LXD version: 5.0
   * Storage backend in use: ZFS

# Issue description

I have a Grafana dashboard setup using Prometheus to scrape data from the `/metrics` endpoints of my LXD servers. It has come to my realization that there are "gaps" in the data on the dashboard as well as no metric for number of instances on a given host. The hosts that have the gaps are ones that run my CI for home ansible so they are not persistent containers with something always running.

![image](https://github.com/canonical/lxd/assets/5050898/ccaf6367-5448-4f88-a87a-8d287b4dfa46)

1. It would be ideal if there could be data as part of the metrics scrape so then I do not need to do `count by() (count_over_time(lxd_procs_total{job="$job"}[$__interval]))` to get the total of instances on a host.
2. It would also be nice that if there is *no* data to display for things like CPU, Memory, network traffic, etc it is a `0` value instead of `no data` to avoid weird gross gaps on a server's lxd dashboard.

**Comment by tomponline** [comment]
@simondeziel I'd be interested in your thoughts on this one?

**Comment by simondeziel** [comment]
> It would be ideal if there could be data as part of the metrics scrape so then I do not need to do `count by() (count_over_time(lxd_procs_total{job="$job"}[$__interval]))` to get the total of instances on a host.

Reporting how many instances are on a given host is something we would like to have in the future. We currently only expose a few LXD (as opposed to instances' metrics) metrics:

```
$ lxc query /1.0/metrics | grep ^lxd_ | grep -vF lxd_go_
lxd_operations_total 0
lxd_warnings_total 1
lxd_uptime_seconds 10883.400932528
```
If I understand your request, you'd also want those metrics to be exposed:

```
lxd_instances_total 32
lxd_containers_total 17
lxd_vms_total 15
```

I also think we should add `lxd_version` to the mix while at it. If you have other metrics for the LXD daemon itself, please share them!

**Comment by simondeziel** [comment]
>     2. It would also be nice that if there is _no_ data to display for things like CPU, Memory, network traffic, etc it is a `0` value instead of `no data` to avoid weird gross gaps on a server's lxd dashboard.

Currently, instances metrics are reported only when the instances are running. Are you proposing that for stopped instances, we keep reporting the labels but with all `0`s? And when a given instance is deleted, LXD would stop reporting about it?

**Comment by MrDaGree** [comment]
> I also think we should add lxd_version to the mix while at it. If you have other metrics for the LXD daemon itself, please share them!
 
 I agree that would be pretty nice to have as well
 
 > Currently, instances metrics are reported only when the instances are running. Are you proposing that for stopped instances, we keep reporting the labels but with all 0s? And when a given instance is deleted, LXD would stop reporting about it?
 
 Ideally if at least stopped instances reported enough for the dropdown part in the example dashboard (`	label_values(lxd_procs_total{job="$job",project="$project"}, name)`) to say its status is `STOPPED` or something would be nice. Everything else wouldn't technically need to have 0's to save on processing as after I submitted this I noticed you can set a "No value" number
 
 
![image](https://github.com/canonical/lxd/assets/5050898/31b35e36-f0be-4104-83db-43a912182141)

**Comment by simondeziel** [comment]
@tomponline, I'm curious to hear your thoughts on reporting metrics for `STOPPED` instances?

**Comment by tomponline** [comment]
It would seem to make sense to include an entry for each stopped instance with minimal metrics that are available to the instance in that state. Along with an indication of its state.

**Comment by simondeziel** [comment]
I think that stopped entries should have the same `key=value` labels as reducing the number of labels, would increase the number of time series needed to store them. https://prometheus.io/docs/practices/naming/#labels:

> every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

So with that in mind how about we turn the current metric:

```
lxd_cpu_seconds_total{cpu="0", instance="foo:9101", job="lxd-foo", mode="system", name="apt", project="default", type="container"}  20.576714
```

Into:

```
# if running:
lxd_cpu_seconds_total{cpu="0", instance="foo:9101", job="lxd-foo", mode="system", name="apt", project="default", type="container", state="RUNNING"}  20.576714
# if stopped:
lxd_cpu_seconds_total{cpu="0", instance="foo:9101", job="lxd-foo", mode="system", name="apt", project="default", type="container", state="STOPPED"}  0
```

**Comment by monstermunchkin** [comment]
> I also think we should add `lxd_version` to the mix while at it.

@simondeziel We could add `lxd_info{version="5.19"} 1` as shown in the [OpenMetrics specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#info-1).

**Comment by monstermunchkin** [comment]
> lxd_instances_total 32
lxd_containers_total 17
lxd_vms_total 15

For this I'd suggest adding the `project` label so that unauthorized users cannot see the total count of every project.

```
lxd_instances{project="default"} 10
lxd_containers{project="default"} 7
lxd_vms{project="default"} 3
lxd_instances{project="foo"} 5
lxd_containers{project="foo"} 4
lxd_vms{project="foo"} 1
```

**Comment by monstermunchkin** [comment]
> For this I'd suggest adding the `project` label so that unauthorized users cannot see the total count of every project.
> 
> ```
> lxd_instances{project="default"} 10
> lxd_containers{project="default"} 7
> lxd_vms{project="default"} 3
> lxd_instances{project="foo"} 5
> lxd_containers{project="foo"} 4
> lxd_vms{project="foo"} 1
> ```

I'm not sure we need `lxd_instances` if we have the other two values since the number of instances can be calculated using those two values.
