### ISSUE TITLE
Fails to rename custom storage volume

### ISSUE THREAD

**Issue by roosterfish** [canonical/lxd#12344]
# Required information

* LXD version: `latest/edge`
* Storage backend in use: All backends seem to be affected

# Issue description

When renaming a custom storage volume with `lxc storage volume mv pool/vol1 pool/vol2` instead of `lxc storage volume rename pool vol1 vol2`, the client expects an operation to be returned. The command fails with `Error: not found`, however the actual volume gets renamed.

Renaming a volume returns a sync response which seems to be the root cause.

# Steps to reproduce

 1. `lxc storage volume create pool vol1`
 2. `lxc storage volume mv pool/vol1 pool/vol2 --debug` -> "Error: not found" when trying to GET the operation.

**Comment by tomponline** [comment]
@roosterfish @monstermunchkin we have "storage volume rename" tests, so I am surprised this is affecting all storage drivers as the tests are passing.

So it seems likely there is some other aspect at play here...

**Comment by tomponline** [comment]
@roosterfish ah I see now you're invoking the rename command with `pool/` for both volumes, perhaps thats the specific difference. Thanks

**Comment by monstermunchkin** [comment]
When LXD detects a rename request, it returns a `SyncResponse`. If it detects a move request, an `OperationResponse` is returned. `lxc storage volume move` internally calls `lxc storage volume copy` which expects an operation to be returned. That's what's causing the failure.

My proposed fix would be to have `lxc storage volume move` detect a rename request (equal source and target pool), and then call `lxc storage volume rename` internally instead.

**Comment by tomponline** [comment]
Sounds reasonable to me, thanks!
