### ISSUE TITLE
nftables port ranges with network forward 

### ISSUE THREAD

**Issue by pmarini** [canonical/lxd#12356]
When creating a network forward rule with a range of ports, LXD generates one nftables rule per port.

However nftables rules support defining one-liner ranges:

```
ip daddr XXX.XXX.XXX.XXX udp dport 1000-2000 dnat ip to 10.0.0.20:1000-2000 
```
It would be great if network forwards could generate rules with ranges.

My use case is hosting a WebRTC Gateway in a  LXD container and it typically requires very large UDP port ranges (20000 ports= to be forwarded.

**Comment by tomponline** [comment]
What LXD version?

**Comment by pmarini** [comment]
I'm on lxd 5.15

**Comment by tomponline** [comment]
Please check if behaviour is seen on supported version (LXD 5.18) and advise.
I seem to recall this was fixed already.
https://github.com/canonical/lxd/pull/11983

If you still experience the issue let me know and we'll reopen.

**Comment by pmarini** [comment]
Yes, confirmed it works as expected in 5.18. Thanks!
