### ISSUE TITLE
create network forward  

### ISSUE THREAD

**Issue by abdodz1234** [canonical/lxd#12368]
# Required information

 * Distribution: ArchLinux
   * Kernel version: 6.5.6-arch2-1
   * LXC version: 5.17
   * LXD version: 5.17
   * Storage backend in use: btrfs

# Issue description

i can't create network forward when  profile gui  attached to container

 1. create profile 
 2. attach profile  to container 
 3.  lxc network forward create lxdbr0  192.168.8.10
lxc command above show   error 
❯ lxc network forward create lxdbr0 192.168.8.10
Error: Failed creating forward: invalid CIDR address: /mnt/X0/32
abdo@ArchLinux ~ [1]
❯ lxc network forward create lxdbr0 192.168.8.10
Error: Failed creating forward: invalid CIDR address: /mnt/wayland-0/32
abdo@ArchLinux ~ [1]
❯ lxc network forward create lxdbr0 192.168.8.10
Error: Failed creating forward: invalid CIDR address: /mnt/X0/32
abdo@ArchLinux ~ [1]

# Information to attach

 lxc profile show gui
config: {}
description: ""
devices:
  PulseSocket1:
    bind: container
    connect: unix:/run/user/1000/pulse/native
    gid: "1000"
    listen: unix:/mnt/pulse-socket
    mode: "0777"
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
    uid: "1000"
  Waylandsocket:
    bind: container
    connect: unix:/run/user/1000/wayland-0
    gid: "1000"
    listen: unix:/mnt/wayland-0
    mode: "0777"
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
    uid: "1000"
  X0:
    bind: container
    connect: unix:/tmp/.X11-unix/X0
    gid: "1000"
    listen: unix:/mnt/X0
    mode: "0777"
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
    uid: "1000"
  mygpu:
    gid: "1000"
    type: gpu
    uid: "1000"
name: gui
used_by:
- /1.0/instances/vscode

❯ lxc config show vscode
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Archlinux current amd64 (20230924_04:18)
  image.os: Archlinux
  image.release: current
  image.requirements.secureboot: "false"
  image.serial: "20230924_04:18"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 304a1881f97e30192d7941c86117bed2eb0ef3a4b5b647c7742dd1ab78de809a
  volatile.cloud-init.instance-id: 7fd26ef6-7bfe-447a-8ce2-9b4ea0779295
  volatile.eth0.hwaddr: 00:16:3e:98:5e:1b
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.uuid: 4a123f78-889e-4c5e-96da-ce12270c8312
  volatile.uuid.generation: 4a123f78-889e-4c5e-96da-ce12270c8312
devices:
  rustc:
    path: /home/a1/.rustup
    readonly: "true"
    source: /opt/rust/.rustup/
    type: disk
ephemeral: false
profiles:
- default
- gui
stateful: false
description: ""

**Comment by tomponline** [comment]
@MusicDin can you see if you can reproduce this please?

Thanks
