### ISSUE TITLE
"Permission denied:" messages are generated on Ubuntu 23.10 console after editing any kind of LXC config (instance, profile, project)

### ISSUE THREAD

**Issue by tregubovav-dev** [canonical/lxd#12388]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 23.10 server on Raspberry Pi 4B
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux picl-01 6.5.0-1005-raspi # 7-Ubuntu SMP PREEMPT_DYNAMIC Sun Oct  8 08:06:18 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
   * LXC version: 5.18
   * LXD version: 5.18
   * Storage backend in use: ceph (microceph)

# Issue description

Following messages are generated on console when regular user included in **lxc** linux group edits any kind of LXC profile (instance, profile, project):
_grep: /proc/sys/kernel/apparmor_restrict_unprivileged_userns: Permission denied
grep: /proc/sys/kernel/apparmor_restrict_unprivileged_unconfined: Permission denied_

These messages are not generated when the same profiles are edited by **root** user.
This issue looks cosmetic and I do not see any impact on LXD cluster behavior.

P.S.
This message does not exists on Ubuntu 22.04.3 (LTS) and LXD 5.17 (Raspberry Pi).

P.P.S
Comparing to Ubuntu 22.04.3,  Ubuntu 23.10 introduced 5 new apparmor related entities in **/proc/sys/kernel/**: apparmor_restrict_unprivileged_unconfined, apparmor_restrict_unprivileged_userns_complain, apparmor_restrict_unprivileged_io_uring, apparmor_restrict_unprivileged_userns, apparmor_restrict_unprivileged_userns_force

# Steps to reproduce

 1. Log-in to linux console as user belonging in lxd group
 2. Start editing default profile: _lxc profile edit default_
 4. Save profile without changing anything

 ## Expected result:
 Config should be saved without any warnings

## Actual result
 Messages below displayed on the console after saving profile
_grep: /proc/sys/kernel/apparmor_restrict_unprivileged_userns: Permission denied
grep: /proc/sys/kernel/apparmor_restrict_unprivileged_unconfined: Permission denied_

The same issue exists when project, instance or system config is being edited.

# Information to attach

There are no relevant messages in any logs that appear.

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
This is worked around by https://github.com/canonical/lxd-pkg-snap/pull/183 which will be in LXD 5.19.

Furthermore we understand from @jrjohansen that there will be a fix to the kernel in Mantic soon.
