### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by wyz2019** [canonical/lxd#12397]
在 LXD 的Debain容器里 可以安装docker，但是无法运行，提示如下错误
Docker can be installed in the Debain container of LXD, but it cannot run with the following error prompt

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by mihalicyn** [comment]
@wyz2019 try `lxc config set container-name security.nesting=true`

**Comment by tomponline** [comment]
Support questions are better posted over at https://discourse.ubuntu.com/c/lxd/support/149 as well
