### ISSUE TITLE
File mount missing "--connect" in help

### ISSUE THREAD

**Issue by turtle0x1** [canonical/lxd#12391]
If i run `lxc file mount c1/blah blah/` then I get  `...For use as a regular user, please use the --connect option instead.`

If you run `lxc file mount --help` it doesn't appear documented. Can this be included in help or removed from the error?

**Comment by tomponline** [comment]
What lxd version, host is version?

**Comment by turtle0x1** [comment]
lxd 5.18, its a doc string thing

**Comment by tomponline** [comment]
I think this error is coming from sshfs potentially.

**Comment by MusicDin** [comment]
Yes, this is not an error from LXD.

**Comment by MusicDin** [comment]
@tomponline Should we prevent running "lxc file mount" if not run as root (before the SSHFS is actually run)?

**Comment by tomponline** [comment]
@MusicDin I tracked down the error message to here:

https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft/wrappers/sshfs#L1-L8

So we just need to change that to suggest using the actual flag in `lxc mount` which is `--listen` rather than `--connect`.
