### ISSUE TITLE
Remove deprecated limits.network.priority setting

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12419]
This setting was deprecated in LXD 5.19 in place of per-NIC limits.priority setting that is compatible with cgroupv1 and cgroupv2.

**Comment by anirbandey1** [comment]
Will removing the related code from 
- `lxd/metadata/configuration.json`
- `lxd/devices.go`
- `lxd/instance/drivers/driver_lxd.go`
- `shared/instance.go`
- `scripts/bash/lxd-client`
- `doc/api-extensions.md`
- `doc/config_options.txt` 
work?

**Comment by tomponline** [comment]
@soufrabi yep that seems like a good place to start.

**Comment by tomponline** [comment]
@MusicDin this is another one I'd like us to complete before the LXD 5.21 LTS release please
