### ISSUE TITLE
5.19 Failed updating volume on cluster

### ISSUE THREAD

**Issue by chribro88** [canonical/lxd#12425]
# Required information

 * Distribution: Ubuntu 22.04.3 LTS
   * Kernel version: 6.2.0-33-generic (amd64), 6.2.0-32-generic (amd64), 5.15.0-1041-raspi (arm64)
   * LXC version:
   * LXD version: 5.19
   * Storage backend in use: ZFS

# Issue description

Recent automatic update to 5.19 appears to have brought down cluster.

Main issue seems to be around the following error:
```
INFO   [2023-10-20T01:15:51Z] Applying patch                                name=storage_zfs_unset_invalid_block_settings_v2
ERROR  [2023-10-20T01:15:51Z] Failed to start the daemon                    err="Failed applying patch \"storage_zfs_unset_invalid_block_settings_v2\": Failed updating volume \"sales-volume\" in project \"carcatcher-dev\" on pool \"magna\": Storage volume not found"
```
This particular storage volume is only on three members. `zfs list` shows dataset exists on each. Although did also see same error for a volume on the local pool.

Before identifying above, had attempted to recover quorum as logs referenced "reported leader server is not the leader" and thought issue mightve been caused by a particular node - followed: 
[https://documentation.ubuntu.com/lxd/en/stable-5.0/howto/cluster_recover/](https://documentation.ubuntu.com/lxd/en/stable-5.0/howto/cluster_recover/)

Have also attempted to revert snap to 5.18, however downgrades don't appear to be permitted with following error:
```
Error: Failed to initialize global database: failed to ensure schema: this node's version is behind, please upgrade
```

I take it there's no way to downgrade. Is my best bet to create these missing datasets on each member and manually add the database?

**Comment by tomponline** [comment]
This should be fixed by https://github.com/canonical/lxd/pull/12421

I am pushing this to latest/candidate now.
