### ISSUE TITLE
Installing LXD breaks "hostname -A"

### ISSUE THREAD

**Issue by jw-rav** [canonical/lxd#12445]
* Distribution: ubuntu-22.04
 * The output of "lxc info": [lxc.txt](https://github.com/canonical/lxd/files/13078724/lxc.txt)

# Issue description

LXD creates a network interface lxdbr0 with one ipv4 and one ipv6 address like this:

4: lxdbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:79:34:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.166.0.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fd42:b992:ae76:9163::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe79:34a6/64 scope link 
       valid_lft forever preferred_lft forever

Those addresses show up in "hostname --all-ip-interfaces" in addition to the original ip address:

  192.168.1.178 10.166.0.1 fd42:b992:ae76:9163::1 

But those addresses have no corresponding reverse lookups:

$ dig -x 10.166.0.1
[ ... ]
1.0.166.10.in-addr.arpa. 0      IN      PTR     h730.
1.0.166.10.in-addr.arpa. 0      IN      PTR     h730.local.
[ ... ]
$ dig -x fd42:b992:ae76:9163::1
[ ... ]
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.6.1.9.6.7.e.a.2.9.9.b.2.4.d.f.ip6.arpa. 0 IN PTR h730.
1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.6.1.9.6.7.e.a.2.9.9.b.2.4.d.f.ip6.arpa. 0 IN PTR h730.local.
[ ... ]

Thus, "hostname -A" reports bogus FQDNs:

$ hostname -A
h730.real.do.main h730 h730

**Comment by simondeziel** [comment]
Do you get the expected PTR if you use `dig -x 10.166.0.1 @10.166.0.1`?

**Comment by jw-rav** [comment]
$ dig -x 10.166.0.1 @10.166.0.1
1.0.166.10.in-addr.arpa. 0      IN      PTR     _gateway.lxd.

I am not sure which PTR is expected form this command.

As far as I understand, FQDNs are about how the outside world sees the given host. As long as virtual environments are not visible/reachable from the outside, they should not affect FQDN/domainname information.

But maybe I have a mis-conception in this regard?

**Comment by simondeziel** [comment]
The thing is that LXD creates a fake TLD (`.lxd` for the usual `lxdbr0`) and that fake TLD is only resolvable by LXD itself. If you want forward and reverse DNS resolution for it, you need to tell your DNS stack about it. Here's how to do it if you use systemd-resolved: https://documentation.ubuntu.com/lxd/en/latest/howto/network_bridge_resolved/

**Comment by jw-rav** [comment]
I do NOT want any DNS resolution for this LXD thing.

In contrast, I expect LXD not to mess up my host settings.

The settings should be left as if LXD was not installed at all.

**Comment by tomponline** [comment]
LXD doesn't alter host DNS settings.
However it must create a network bridge with IPs in order for instances to have network connectivity.

**Comment by jw-rav** [comment]
While LXD doesn't alter DNS, the created bridge confuses and breaks /bin/hostname (which is a standard-utility for decades).

Do you think braking standard utilities is a good habit? Should I expect that /bin/sh is broken at one of the next releases?

Maybe lxd-developers should have coordinated with hostname developers about how to avoid to confuse/break /bin/hostname?

**Comment by tomponline** [comment]
I just tried this on my Ubuntu 22.04 machine with a lxdbr0 IP address of 10.21.203.1

The `hostname --all-ip-interfaces` flag doesn't exist there, but I think `--all-ip-addresses` is equivalent:

```
hostname --all-ip-addresses
192.168.1.115 192.168.1.112 10.21.203.1
```

Then when I do `hostname -A` I see:

```
hostname -A
user-ThinkPad-X1-Carbon-7th user-ThinkPad-X1-Carbon-7th user-ThinkPad-X1-Carbon-7th
```

So that looks OK to me. Perhaps because systemd-resolved is detecting this is a local IP and resolving it correctly.

I'm not sure where the domain "h730.local" is coming from, perhaps its coming from your router or ISP?

When I do `dig -x 10.21.203.1` I get `NXDOMAIN` as I would expect:

```
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 14749
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```

I'm not sure there's much that LXD can do about this I'm afraid. I suspect this is down to local environmental settings causing unexpected responses to PTR lookups.

**Comment by tomponline** [comment]
`Note  that  different addresses may resolve to the same  name, therefore the output may contain duplicate entries.`

As for the domain parts my system doesn't have a domain set, so its just the hostname.

I'm going to close this one down for now as there's no clear issue with LXD's network setup.

But if you want to discuss further you with regard to your system setup we can discuss over on the support forum:

https://discourse.ubuntu.com/c/lxd/support/149

**Comment by jw-rav** [comment]
> As for the domain parts my system doesn't have a domain set, so its just the hostname.

So you verify the behaviour of "hostname --all-fqdns" with a setup that don't have a domain set at all? And you tell me that the problem is on MY side?
