### ISSUE TITLE
Pushing files to a stopped container with raw.idmap set does not work

### ISSUE THREAD

**Issue by morphis** [canonical/lxd#12507]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: `6.2.0-36-generic #37~22.04.1-Ubuntu`
   * LXC version: 5.0.3
   * LXD version: 5.0.2
   * Storage backend in use: zfs

# Issue description

When trying to push a file to a stopped unprivileged container which has an additional idmapping set via `raw.idmap` the call to `lxc file push fails`:

`Error: Failed to run forkfile: fork/exec /snap/lxd/current/bin/lxd: invalid argument:`

# Steps to reproduce

First we start a container with no `raw.idmap` set:

```
$ lxc launch ubuntu:j c0
$ lxc stop c0
$ touch foo
$ lxc file push foo c0/root/
```

This works without prolems as expected. Next trying the same with an `raw.idmap` set causes the described problem:

```
$ lxc launch ubuntu:j c1 -c raw.idmap="both 1000 1000"
$ lxc stop c1
$ lxc file push foo c1/root/
Error: Failed to run forkfile: fork/exec /snap/lxd/current/bin/lxd: invalid argument:
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
@morphis to confirm this is an issue in 5.0/stable and not a regression in 5.0/edge? Thanks

**Comment by tomponline** [comment]
And do you see the issue on latest/stable?

**Comment by morphis** [comment]
@tomponline yes, this is with 5.0.2 from 5.0/stable. Can be reproduced on latest/stable (5.19-31ff7b6, rev 26093) as well.

**Comment by tomponline** [comment]
Want to take this one @mihalicyn ?

**Comment by morphis** [comment]
@mihalicyn hey! Any idea what is wrong here?

**Comment by tomponline** [comment]
@morphis Hi, we discussed this this morning in our catch up and @mihalicyn is going to look into this this week.

**Comment by morphis** [comment]
Thanks @tomponline !

**Comment by mihalicyn** [comment]
I have tried to reproduce this with `latest/edge` and `latest/stable` (5.19) and it just works fine.
The only difference is that I'm using "dir" backend (with ext4 filesystem behind), while in your case it's ZFS.

**Comment by mihalicyn** [comment]
Maybe @tomponline will give a bit of extra context on that. I find this behavior a bit suspicious (or I just don't know the story behind it).

**Comment by tomponline** [comment]
Try on ubuntu 23.10

**Comment by tomponline** [comment]
I wonder if it works on LXD 5.0.2 with shiftfs enabled.
