### ISSUE TITLE
OIDC implementation discussion

### ISSUE THREAD

**Issue by nsklikas** [canonical/lxd#12531]
# Issue description

I looked into the oidc implementation and I have a couple of comments/questions. I didn't run the UI and I am not 100% clear on your use-cases, so I may be missing something:
- The oidc handler uses the zitadel library with encrypted cookies, but the cookies don't have `Secure` set (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L269). AFAICT lxd will always use https, so I don't see a reason that `Secure` is not set.
- LXD requires that the tokens it accepts have a configurable audience (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L238). This makes sense in cases where the token is issued for another client and it is used to authenticate with the LXD API (CLI authentication), but it does not make sense for the case of UI authentication because in that case the tokens should always have the LXD client_id as an audience (see https://openid.net/specs/openid-connect-core-1_0.html#IDToken, `aud` claim) as they were issued for that client.
- LXD requests for the `aud` claim in the authorization request (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L148). Even though it is common practice to request for an audience this way, it is not described in the auth2/oidc standard so it will not work for _any_ provider (but it will probably work for the major ones).
- The `email` scope is not requested (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L276), even though the `email` claim is expected by the backend (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L133)
- After the oidc flow has finished, the `access_token` and the `refresh_token` are stored unencrypted in session cookies (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L187). These cookies have `HttpOnly` set to `False`, I am not sure why that is needed. IMHO This is not secure as an attacker can gain those tokens through MITM attacks, by sending the refresh token through the cookies an attacker can gain long lasting access to user resources. Also perhaps I am missing something, but storing refresh tokens in session cookies beats the purpose (refresh tokens are long lived, session cookies are short lived).

Thoughts/Suggestions:
- The `aud` checking logic in https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L238 should be: `if !(o.audience in audience or o.client_id in audience) return error` (or you maybe can require that the audience must include the `client_id`, if you expect that you will always have one).
- The audience parameter in the authorization request is not needed, unless you plan to use the access_tokens to access other resources.
- The `email` scope should be requested.
- If you wish to store tokens in the cookies, they should be encrypted. (I am not a security person, but intuitively this makes sense to me)
- Semantically speaking, I am not sure if you should use the access token or ID token for managing the browser session. Access tokens are used for authorization, ID tokens are used for identification. In the case of CLI, access tokens make sense as you are checking if the client is authorized to access the server (through the audience). In the case of UI, you are only using the token to get the user's claims (identify the user). Authorization is always offloaded to another system (openfga or internal server logic). Also access tokens are not always JWTs.

cc @massigori @markylaing

**Comment by massigori** [comment]
Adding @edlerd for awareness too

**Comment by tomponline** [comment]
> I think that is may be due to how the LXD UI works (@edlerd @tomponline please correct me if I'm wrong). The LXD UI is bundled with the LXD snap as a set of static files. If you're running a local standalone LXD, you can access the UI without trusting the LXD server certificate in the browser. This is "insecure" from the perspective of the browser, but isn't actually insecure because it's all running on localhost. However, this is a problem if you're connecting to the LXD UI remotely. I'm not sure would be best here. Ideally when using the UI everything will be https, even on localhost.

As we always use HTTPS I dont see any problem with setting Secure if that helps.

**Comment by nsklikas** [comment]
> Where would you suggest we store the tokens instead? If I understand correctly, the access token is not needed for login via the UI, so I'll attempt to remove it from the callback as I understand that is only used in the Authorization Code flow and not the Device Authorization Grant.

That's a good question. After the OIDC flow is finished, LXD has the user's ID token (which contains the user's information), the access token (which LXD can use on behalf of the user to make calls to third party services, I don't think you need this) and the refresh token (which LXD can use to refresh the user's session and fetch the user attributes again). It is quite common to create a user, create a session for the user and then return that session to the UI via cookies. Where and whether you need to store the tokens depends on how you want the LXD session to behave. How long do you want the sessions to be? Do you create users in the backend? Do you want to allow the user session to be refreshed? 

If you don't want to implement your own sessions you could do something like what you are doing, but I would suggest you to use the ID token instead of the access token (unless you wish to make a call every time to the userinfo endpoint), enable HTTPOnly in the cookies and to consider encrypting the cookies (not 100% what are the best security practices here). Of course, with this approach you rely on the IdP's session and I would think that it makes auditing a user's actions a little harder. About the refresh tokens, that again depends on whether you wish to have long lasting sessions (if I understand correctly, currently you don't have long lasting sessions).

I can't really point you to an implementation as that is application specific.

**Comment by shipperizer** [comment]
@markylaing on point 1, not sure if this answers it but have a look at here https://auth0.com/blog/id-token-access-token-what-is-the-difference/#What-Is-an-ID-Token-NOT-Suitable-For

**Comment by markylaing** [comment]
> 2\. I'd like to further improve our implementation to ensure that we can ensure ID token claims are always up-to-date. For example, if I change the group memberships of a user, how can we ensure we have the correct groups when we verify the ID token and inspect the claims?

After playing with this a bit, I don't think we'll need to do anything special with caching tokens etc. If an administrator of the IDP assigns a user to a group, their `identity_token` cookie will not contain the group. If the user logs out of LXD (e.g. deletes the cookies) and logs back in, the new identity token will contain the correct groups. Similarly for the CLI, the access token will not contain the correct groups until the token is refreshed, we can force this by deleting the access token and using the refresh token to get a new one.

It's fairly commonplace to require a user to log out and log back in again to get the correct permissions so I don't see this being an issue for UX perspective. However, there would be an problem if an IDP admin accidentally gives the wrong user elevated permissions, in this case the token will not be refreshed until it expires
