### ISSUE TITLE
List all storage volumes via API

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#12550]
# Required information

 * Distribution: Ubuntu snap
 * Distribution version: 5.19

# Issue description

Existing API endpoint to get storage volumes depend on a storage pool via the `/1.0/storage-pools/{poolName}/volumes` endpoint.

We need one endpoint to get the list of storage volumes from all pools. In LXD-UI we display a global storage volume list from all pools. This is currently fetching all pools, then all volumes in each pool, and then merging the lists. Obviously this is rather inefficient and one endpoint to get the full volume list would be preferred. We are only consuming volumes for a one project at a time.

Proposed endpoint: `GET /1.0/storage-volumes?project=foo`, returning a list of all volumes in project foo with an additional `pool` field. Alternatively returning a list with hierarchy like `["pool-a": [...volumesInPoolA], "pool-b": [...volumesInPoolB]]`.

**Comment by tomponline** [comment]
@escabo @masnax ive also asked Pedro to look into this

**Comment by masnax** [comment]
@hamistao So in this case I think you can just return a slice of structs:
```go
[]StorageVolumesAllPools{
  {
    PoolName       string
    Project        string
    StorageVolumes []StorageVolume
  }
}
```

You could also use a `map[poolName][]StorageVolume`, but that would be less flexible in the long run, in case we want to extend the API.

**Comment by masnax** [comment]
In particular, we already have a way to filter storage volumes by pool with the existing endpoint so if we're concerned about lookup efficiency for a particular pool, then we should be using the existing endpoints.

If you want to avoid assembling the merged list on the other end, then you can do something like this: 

```go
type StorageVolumeInPool struct {
  StorageVolume

  PoolName string
}
```

and return a slice of `[]StorageVolumeInPool`.

**Comment by tomponline** [comment]
I think the first approach is the one we should go for.

**Comment by hamistao** [comment]
I think it would also be worth it change the CLI command `lxc storage volume list` that doesn't require the pool name and would use this new endpoint in case no pool is specified. If you agree I can open one issue on this subject and assign to myself.

**Comment by tomponline** [comment]
> I think we should also change the CLI command `lxc storage volume list` so that it doesn't require the pool name and would use this new endpoint in case no pool is specified. I decided to open this issue on the subject to discuss it further #13018.

Lets go for that
