### ISSUE TITLE
LXD snap occasionally freezes on stop

### ISSUE THREAD

**Issue by masnax** [canonical/lxd#12582]
Occasionally, LXD will freeze when stopping via the snap. This happens on both `stable` and `edge`.

This can be replicated with `snap restart lxd` or `systemctl stop snap.lxd.daemon snap.lxd.daemon.unix.socket`

I see `/snap/lxd/current/commands/daemon.stop` in the process list, and killing this process will make LXD continue as normal.

**Comment by masnax** [comment]
I said "continue as normal", but actually LXD is definitely left in a broken state after forcibly killing `daemon.stop`.

**Comment by masnax** [comment]
The setup is a LXD cluster created with MicroCloud (so ceph and ovn are set up as well), and I'm restarting LXD on each system like so:
```
snap disable lxd
systemctl stop snap.lxd.daemon snap.lxd.daemon.unix.socket
snap enable lxd
snap start lxd
```

**Comment by tomponline** [comment]
@masnax are you still experiencing this?

**Comment by masnax** [comment]
I think this was related to MicroCloud restarting LXD while it was shutting down. I'll close for now.
