### ISSUE TITLE
LXD Buckets: Failed creating storage bucket: Failed finding free listen port for bucket MinIO process

### ISSUE THREAD

**Issue by arren-ru** [canonical/lxd#12586]
# Issue description

Tried to create bucket according to [documentation](https://github.com/canonical/lxd/blob/main/doc/howto/storage_buckets.md), but had not success.
I feel lack of details in documentation.

```
❯ lxc storage bucket create zfs test
Error: Failed creating storage bucket: Failed finding free listen port for bucket MinIO process: listen tcp [::1]:0: socket: address family not supported by protocol
```

 * Distribution: Archlinux
 * LXD 5.19
 * Storage ZFS 2.2.2

Bucket address activated via config

```
config:
  core.https_address: :8443
  core.storage_buckets_address: :8555
```

**Comment by roosterfish** [comment]
Hi @arren-ru, thanks for reporting this. The error is most likely caused by your system having the IPv6 stack disabled. We try to bind the local MinIO to `::1 which isn't possible in case you only have IPv4 support. I'll work on a fix.

**Comment by tomponline** [comment]
@roosterfish we should be able to use /proc to detect if ipv6 is enabled and change our internal bind address appropriately.

**Comment by tomponline** [comment]
Does that work on a non-ipv4 system?

**Comment by tomponline** [comment]
If 127.0.0.1 is always available then I dont see an issue using that.

**Comment by arren-ru** [comment]
Sorry for late response, I didn't have opportunity to answer in time.
Yes, I don't use ipv6 stack, only ipv4.
But when I did `ss -tlnp` to see opened ports, I see that serving on 0.0.0.0 as well
```
LISTEN  0  4096  0.0.0.0:8555  0.0.0.0:*  users:(("lxd",pid=450403,fd=26))
```

@roosterfish thanks for working on fix that

**Comment by roosterfish** [comment]
@arren-ru we use a simple trick to discover a free port to use for MinIO. Prior to this fix LXD tried to bind to `[::1]:0` where the `0` indicates that a random free port should be chosen. We then close the socket and use this port for starting MinIO using `minio --address {localhost addr}:{random port}`. Unfortunately you cannot configure the IP to use for discovery.

The `:8555` process you see is LXD proxying requests from this port to the MinIO process which is listening locally for the selected storage pool.

**Comment by roosterfish** [comment]
The fix is already in the `latest/edge` snap channel.

**Comment by arren-ru** [comment]
Does LXD use minio binary from other package or its functionality already builtin?
Unfortunately, I don't use snap, but archlinux packaging system.

**Comment by roosterfish** [comment]
It's included in the snap package https://github.com/canonical/lxd-pkg-snap/blob/latest-edge/snapcraft.yaml#L582
