### ISSUE TITLE
stalled remote client prevents snapshots from taking place

### ISSUE THREAD

**Issue by aivanise** [canonical/lxd#12611]
stalled remote client doing lxc pull (i.e. forking a lxc forkfile process) can block snapshot creation/deletion

see https://discourse.ubuntu.com/t/lxc-snapshot-operations-blocked-by-hanging-forkfile-process/40817 for discussion

how to reproduce:

on the client:
lxc file pull container/some/big/file

forcefully cut the network connection, i.e. pull the network cable, turn off the vpn, firewall off port 8443 etc

lxc snapshot container will hang
lxc rm container/snap0 will also hang

forkfile process spawned off of a lxd will also hang on the server indefinitely

**Comment by gabrielmougard** [comment]
@aivanise I'm able to reproduce the issue. Working on a fix.

**Comment by aivanise** [comment]
Many thanks, its not very common, but it's super annoying when it happens.
