### ISSUE TITLE
`5.0/edge` iso import fails

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12647]
On a `dir` pool:

```
$ tmp_iso_dir="$(mktemp -d)"
$ echo foo > "${tmp_iso_dir}/foo"
$ genisoimage -o vol5.iso "${tmp_iso_dir}"

$ lxc storage volume import vmpool2365 vol5.iso vol5
Importing custom volume: 100% (286.45MB/s)
Error: Unsupported compression
```

Version info:

```
$ uname -a
Linux lxd-ci-storage-volumes-vm-jammy-5-0-edge 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ snap list lxd
Name  Version      Rev    Tracking  Publisher    Notes
lxd   git-ccdba5c  26494  5.0/edge  canonical**  -
```

**Comment by tomponline** [comment]
This will likely be resolved by backporting 

https://github.com/canonical/lxd/pull/12649
https://github.com/canonical/lxd/pull/12616

**Comment by tomponline** [comment]
@simondeziel ah this is because stable-5.0 does not include iso support (as it requires a DB level value change so cannot be backported). As such the error is correct because it was expecting a tarball and got a ISO.

**Comment by simondeziel** [comment]
> @simondeziel ah this is because stable-5.0 does not include iso support (as it requires a DB level value change so cannot be backported). As such the error is correct because it was expecting a tarball and got a ISO.

Excellent, I'll dig up the API extension name and make an exclusion in the test case, thanks!
