### ISSUE TITLE
LXD License change causes any Software dependent on the  included lxd go client to become AGPL from v5.20?

### ISSUE THREAD

**Issue by etherealbacon** [canonical/lxd#12679]
Please forgive the lack of template use. This is purely a licensing question.

The new AGPL licensing by my current understanding prevents any further use of the LXD go client  libraries (from v5.20) from being used in non AGPL licensed software.

Such as:
terraform provider
ansible library
any third party building tools upon lxd go client libs.

Could someone clarify that my understanding is correct?

**Comment by gabriel-samfira** [comment]
I would also be interested in this.

**Comment by tomponline** [comment]
Hi,

There has been an update posted about this here https://discourse.ubuntu.com/t/an-update-on-the-licence-change-and-community-image-server/41549

**Comment by tomponline** [comment]
The Go SDK client is now licensed out as Apache-2.0 

https://github.com/canonical/lxd/pull/12731
