### ISSUE TITLE
Decouple the client as Apache 2.0

### ISSUE THREAD

**Issue by gabriel-samfira** [canonical/lxd#12678]
The switch to AGPLv3 is making things a bit awkward for projects that import the LXD client. For projects that cannot re-license to AGPLv3, the only options that exist is to either stay on an old version of the client (which may not work with future versions of LXD), resort to runing `Exec()` calls against the `lxc` CLI or simply remove LXD support (which would be a shame).

Could the go client code be decoupled from LXD and be left as Apache 2.0?

**Comment by tomponline** [comment]
Hi,

There has been an update post about this here https://discourse.ubuntu.com/t/an-update-on-the-licence-change-and-community-image-server/41549
