### ISSUE TITLE
Replace password auth by trust token

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12686]
This has been discussed previously and password support is less visible that it used to be but we should ensure it doesn't go in the next LXD. This should be similar to https://github.com/lxc/incus/pull/62

**Comment by tomponline** [comment]
I think its too close to the LTS release date to remove this functionality without consulting with other teams/users as to whether they depend on this functionality and would need to make their own updates. We could remove this in 6.0 potentially though.

**Comment by tomponline** [comment]
@escabo are you happy for us to go ahead and remove the trust password concept?

**Comment by tomponline** [comment]
> This way we can backport this addition into the 6.X releases.

You mean 5.21.x  releases? We dont do backports for 6.x releases.

**Comment by roosterfish** [comment]
> You mean 5.21.x releases? We dont do backports for 6.x releases.

Yes thanks for catching this! I have updated the comment.
