### ISSUE TITLE
LXD network lxdbr0 interface dhcp feature is not explained in docs

### ISSUE THREAD

**Issue by selcem-artan** [canonical/lxd#12696]
As Juju supports Microk8s and LXD controller types, charms could be also installed as LXD machine charms in addition to microk8s charms. In case of LXD controller usage, by default both IPv4 and IPv6 is enabled for “lxdbr0” bridge network. To enable ipv4 address allocation for LXD machines, it needs to be set "lxc network set lxdbr0 ipv4.dhcp=true" 

However, this setting does not seem to be documented anywhere in the Reference [check]. Is there a place where I can find a list of all the settings? It would be good to have something like that in the Reference docs. 

In Juju docs, in the Reference doc on LXD (https://juju.is/docs/juju/lxd), in the Machines row, add a note about changing IP protocols with a link to the LXD reference doc that covers it.

**Comment by tomponline** [comment]
Hi @selcem-artan if `ipv{n}.dhcp` isn't specified in the network config then DHCP is enabled by default.
Its only disabled if `ipv{n}.dhcp` is set to `false`.

This is documented here https://documentation.ubuntu.com/lxd/en/latest/reference/network_bridge/ where the value in the Default column is `true` for ipv4.dhcp and ipv6.dhcp.

Does that answer your question?

**Comment by selcem-artan** [comment]
Hello Tom,

thanks for your reply. In my case, default settings were in use and I saw
ipv4 or ipv6 addresses randomly allocated. So, which version will be
prioritized?

***@***.***:~/vault/charm-vault/src/lib/charm$ lxc network
list

+-----------+----------+---------+-----------------+---------------------------+-------------+---------+---------+

| NAME | TYPE | MANAGED | IPV4 | IPV6 | DESCRIPTION | USED BY | STATE |

+-----------+----------+---------+-----------------+---------------------------+-------------+---------+---------+

| lxdbr0 | bridge | YES | 10.114.204.1/24 | fd42:2b17:24ec:5608::1/64 | |
14 | CREATED |

***@***.***:~/vault/charm-vault$ juju status

Model   Controller  Cloud/Region     Version  SLA      Timestamp

deneme  selcem  localhost/localhost  3.1.6 unsupported  09:41:40+03:00

App Version  Status   Scale  Charm  Channel   Rev  Exposed  Message

vault       waiting 0/1  vault         10  no   waiting for machine

Unit  Workload  Agent   Machine  Public address                      Ports
Message

vault/8   waiting   allocating  9    fd42:2b17:24ec:5608:216:3eff:fe43:c009
    waiting for machine

Machine  State Address                             Inst id    Base      AZ
Message

9    pending  fd42:2b17:24ec:5608:216:3eff:fe43:c009  juju-cca972-9
***@***.***  Running


To allocate ipv4 address while deploying charm, one has to set (???)

lxc network set lxdbr0 ipv4.dhcp=true

And as a result, for a newly created container ip will be ipv4.

***@***.***:~/vault/charm-vault$ juju status

Model   Controller  Cloud/Region     Version  SLA      Timestamp

deneme  selcem  localhost/localhost  3.1.6 unsupported  09:46:37+03:00

App Version  Status   Scale  Charm  Channel  Rev  Exposed  Message

vault       waiting 0/1  vault        11  no   waiting for machine

Unit Workload  Agent   Machine  Public address  Ports  Message

vault/9  waiting   allocating  10   10.114.204.199     waiting for machine

Machine  State Address     Inst id     Base      AZ  Message
10   pending  10.114.204.199  juju-cca972-10  ***@***.***  Running

Regards,
Selcem

**Comment by tomponline** [comment]
Hi,

I'm afraid I'm not that familiar with the charms you're referring to or how LXD is being configured by them.

Have you checked `lxc network show <network>` to see how LXD is being setup to confirm its not being explicitly disabled for some reason?

But I would expect both IPv4 and IPv6 to be allocated by default for bridge networks.

Also, what version of LXD is being used here?

Finally, for future reference support queries should go to our forum first before opening a GH issue: https://discourse.ubuntu.com/c/lxd/support/149

Thanks

**Comment by selcem-artan** [comment]
Hello Tom,

I am running Juju on LXD and LXD version is "5.19". I can tell "ipv4.dhcp"
was not "True" by default, I set it as below. And as seen also, "ipv6.dhcp"
is not set "True" by default.

***@***.***:~/vault/charm-vault/test$ lxc network show
lxdbr0
config:
  ipv4.address: 10.114.204.1/24
  ipv4.dhcp: "true"          --> I set it manually
  ipv4.nat: "true"
  ipv6.address: fd42:2b17:24ec:5608::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
-
/1.0/instances/base-instance-charmcraft-buildd-base-v50-97ec57918ad3a9bc094a?project=charmcraft
-
/1.0/instances/base-instance-charmcraft-buildd-base-v50-a3fd9dbcaa7d9c31f30b?project=charmcraft
-
/1.0/instances/base-instance-charmcraft-buildd-base-v50-ff9bd43869d54fb637a0?project=charmcraft
- /1.0/instances/charmcraft-vault-10354808-0-0-amd64?project=charmcraft
- /1.0/instances/charmcraft-vault-10616839-0-0-amd64?project=charmcraft
- /1.0/instances/charmcraft-vault-10616839-4-0-amd64?project=charmcraft
- /1.0/instances/charmcraft-vault-10616839-8-0-amd64?project=charmcraft
- /1.0/instances/juju-69cb70-0
- /1.0/instances/juju-69cb70-3
- /1.0/instances/juju-ca7fd4-0
- /1.0/instances/juju-e83952-6
- /1.0/instances/juju-ef39a7-0
- /1.0/profiles/default
- /1.0/profiles/default?project=charmcraft
managed: true
status: Created
locations:
- none

Regards,
Selcem

**Comment by tomponline** [comment]
Yes, but my point is that if its not set, then it defaults to enabled (true).

To show this, please try this (without involving juju):

```
lxc network create foo
lxc network show foo
config:
  ipv4.address: 10.163.161.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:776b:5cc2:cad3::1/64
  ipv6.nat: "true"
description: ""
name: foo
type: bridge
used_by:
- /1.0/instances/c1
managed: true
status: Created
locations:
- none

lxc launch ubuntu:22.04 c1 -n foo
```

Does this get an IPv4 and IPv6 address?

**Comment by selcem-artan** [comment]
Hello Tom,

It gets both ipv4 and ipv6, but for one of Juju instance below, only ipv6
allocated.

***@***.***:~# lxc list
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
|     NAME      |  STATE  |         IPV4          |
IPV6                      |   TYPE    | SNAPSHOTS |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
*| c1            | RUNNING | 10.249.33.186 (eth0)  |
fd42:3b8c:cf4c:6419:216:3eff:fec2:d83a (eth0) | CONTAINER | 0         |*
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-69cb70-0 | RUNNING | 10.233.251.1 (lxdbr0) |
fd42:2b17:24ec:5608:216:3eff:feae:320d (eth0) | CONTAINER | 0         |
|               |         | 10.114.204.232 (eth0) |
                      |           |           |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
*| juju-69cb70-4 | RUNNING |                       |
fd42:2b17:24ec:5608:216:3eff:fe29:8b1e (eth0) | CONTAINER | 0         |*
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+

Regards,
Selcem

**Comment by tomponline** [comment]
Right, so I suspect this is an issue with the instance itself, rather than LXD.
The IPv6 address is being allocated via IPv6 router advertisements and thus does not depend on the network configuration inside the instance to have run, whereas IPv4 is allocated by DHCP and requires a DHCP client to run inside the instance.

Its possible that something is holding up/failing the network setup inside the instance.

What does the journalctl inside the problem container show?

**Comment by selcem-artan** [comment]
Hello Tom,

this looks like not related with LXD but with Juju. If you check below
charm has also acquired ip4 address in addditon to ipv6. But in "Juju
status" we can see only IPv6 address. I think it should either show ipv4
and ipv6 or show only ipv4 for ease of usage. What's your view on that?

***@***.***:~# juju status
Model    Controller  Cloud/Region         Version  SLA          Timestamp
new-lxd  new-lxd     localhost/localhost  3.1.6    unsupported
 14:30:04+03:00

App    Version  Status   Scale  Charm  Channel  Rev  Exposed  Message
vault  1.8.8    blocked      1  vault             0  no       Vault needs
to be initialized

Unit      Workload  Agent  Machine  Public address
 Ports     Message
vault/9*  blocked   idle   4       * fd42:2b17:24ec:5608:216:3eff:fe29:8b1e
* 8200/tcp  Vault needs to be initialized

Machine  State    Address                                 Inst id
   Base          AZ  Message
0        started  10.114.204.232                          juju-69cb70-0
   ***@***.***      Running
0/lxd/0  pending
 juju-69cb70-0-lxd-0  ***@***.***      Container started
0/lxd/1  pending
 juju-69cb70-0-lxd-1  ***@***.***      Container started
4        started  *fd42:2b17:24ec:5608:216:3eff:fe29:8b1e*  juju-69cb70-4
     ***@***.***      Running
5        started  10.114.204.236                          juju-69cb70-5
   ***@***.***      Running
***@***.***:~#


***@***.***:~# juju exec --unit vault/9 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group
default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
120: ***@***.***: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
state UP group default qlen 1000
    link/ether 00:16:3e:29:8b:1e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet *10.114.204.179/24 <http://10.114.204.179/24> *metric 100 brd
10.114.204.255 scope global dynamic eth0
       valid_lft 2150sec preferred_lft 2150sec
    inet6 fd42:2b17:24ec:5608:216:3eff:fe29:8b1e/64 scope global mngtmpaddr
noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe29:8b1e/64 scope link
       valid_lft forever preferred_lft forever


***@***.***:~# lxc list
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
|     NAME      |  STATE  |         IPV4          |
IPV6                      |   TYPE    | SNAPSHOTS |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| c1            | RUNNING | 10.249.33.186 (eth0)  |
fd42:3b8c:cf4c:6419:216:3eff:fec2:d83a (eth0) | CONTAINER | 0         |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-69cb70-0 | RUNNING | 10.233.251.1 (lxdbr0) |
fd42:2b17:24ec:5608:216:3eff:feae:320d (eth0) | CONTAINER | 0         |
|               |         | 10.114.204.232 (eth0) |
                      |           |           |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
*| juju-69cb70-4 | RUNNING | 10.114.204.179 (eth0) |
fd42:2b17:24ec:5608:216:3eff:fe29:8b1e (eth0) | CONTAINER | 0         |*
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-69cb70-5 | RUNNING | 10.114.204.236 (eth0) |
fd42:2b17:24ec:5608:216:3eff:feee:fa45 (eth0) | CONTAINER | 0         |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-ca7fd4-0 | RUNNING | 10.114.204.69 (eth0)  |
fd42:2b17:24ec:5608:216:3eff:fe5a:4546 (eth0) | CONTAINER | 0         |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-e83952-6 | RUNNING | 10.114.204.37 (eth0)  |
fd42:2b17:24ec:5608:216:3eff:fe2c:2f3a (eth0) | CONTAINER | 0         |
+---------------+---------+-----------------------+-----------------------------------------------+-----------+-----------+
| juju-ef39a7-0 | RUNNING | 10.114.204.193 (eth0) |
fd42:2b17:24ec:5608:216:3eff:fed3:8a8f (eth0) | CONTAINER | 0         |


Regards,
Selcem

**Comment by tomponline** [comment]
> If you check below charm has also acquired ip4 address in addditon to ipv6. But in "Juju status" we can see only IPv6 address. I think it should either show ipv4 and ipv6 or show only ipv4 for ease of usage. What's your view on that?

My suggestion would be for juju to show both/any IPs associated to the instance.

**Comment by tomponline** [comment]
@selcem-artan happy to close this issue now? Thanks

**Comment by selcem-artan** [comment]
Thanks Tom
