### ISSUE TITLE
Incorrect error message for reusing osd pool

### ISSUE THREAD

**Issue by mas-who** [canonical/lxd#12719]
# Issue description

When creating a new storage pool based on the `ceph` driver, if the `source` config is set to the name of an existing osd pool in the target ceph cluster, that was created using lxd, the following error is returned:

`Error: Pool 'existing-ceph-pool' in cluster 'ceph' seems to be in use by another LXD instance. Use 'ceph.osd.force_reuse=true' to force`.

This seems to be incorrect as the `ceph.osd.force_reuse` config was deprecated and osd pool reuse is not supported for ceph storage pools by lxd. Suggest to remove mentions of the `ceph.osd.force_reuse` config in the error message.

# Steps to reproduce

 1. run: `lxc storage create ceph-storage-pool ceph source=[existing_osd_pool_name]`
 2. Observe the error output

**Comment by tomponline** [comment]
So we just need to drop the "Use 'ceph.osd.force_reuse=true' to force" bit from the error message.

**Comment by tomponline** [comment]
@MusicDin im going to give this one to Pedro.
