### ISSUE TITLE
OVN setup issue for rest of machines of LXD Cluster

### ISSUE THREAD

**Issue by vips-patel** [canonical/lxd#12729]
Hi,

I have set up the LXD cluster on OVN. OVN is working fine on all 5 servers but containers created in servers 4 and 5 do not ping other containers. Some configs are missing in the documentation for the OVN cluster setup for the LXD Cluster. can you please help with it?

---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/howto/network_ovn_setup/

**Comment by tomponline** [comment]
Hi @vips-patel please can you post your setup over at https://discourse.ubuntu.com/c/lxd/support/149 as support questions are handled there. Thanks
