### ISSUE TITLE
Switch snap to use golang 1.22 when its released

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12734]
Noble appears to have Golang 1.22 as an option https://packages.ubuntu.com/noble/golang-1.22

So when its released I think we should be able to use 1.22 for LXD's snap build too (using the existing Go snap package).

That way we can benefit from new default behavior for loop variables in for loops which is a common cause of bugs.

**Comment by simondeziel** [comment]
> Go 1.22 is expected to be released in February 2024. 

Timing-wise this should be good for the Noble feature-freeze :)

**Comment by GiGurra** [comment]
Any progress on this? 1.22 is released

**Comment by tomponline** [comment]
Done
