### ISSUE TITLE
`/dev/lxd/sock` is world accessible in containers but restricted to root in VMs

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12746]
I don't know if that intentional or not but having the `/dev/lxd/sock` is world accessible in containers is surprising, especially since it's restricted to root in VMs:

```
$ lxc launch ubuntu-daily:22.04 v1 --vm
$ lxc launch ubuntu-daily:22.04 u1
$ sleep 30
$ lxc exec u1 -- ls -l /dev/lxd/
total 0
srw-rw-rw- 1 nobody nogroup 0 Jan 18 14:02 sock
$ lxc exec v1 -- ls -l /dev/lxd/
total 0
srw------- 1 root root 0 Jan 18 17:36 sock
```

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-6dc565a  26672  latest/edge  canonical✓  -
```

**Comment by tomponline** [comment]
@simondeziel please can you see if the container side is a regression?

**Comment by simondeziel** [comment]
@tomponline apparently not a regression as it's reproducible on `5.0/edge` and `5.0/stable`:

```
$ snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-3afa7f6  26630  5.0/edge  canonical✓  -

$ snap list lxd
Name  Version        Rev    Tracking    Publisher   Notes
lxd   5.0.2-838e1b2  24322  5.0/stable  canonical✓  -
```

**Comment by simondeziel** [comment]
Same so that's an old behavior:
```
root@v1:~# snap list lxd
Name  Version        Rev    Tracking    Publisher   Notes
lxd   4.0.9-a29c6f1  24061  4.0/stable  canonical✓  -
root@v1:~# lxc exec c1 -- ls -l /dev/lxd
total 0
srw-rw-rw- 1 nobody nogroup 0 Jan 19 15:13 sock
```

**Comment by tomponline** [comment]
@simondeziel so I guess we should align VMs to be the same.
We should first check if anything sensitive is revealed by /dev/lxd though

**Comment by simondeziel** [comment]
Plot twist, I just found out that in the container case, LXD looks up which user is making the query and only letting root access it:

```
root@c1:~# curl --unix-socket /dev/lxd/sock lxd/1.0/config/user.cloud-init.user-data
#cloud-config
ssh_import_id: lp:sdezielroot@c1:~# 
root@c1:~# sudo -u ubuntu curl --unix-socket /dev/lxd/sock lxd/1.0/config/user.cloud-init.user-data
Access denied for non-root user
```

I think the identification mechanism (`SO_PEERCRED`?) didn't work in the VM case hence the DAC restrictions on the Unix socket.

In a belt and suspenders approach, shouldn't we also ensure the container case has `/dev/lxd/sock` as `root:root` with `0600`?

**Comment by tomponline** [comment]
I imagine that we should be able to make the lxd-agent validate the peer cred in the same way, as that is what creates the unix listener in VMs.

I wonder why it was done like that for containers rather than using the file perms...

**Comment by tomponline** [comment]
Yeah I agree, although not sure about changing containers to be root accessible only without knowing why that mechanism was used instead.

**Comment by simondeziel** [comment]
I tested the container case some more by trying every endpoints mentioned in https://documentation.ubuntu.com/lxd/en/latest/dev-lxd/#api-structure and they all deny non-root users, even `/`.

**Comment by tomponline** [comment]
So I think its clearest to align the perms of the container with the VM, so make the file non-world readable.

**Comment by tomponline** [comment]
@simondeziel maybe first do an audit of the commit history around the functionality and check it wasn't relaxed for a reason historically?

**Comment by tomponline** [comment]
Ah thanks for digging out the reason @simondeziel
