### ISSUE TITLE
Remove the `images:` remote from the `lxc` CLI tool

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12742]
Given that the `images:` remote will soon stop working for LXD users (see https://discuss.linuxcontainers.org/t/important-notice-for-lxd-users-image-server/18479) we should remove it from the default remotes list in the `lxc` CLI tool to avoid confusion.

**Comment by ru-fu** [comment]
This will need a doc update as well.

**Comment by tomponline** [comment]
@MusicDin as you mentioned we should also remove the fix we originally added to support the community image server.
