### ISSUE TITLE
Chocolatey package needs a update

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12752]
The Windows CLI package (https://community.chocolatey.org/packages/lxc) contains a `LICENSE.txt` referring to https://github.com/lxc/lxd/blob/master/COPYING. To see it, go to https://community.chocolatey.org/packages/lxc#files and then click "Show" on `tools\LICENSE.txt`.

The `tools\VERIFICATION.txt` file also refers to https://ci.appveyor.com/project/lxc/lxd/branch/lxd-VERSION/artifacts which might need to be updated for a new project name.

**Comment by tomponline** [comment]
Updated license here https://github.com/canonical/lxd-pkg-chocolatey/commit/c56a8faca9c1a13a8c132483d156ed5a51b2f585

Will be pushed with LXD 5.21 release.

**Comment by tomponline** [comment]
Updated verification here https://github.com/canonical/lxd-pkg-chocolatey/commit/2ccac99def03512ac79e0b8289551d38fbc372cc
