### ISSUE TITLE
Add ability to indicate LTS in `lxc version` and `lxc --version` commands

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#12768]
This will require including something like `server_lts: true` in the `/1.0` API response (api.ServerEnvironment) and an API extension, as well as equivalent info request in /dev/lxd.

We should also add an LTS indicator constant in the `shared/version/flex/version.go` file for use with the CLI.

**Comment by tomponline** [comment]
@MusicDin are you able to take this one?

**Comment by MusicDin** [comment]
Sure
