### ISSUE TITLE
lxd will not start up because of a missing storage pool

### ISSUE THREAD

**Issue by terminaldweller** [canonical/lxd#12774]
# Required information
* Distro: void linux
* Distro version: rolling release
* `lxc info` failes to run since lxd refuses to start
```
$ uname -r
6.6.11_1
```
```
$ lxc --verion
5.20
```
```
$ lxd version
5.20
```
* the storage backend in use is zfs

# Issue description

After upgrade from `5.9` to `5.20`, lxd fails to start at all. The logs mention the failure to add a patch to the missing storage pool causes this but since lxd fails to start at all, I am not able to solve the issue in any way.

# Steps to reproduce

I'm not sure.

# Information to attach

I have attached the logs here:
https://gist.github.com/terminaldweller/6774631bf7931621f458bc889cf65b18

**Comment by terminaldweller** [comment]
adding the storage pool mentioned  in the logs will allow lxd to start,

also I have attached the ZFS version:
```
$ zfs --version
zfs-2.2.2-1
zfs-kmod-2.2.2-1
```

**Comment by tomponline** [comment]
> adding the storage pool mentioned in the logs will allow lxd to start,

When patches are needed to be applied all storage pools must be present to start LXD.

**Comment by terminaldweller** [comment]
even though that puts you in a bit of predicament?
In my case I was lucky that I could have the pool back temporarily to delete it but if that's not an option you can't get lxd to come up to rectify the situation so what are your options then?
