### ISSUE TITLE
Static analysis: Reintroduce `--whole-files` flag

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#12862]
`golangci-lint` was using `--whole-files` to enforce that we fix lint errors in any files that are touched by a commit. This was removed due to time pressure but should be re-added.

See #12861.

**Comment by tomponline** [comment]
@markylaing im also disabling golangci on stable-5.0 as im backporting the file re-arranging and that is throwing up lots of pre-existing linting issues.
