### ISSUE TITLE
Adding headers to API and UI responses

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#12920]
# Required information

 * Distribution: snap
 * Distribution version: 5.20

# Issue description

The UI is served by LXD without compression. Can we enable gzip or similar, to speed up its loading times?

Furthermore, there are several common security headers, that should be set on all responses for HTML, JS, CSS, images under the ui/ route. This might also be relevant for the routes under the 1.0/ route. I suggest to set the following:
```
    response.headers["Permissions-Policy"] = "interest-cohort=()"
    response.headers["X-Content-Type-Options"] = "NOSNIFF"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"
    response.headers["X-Xss-Protection"] = "1; mode=block"
```

# Steps to reproduce

 1. Enable UI
 2. Load /ui in a browser
 3. Check response headers for the html, css, js, image requests  (i.e. F12 on Firefox, go to the network requests and reload to see them).
 4. The headers mentioned above should be set

**Comment by gabrielmougard** [comment]
@edlerd @tomponline updated
