### ISSUE TITLE
`lxc config uefi show` errors out if the VM was never started (no `qemu.nvram`)

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12935]
It seems like the `qemu.nvram` file is created opportunistically but that causes a weird error when trying to show the uefi config:

```
$ lxc init ubuntu-minimal-daily:22.04 m1 --vm
$ lxc config uefi show m1
Error: open /var/snap/lxd/common/lxd/virtual-machines/m1/qemu.nvram: no such file or directory
$ lxc start m1
$ lxc config uefi show m1
variables:
  00163E5FE3A8-5b446ed1-e30b-4faa-871a-3654eca36080:
    data: 3a5001001000afaf040000000100000000000000
    attr: 3
    timestamp: ""
...
```

Returning nothing might be better than providing this error?

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-35aa763  27329  latest/edge  canonical✓  -
```

**Comment by mihalicyn** [comment]
I think it's better to return an error, but more reasonable like `UEFI variables are not initialized yet. Please start an instance at least once.` Because, we definitely don't want to allow user to set UEFI variable before this. We want LXD to create a first (default) UEFI variables set from a template and only after that allow any editing for it.

**Comment by tomponline** [comment]
Hrm although if you want to modify the settings before first boot that would be less useful.
Can we get LXD to generate the initial UEFI vars at instance create time?

**Comment by mihalicyn** [comment]
> Hrm although if you want to modify the settings before first boot that would be less useful.

yep, it always was like that. We doing a lazy initialization of NVRAM depending on the instance configuration during instance start.

> Can we get LXD to generate the initial UEFI vars at instance create time?

Yes, of course, but it's way more work and not directly related to the EFI editor feature.

**Comment by tomponline** [comment]
@mihalicyn  how about we call d.setupNvram() from d.UEFIVarsUpdate() if d.nvramPath() doesn't exist?
