### ISSUE TITLE
REST API documentation doesn't display right with Swagger UI 5.11.8

### ISSUE THREAD

**Issue by ru-fu** [canonical/lxd#12974]
When using Swagger UI v5.11.8, many of the examples in the REST API don't show up correctly:

![image](https://github.com/canonical/lxd/assets/11227796/6c0fa579-815c-451f-985c-85d18fbf71ac)

https://github.com/canonical/lxd/pull/12973 pins the version to v5.11.7, but we should figure out the problem and go back to using the latest version.

[Diff between v5.11.8 and v5.11.7](https://github.com/swagger-api/swagger-ui/compare/v5.11.7...v5.11.8)

**Comment by tyagis** [comment]
Thanks for resolving this! 🚀

**Comment by tomponline** [comment]
@ru-fu do you think this one can be closed now?
