### ISSUE TITLE
Lxd container disappears

### ISSUE THREAD

**Issue by liyifo** [canonical/lxd#12995]
My lxd container mysteriously disappeared.
Let me introduce the situation:
On February 22nd, running the Python program inside the container did not respond. After restarting the container, the container failed and lost contact.
There was an issue with restarting the system on the 26th. Now, while reading the data, no container was found, except for log.
I renamed lxc. conf to lxc. txt, which mentioned that lxc. rootfs. path=dir:/var/lib/lxd/storage tools/pool1/containers/qluai4/rootfs, but the pool1 folder is empty.
All my data is lost, is there any hope of recovery?
![58620e1fe3edf19e9082f4e3fc71bb3](https://github.com/canonical/lxd/assets/80516655/1dec9380-d909-4738-9349-62761a9ec66c)
[console.log](https://github.com/canonical/lxd/files/14445398/console.log)
[proxy.forward6004.log](https://github.com/canonical/lxd/files/14445415/proxy.forward6004.
[lxc.txt](https://github.com/canonical/lxd/files/14445428/lxc.txt)
log)
![image](https://github.com/canonical/lxd/assets/80516655/350d2969-de2f-469a-8e6a-67809a3d1a6c)

**Comment by liyifo** [comment]
[proxy.forward6004.log](https://github.com/canonical/lxd/files/14445468/proxy.forward6004.log)

**Comment by tomponline** [comment]
Hi @liyifo please can you post support requests over on the forum https://discourse.ubuntu.com/c/lxd/support/149
