### ISSUE TITLE
Unhelpful message returned to browser when lxd-ui is disabled

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12997]
When the LXD UI is not enabled, if one tries to access it with a browser this message is returned:

```
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
```

If LXD is able to do user agent sniffing and detect it's not a LXD client trying to access it, it could return a clearer message maybe in a "501 Not Implemented" HTML saying the LXD UI is disabled. Maybe with a link to https://documentation.ubuntu.com/lxd/en/latest/howto/access_ui/

**Comment by tomponline** [comment]
Relevant sections:

https://github.com/canonical/lxd/blob/8245088b46a0d3b60476701836afcf22eca7913d/lxd/api.go#L70-L78
https://github.com/canonical/lxd/blob/8245088b46a0d3b60476701836afcf22eca7913d/lxd/api.go#L122-L129
