### ISSUE TITLE
Licence check fails on Go 1.22.0

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#13048]
See https://github.com/canonical/lxd/actions/runs/8156637138/job/22299617287#step:13:305 and https://github.com/canonical/lxd/pull/13042#issuecomment-1979507605

**Comment by tomponline** [comment]
From my observations it works fine on go 1.22 when using `@latest` but this fails on our GH worflows because `make static-analysis` is pinned at go 1.21 due to swagger incompatibility with go 1.22. https://github.com/go-swagger/go-swagger/issues/3070
