### ISSUE TITLE
doc: unreadable in dark mode

### ISSUE THREAD

**Issue by harridu** [canonical/lxd#13062]
Please check the colors of your online documentation in dark mode. Currently it is unreadable due to lack of contrast (eg blue chars on a black background).
---
Document: howto/network_bgp.md

**Comment by tomponline** [comment]
Similar to https://github.com/canonical/lxd/issues/12244

@edlerd do you have any suggestions for visual improvements of links in dark mode?

**Comment by edlerd** [comment]
Sure, we should probably use the same colours as [vanilla framework](https://vanillaframework.io/docs/patterns/links). For links in dark mode, vanilla uses `#69c`, whereas the current LXD docs use `#06c`.

Though, I wonder where the LXD doc colours come from. Maybe we should use vanilla directly? Or is it using an older version of vanilla? Then an update might fix it.

**Comment by ru-fu** [comment]
> Though, I wonder where the LXD doc colours come from. Maybe we should use vanilla directly? Or is it using an older version of vanilla? Then an update might fix it.

The LXD doc colors come mostly from [Furo](https://github.com/pradyunsg/furo), with some tweaks to make them a bit more Canonical-like. Vanilla didn't have a dark theme at that time.

We'd love to use a Vanilla-based theme, but we've been asking for that for a long time, and it's still not in the plans ...

**Comment by tomponline** [comment]
@ru-fu shall we change the blue colour for now, is that possible?
