### ISSUE TITLE
Configure microceph to allow testing `ceph` in `tests/storage-vm` and `tests/storage-volumes-vm`

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13074]

**Comment by simondeziel** [comment]
Closing in favor of https://github.com/canonical/lxd/issues/13137

**Comment by tomponline** [comment]
Ah sorry I forgot you had this one already. I was just checking over the test results for LXD 5.21.0 and realised i needed to run these manually. Thanks
