### ISSUE TITLE
Add `Content-Security-Policies` response header when serving LXD-UI

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/lxd#13108]
As discussed in https://github.com/canonical/lxd/pull/13100#issuecomment-1991390494, we'd need to enable `Content-Security-Policies` to the LXD UI server assets to avoid X-XSS injection. Some URLs will need to be whitelisted (e.g: `https://assets.ubuntu.com` and `https://cloud-images.ubuntu.com`) in order for the UI assets to be allowed to receive external assets. The other problem we'll be facing is with OIDC login in the UI. We need to tell the server to adapt its CSP rules given the currently used OIDC provider URLs used in the UI assets. Otherwise, the JS script used by the OIDC provider won't be authorized to be injected when needed. These CSP rules on the server related to OIDC need to be dynamically updated (because the OIDC provider can be updated on the server side), so we need to find a way to 'refresh' the CSP rules when a change occurs.

**Comment by edlerd** [comment]
Thanks for opening this as a dedicated issue. I did more testing this morning and with the following CSP everything in the UI seems to work as expected:

```
w.Header().Set("Content-Security-Policy", "default-src 'self' data: https://assets.ubuntu.com https://cloud-images.ubuntu.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'")
```

As for the problems with OIDC I mentioned in [the previous pr](https://github.com/canonical/lxd/pull/13100#discussion_r1521058740), those turned out to be a misconfiguration. After resolving it I could use OIDC properly also with the CSP header as set above.

**Comment by gabrielmougard** [comment]
@edlerd here it is then https://github.com/canonical/lxd/pull/13121

**Comment by tomponline** [comment]
Yes thats right.

**Comment by tomponline** [comment]
@edlerd more generally wrt external assets, we talk quite often about the scenario where microcloud is used in an air-gapped environment. With the revelation that the LXD UI depends on external assets, should those be brought into the LXD UI itself so they are in the snap such that the UI also works in an air-gapped environment?

**Comment by edlerd** [comment]
> @edlerd more generally wrt external assets, we talk quite often about the scenario where microcloud is used in an air-gapped environment. With the revelation that the LXD UI depends on external assets, should those be brought into the LXD UI itself so they are in the snap such that the UI also works in an air-gapped environment?

I think there are only two external assets used in the UI:
1. Fonts from assets.ubuntu.com (we could include those)
2. The image list from cloud-images.ubuntu.com, this probably doesn't make sense to include for an air gapped environment. Do you know where would the images come from in that case?

**Comment by tomponline** [comment]
> The image list from cloud-images.ubuntu.com, this probably doesn't make sense to include for an air gapped environment. Do you know where would the images come from in that case?

Ah yeah for an air gapped environment they would need to use a proxy or import their own images so this is fine.

**Comment by mas-who** [comment]
> The gzip one could be added to /documentation.
> 
> I'm not sure about whether the other ones make sense for that or the /1.0 endpoint (there is no scripting on the API endpoints).

Thanks for clarifying @tomponline :slightly_smiling_face: I think it could be nice to have gzip on the api endpoints since some might return a fair bit of data e.g. `GET /1.0/auth/permissions`?

**Comment by edlerd** [comment]
Right, also the `documentation/objects.inv.txt` and `1.0/metadata/configuration` are >100kb, gzip might be a good idea.

**Comment by gabrielmougard** [comment]
> Right, also the `documentation/objects.inv.txt` and `1.0/metadata/configuration` are >100kb, gzip might be a good idea.

here is the PR for that: https://github.com/canonical/lxd/pull/13164
