### ISSUE TITLE
Auth: Log `can_view_configuration` auth checks at debug level

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#13104]
Additionally, the network and storage handlers are using `can_edit` as a check for whether the caller can view configuration of the network or storage pool. We should change this to `can_view_configuration` as it is more descriptive. 

The authorization model should still allow any caller with `can_edit` permission to also have `can_view_configuration`, e.g.:
```
type network
  relations
    define project: [project]
    define can_edit: [identity, service_account, group#member] or can_edit_networks from project
    define can_delete: [identity, service_account, group#member] or can_delete_networks from project
    define can_view: [identity, service_account, group#member] or can_edit or can_delete or can_view_networks from project
    define can_view_configuration: [identity, service_account, group#member] or can_edit or can_delete or can_view_network_configuration from project
```

**Comment by tomponline** [comment]
I've switched this to the 5.21 milestone as we should get the permissions sorted out and stable before 5.21.0 is released.
