### ISSUE TITLE
Add gzip and security header for documentation and API endpoints

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#13150]
# Required information

 * Distribution: snap
 * Distribution version: 5.21.0-0cbd19b

# Issue description

The documentation served with LXD needs the same security headers as the UI received in #13100 

Both documentation and all API endpoints should have support for gzip. Especially the `1.0/metadata/configuration` and `documentation/objects.inv.txt` paths have large response payloads and would benefit from compression.

# Steps to reproduce
## Documentation
 1. Request local path `GET /documentation`
 2. Check security headers are present and gzip compression is enabled in the response

## API endpoints
 1. Request API endpoint `GET 1.0/metadata/configuration`
 2. Check the response has gzip compression enabled.

**Comment by gabrielmougard** [comment]
@edlerd thanks

**Comment by gabrielmougard** [comment]
@edlerd updated
