### ISSUE TITLE
imagebuilder: Generate SHA for verifying image upload

### ISSUE THREAD

**Issue by MusicDin** [canonical/lxd#13190]
Generate SHA for image files to verify using simplestream maintainer whether the expected content arrived on the imageserver

**Comment by simondeziel** [comment]
> Generate SHA for image files to verify using simplestream maintainer whether the expected content arrived on the imageserver

Those verified fingerprints should be reused rather than compute them again before putting them into the index. This was not immediately clear to me hence the comment :)
