### ISSUE TITLE
Metric names not compatible with openmetrics

### ISSUE THREAD

**Issue by samuelallan72** [canonical/lxd#13194]
Metric family labels appear to break the [Suffixes rule](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes) in the open metrics spec.

For example, `lxd_cpu_seconds_total` should be `lxd_cpu_seconds` in the first two lines here:

```
# HELP lxd_cpu_seconds_total The total number of CPU time used in seconds.
# TYPE lxd_cpu_seconds_total counter
lxd_cpu_seconds_total{cpu="0",mode="system",name="juju-3974d6-0",project="default",type="container"} 96.453461
lxd_cpu_seconds_total{cpu="0",mode="user",name="juju-3974d6-0",project="default",type="container"} 165.58365
lxd_cpu_seconds_total{cpu="0",mode="system",name="juju-1e65f3-0",project="default",type="container"} 1044.756945
lxd_cpu_seconds_total{cpu="0",mode="user",name="juju-1e65f3-0",project="default",type="container"} 1907.128387
```

At least, it appears this way, and [sinkingpoint/openmetrics-parser](https://github.com/sinkingpoint/openmetrics-parser) fails parsing with:

```
    InvalidMetric(
        "Invalid Name in metric family: lxd_cpu_seconds != lxd_cpu_seconds_total",
    ),
```

It's possible this is a bug in that parser project instead of lxd not following the spec; I don't know enough about the spec to confirm.

**Comment by tomponline** [comment]
What do you think about this @simondeziel ?

**Comment by simondeziel** [comment]
The OpenMetrics says that `_total` **should** be avoided for Counters which I can agree with however it's too late to change now.
Also, we've historically used the Prometheus Node Exporter as the reference for our metrics and [there](https://node.demo.do.prometheus.io/metrics) they use `_seconds_total`:

```
# HELP node_cpu_seconds_total Seconds the CPUs spent in each mode.
# TYPE node_cpu_seconds_total counter
node_cpu_seconds_total{cpu="0",mode="idle"} 7.94366552e+06
node_cpu_seconds_total{cpu="0",mode="iowait"} 17752.35
node_cpu_seconds_total{cpu="0",mode="irq"} 0
node_cpu_seconds_total{cpu="0",mode="nice"} 1628.83
node_cpu_seconds_total{cpu="0",mode="softirq"} 18541.48
node_cpu_seconds_total{cpu="0",mode="steal"} 23471.87
node_cpu_seconds_total{cpu="0",mode="system"} 356835.31
node_cpu_seconds_total{cpu="0",mode="user"} 1.35422689e+06
```

And the [Prometheus doc](https://prometheus.io/docs/practices/naming/#metric-names) still mentions `process_cpu_seconds_total` so LXD is definitely not alone in that case.
