### ISSUE TITLE
Can't name block volume device with `lxc storage volume atttach`

### ISSUE THREAD

**Issue by hamistao** [canonical/lxd#13238]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
  Name    Version       Rev    Tracking       Publisher   Notes
  core20  20240111      2182   latest/stable  canonical✓  base
  core22  20240111      1122   latest/stable  canonical✓  base
  lxd     5.20-f3dd836  27049  latest/stable  canonical✓  -
  snapd   2.61.1        20671  latest/stable  canonical✓  snapd,disabled
  snapd   2.61.2        21184  latest/stable  canonical✓  snapd
 ```
 * LXC version: 5.21.0 LTS
 * LXD version: 5.21.0 LTS

# Issue description

When attaching a volume to an instance with `lxc storage volume attach`, the provided device name is interpreted as the device path if the path is not also provided. Because of that, trying to name the created device using `lxc storage volume attach` on a block volume, that doesn't accept a path, results in something similar to `Error: Failed add validation for device "vol1": Custom block volumes cannot have a path defined`.

# Steps to reproduce

 1. `lxc launch ubuntu:22.04 vm --vm # has to be a vm so it accepts block volumes` 
 2. `lxc storage volume create default vol --type=block`
 3. `lxc storage volume attach default vol vm device_name`

**Comment by gabrielmougard** [comment]
Taking a look

**Comment by gabrielmougard** [comment]
@hamistao this should do it:
```patch
diff --git a/lxc/storage_volume.go b/lxc/storage_volume.go
index 31dd7544bb..fea3bc731a 100644
--- a/lxc/storage_volume.go
+++ b/lxc/storage_volume.go
@@ -14,7 +14,7 @@ import (
 	"github.com/spf13/cobra"
 	"gopkg.in/yaml.v2"
 
-	"github.com/canonical/lxd/client"
+	lxd "github.com/canonical/lxd/client"
 	"github.com/canonical/lxd/shared"
 	"github.com/canonical/lxd/shared/api"
 	cli "github.com/canonical/lxd/shared/cmd"
@@ -195,9 +195,15 @@ func (c *cmdStorageVolumeAttach) Run(cmd *cobra.Command, args []string) error {
 	if len(args) == 3 {
 		devName = args[1]
 	} else if len(args) == 4 {
-		// Only the path has been given to us.
-		devPath = args[3]
-		devName = args[1]
+		// Either a device name or a target path has been given to us.
+		if strings.HasPrefix(args[3], "/") {
+			// Only the path has been given to us.
+			devPath = args[3]
+			devName = args[1]
+		} else {
+			// Only the device name has been given to us.
+			devName = args[3]
+		}
 	} else if len(args) == 5 {
 		// Path and device name have been given to us.
 		devName = args[3]

```

What do you think?

**Comment by hamistao** [comment]
Originally the command accepts paths that don't start with `/` and places the path provided under the root directory. But I think it makes sense to only accept paths preceded by `/`, so this should be an appropriate solution.

**Comment by tomponline** [comment]
@gabrielmougard ive assigned this to you as it was still unassigned, but you have a PR open that references it.
