### ISSUE TITLE
Elaborate difference between `lxc launch` and `lxc init` in help text

### ISSUE THREAD

**Issue by sed-i** [canonical/lxd#13243]
The description on [`launch`](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/launch/#lxc-launch-md) and [`init`](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/init/#lxc-init-md) docs is very similar:

```
  lxc init ubuntu:22.04 u1 < config.yaml
      Create the instance with configuration from config.yaml
```
vs
```
  lxc launch ubuntu:22.04 u1 < config.yaml
      Create and start a container with configuration from config.yaml
```

and in the [cloud-init doc](https://documentation.ubuntu.com/lxd/en/latest/cloud-init/) it says to use `init` rather than `launch`.

https://github.com/canonical/lxd/blob/7f0ad17f620f065845b8eda762c692948c22c0b9/doc/cloud-init.md?plain=1#L70

Coming from multipass blueprints, I find this a bit confusing.

I'm also curious about the effect of `--preseed` in `lxd init --preseed` and how it compares to the above.

**Comment by holmanb** [comment]
> The description on [launch](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/launch/#lxc-launch-md) and [init](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/init/#lxc-init-md) docs is very similar:

The diff between those two descriptions, 'and start' is key.

The `launch` command is basically shorthand for `lxc init ubuntu:22.04 u1 < config.yaml && lxc start u1`.

i.e., if you don't want the instance started, just use `lxc init`, otherwise use `lxc launch`

**Comment by sed-i** [comment]
Thanks @holmanb!
Another diff is `instance` vs. `container`. I imagine it should be `instance` in both cases? I guess instance is "container or vm".

**Comment by sed-i** [comment]
Btw, what does `--preseed` add to this?

**Comment by holmanb** [comment]
> I imagine it should be instance in both cases?

I'm guessing that's just accidentally inconsistent.

> Btw, what does --preseed add to this?

I think [the docs](https://documentation.ubuntu.com/lxd/en/stable-4.0/preseed/#non-interactive-configuration-via-preseed-yaml) explain it pretty well - it's intended for providing an instance configuration non-interactively.

**Comment by sed-i** [comment]
Got it! So, iiuc,
- `lxd init --preseed` takes a LXD daemon config.
- `lxc init` and `lxc launch` take a cloud-init.
- There is no overlap between the two, except for the toplevel key being called `config` in both.

Is there a schema doc for the lxd daemon config?

**Comment by tomponline** [comment]
Yes we should update lxc launch and lxc init help text to be consistent, with the only difference being that launch starts the instance after creating it.

**Comment by tomponline** [comment]
@sed-i for future reference support questions are best asked over on the forums 

https://discourse.ubuntu.com/c/lxd/126

Thanks!
