### ISSUE TITLE
`lxc image list` does not use `core.proxy_https`

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13259]
`lxc image list` doesn't use the `core.proxy_https` config while other image operation do like `lxc image copy`. Here's how to reproduce this with a bogus proxy:

```
$ lxc launch ubuntu-daily:22.04 u1
$ lxc shell u1
root@u1:~# lxd init --auto
root@u1:~# lxc config set core.proxy_https http://127.0.0.1:9090
To start your first container, try: lxc launch ubuntu:22.04
Or for a virtual machine: lxc launch ubuntu:22.04 --vm

root@u1:~# snap restart lxd
2024-04-04T17:37:03Z INFO Waiting for "snap.lxd.daemon.service" to stop.
Restarted.
root@u1:~# lxc image list ubuntu-minimal-daily:22.04 | head -n 5
+------------+--------------+--------+---------------------------------------------------+--------------+-----------------+-----------+------------------------------+
|   ALIAS    | FINGERPRINT  | PUBLIC |                    DESCRIPTION                    | ARCHITECTURE |      TYPE       |   SIZE    |         UPLOAD DATE          |
+------------+--------------+--------+---------------------------------------------------+--------------+-----------------+-----------+------------------------------+
| j (9 more) | c489c561074e | yes    | ubuntu 22.04 LTS amd64 (minimal daily) (20240403) | x86_64       | CONTAINER       | 133.77MiB | Apr 3, 2024 at 12:00am (UTC) |
+------------+--------------+--------+---------------------------------------------------+--------------+-----------------+-----------+------------------------------+
root@u1:~# lxc image copy ubuntu-minimal-daily:22.04 local:
Error: Failed remote image download: Failed getting remote image info: Failed getting image: Failed parsing stream: Get "https://cloud-images.ubuntu.com/minimal/daily/streams/v1/index.json": proxyconnect tcp: dial tcp 127.0.0.1:9090: connect: connection refused
```

This has been confirmed on LXD `4.0/stable`, `5.0/stable`, `5.21/edge` and `latest/edge`.

**Comment by simondeziel** [comment]
Even the `lxc image copy` operation seems to first try a direct connection before retrying using the HTTPS proxy.

With a working/valid proxy configured but without direct outbound network connectivity blocked, we can see how much slower it is due to the timeout+fallback:

## Fast when direct outbound connectivity is permitted:

```
root@u1:~# time lxc image copy images:alpine/3.16 local:
Image copied successfully!                   

real	0m2.084s
user	0m0.018s
sys	0m0.052s

root@u1:~# lxc image list
+-------+--------------+--------+-------------------------------+--------------+-----------+---------+-----------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |          DESCRIPTION          | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE         |
+-------+--------------+--------+-------------------------------+--------------+-----------+---------+-----------------------------+
|       | c7cd5f923852 | no     | alpine  amd64 (20240404_0017) | x86_64       | CONTAINER | 2.50MiB | Apr 4, 2024 at 7:15pm (UTC) |
+-------+--------------+--------+-------------------------------+--------------+-----------+---------+-----------------------------+
root@u1:~# lxc image rm c7cd5f923852
```

## Slow fallback when direct outbound connectivity is not allowed:

```
root@u1:~# iptables -I OUTPUT -p tcp -d images.lxd.canonical.com -j DROP
root@u1:~# ip6tables -I OUTPUT -p tcp -d images.lxd.canonical.com -j DROP

root@u1:~# time lxc image copy images:alpine/3.16 local:
Image copied successfully!                   

real	4m30.351s
user	0m0.053s
sys	0m0.038s
```

**Comment by tomponline** [comment]
@simondeziel as `core.proxy_https` is a LXD server setting I wouldn't expect it to (nor can it) influence how the `lxc` command makes external calls. For this I would expect the HTTPS_PROXY env var to influence it.

I couldn't see from your reproducer steps above an example of `lxc image list` not working with a proxy though?

**Comment by simondeziel** [comment]
> @simondeziel as `core.proxy_https` is a LXD server setting I wouldn't expect it to (nor can it) influence how the `lxc` command makes external calls. For this I would expect the HTTPS_PROXY env var to influence it.

Indeed, it makes sense and it works when I use `HTTPS_PROXY=http://squid.sdeziel.info:3128 lxc image ls images:`. Thanks for straightening that up for me!

> I couldn't see from your reproducer steps above an example of `lxc image list` not working with a proxy though?

Maybe I'm still not understanding it fully but should `lxc image copy` (not `list`) obey the `core.proxy_https` or is the `lxc` command initially involved with contacting the remote first?

**Comment by tomponline** [comment]
> Maybe I'm still not understanding it fully but should `lxc image copy` (not `list`) obey the `core.proxy_https` or is the `lxc` command initially involved with contacting the remote first?

I'm not sure about that, more investigation needed I would say.

**Comment by simondeziel** [comment]
While I didn't look at the code, the experimentation in the "Slow fallback when direct outbound connectivity is not allowed" section of the bug description is exactly that. I see many direct tentative connections before it eventually moves on to going through the proxy.

At home, my LXD server needs to go through the proxy as all direct outbound connections are dropped. There, I see many firewall logs dropping direct connections which explains the long delay before the actual copy begins through the proxy.

I just realized that those dropped connections are for direct HTTP (no S) which makes sense as I don't have `core.proxy_http`, just the `https` one defined. Now I'm not sure why this simplestream remote is connected to using HTTP while the remote definition has HTTPS in it.

**Comment by tomponline** [comment]
Probably because of:

https://github.com/canonical/lxd/blob/9ef74cf3ae200a184867e55949df6c45ad13acd0/client/simplestreams_images.go#L97-L101

**Comment by simondeziel** [comment]
I just exported both `core.proxy_http` and `core.proxy_https` and now `lxc image copy` is super fast.

So it seems like the root case of the "issue" is that simplestreams remote are first connected using HTTP with a fallback to HTTPS. That dual protocol rings a bell now. IIRC the fingerprint would be fetched over HTTPS and the bulk data transfer would tentatively happen over HTTP if possible.
