### ISSUE TITLE
Document internal VM live migration process 

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#13307]
Produce a document in this repository explaining how the VM live migration process & protocol works to aid future developments on it.

**Comment by kadinsayani** [comment]
@tomponline would this be a good exercise for me to do as part of my upcoming work improving live migration of VMs between different CPU architectures?

**Comment by tomponline** [comment]
> @tomponline would this be a good exercise for me to do as part of my upcoming work improving live migration of VMs between different CPU architectures?

Sounds good thanks!
