### ISSUE TITLE
copy --refresh for vm from another server fails with: Snapshot cannot be restored due to subsequent snapshot(s)

### ISSUE THREAD

**Issue by borgeira** [canonical/lxd#13304]
Bug report:
https://github.com/lxc/incus/issues/457

Solution:
https://github.com/lxc/incus/pull/517/commits/2fc95eb5ef355ad507d4369b355b687713f920f9

Its affecting LXD 5.21/stable (5.21.1-3f3c2a9).

**Comment by borgeira** [comment]
Its affecting LXD 5.21/stable (5.21.1-3f3c2a9).

**Comment by tomponline** [comment]
This is now cherry-picked into the 5.21/stable snap channel.
