### ISSUE TITLE
Add create and start endpoint

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#13322]
# Required information

 * Distribution: 5.21 LTS
 * Distribution version: snap

# Issue description

Please add the option to start an instance to the `POST 1.0/instances` API endpoint. This could be an additional query parameter like `?start=true` or expressed in the payload.

Motivation is LXD-UI. It has an option to "create and start" an instance, which under the hood posts to `1.0/instances`. Once the instance is created, the UI changes the state of the instance via `PUT 1.0/instances/:instance/state`. This is the same as the CLI is doing it. But in the UI this is problematic, because a user might refresh the page in between -- i.e. when the creation is taking a long time because the image needs to be fetched first. In that case the ui is missing to send the 2nd request, because the callback to do so is lost due to the refresh operation.

**Comment by hamistao** [comment]
I think this would be good for @boltmark to look at

**Comment by tomponline** [comment]
Yeah note this is just a cherry pick.
