### ISSUE TITLE
Failed to start virtiofsd error wtih lxd 5.21.1 LTS

### ISSUE THREAD

**Issue by aludman** [canonical/lxd#13325]
# Required information

 * Distribution: `Ubuntu`
 * Distribution version: `20.04.6 LTS`
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
 Name    Version       Rev    Tracking       Publisher   Notes
core20  20240227      2264   latest/stable  canonical✓  base
core20  20240111      2182   latest/stable  canonical✓  base,disabled
core22  20231123      1033   latest/stable  canonical✓  base,disabled
core22  20240111      1122   latest/stable  canonical✓  base
lxd     5.20-f3dd836  27049  5.20/stable    canonical✓  held
snapd   2.61.2        21184  latest/stable  canonical✓  snapd
snapd   2.61.1        20671  latest/stable  canonical✓  snapd,disabled
````
 * The output of "lxc info":
 Note that this is from after we have reinstalled 5.20 since I do not want to go back and break ths system just so I can get this information. The problem is very easily reproduced using the steps further below.
 
[lxcinfo.txt](https://github.com/canonical/lxd/files/14963744/lxcinfo.txt)

# Issue description

We're unable start / exec to our lxd vms after an automatic refresh of lxd snap from 5.20 to 5.21.1.

The error we get is the following:
> Error: Failed to start device "SHARED_DIR": Failed to setup virtiofsd for device "SHARED_DIR": Failed to start virtiofsd: Unable to start process: fork/exec /snap/lxd/28156/bin/virtiofsd: invalid argument

I was expecting the system to work as before after the automatic update.

Reverting back to 5.20 using `sudo snap revert lxd` resulted in lxd not working at all, so we ended up uninstalling lxd completely and reinstalling the 5.20 version and recreating everything from scratch, which resolved our issue.

# Steps to reproduce

The problem is reproducible on *our system* by following these basic steps:
```
sudo snap install lxd
lxd init --minimal
lxc init ubuntu:22.04 --vm test
lxc config set test limits.cpu=8 limits.memory=4GiB
echo -en "both $(id -u) 0" | lxc config set test raw.idmap -
lxc config device add test SHARED_DIR disk source="/tmp" path="/mnt/tmp"
lxc start test
lxc exec test -- /bin/bash
```
The key step is the `lxc config set test raw.idmap` step. If I skip that then the instance starts up just fine.
The `lxc config set test limits.cpu=8 limits.memory=4GiB` step is probably not important but it was part our steps, so I've included it.

**Comment by mihalicyn** [comment]
Hi @aludman !

>Reverting back to 5.20 using sudo snap revert lxd resulted in lxd not working at all, so we ended up uninstalling lxd completely and reinstalling the 5.20 version and recreating everything from scratch, which resolved our issue.

Ugh, this is really painful. Sorry about that.

I have created a PR with the fix for this problem https://github.com/canonical/lxd/pull/13332

**Comment by tomponline** [comment]
This is now cherry-picked into the 5.21/stable snap channel.
