### ISSUE TITLE
LXD 5.21.1 Failed to ensure schema: not an error

### ISSUE THREAD

**Issue by chuegel** [canonical/lxd#13326]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ``` 
snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240111        2182   latest/stable  canonical✓  base,disabled
core20  20240227        2264   latest/stable  canonical✓  base
core22  20231123        1033   latest/stable  canonical✓  base,disabled
core22  20240111        1122   latest/stable  canonical✓  base
lxd     5.20-f3dd836    27049  latest/stable  canonical✓  disabled
lxd     5.21.1-43998c6  28155  latest/stable  canonical✓  -
snapd   2.61.1          20671  latest/stable  canonical✓  snapd,disabled
snapd   2.61.2          21184  latest/stable  canonical✓  snapd
````
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-209-generic
   * LXC version: 5.21.1 LTS
   * LXD version: 5.21.1 LTS
   * Storage backend in use: BTRFS

# Issue description

Since the last update I get on any `lxc` commands following error:
```
Error: LXD unix socket not accessible: Get "http://unix.socket/1.0": EOF
````
The containers itself are running as I can reach the services behind them.

Below are some logs collected from the server:

```
cat /var/snap/lxd/common/lxd/logs/lxd.log
time="2024-04-14T16:59:23+02:00" level=warning msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored"
```
syslog

```
Apr 14 17:03:09 bionic systemd[1]: Started Service for snap application lxd.daemon.
Apr 14 17:03:09 bionic lxd.daemon[31828]: => Preparing the system (28155)
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Loading snap configuration
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Setting up mntns symlink (mnt:[4026532607])
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Setting up kmod wrapper
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Preparing /boot
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Preparing a clean copy of /run
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Preparing /run/bin
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Preparing a clean copy of /etc
Apr 14 17:03:09 bionic lxd.daemon[31828]: ==> Preparing a clean copy of /usr/share/misc
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Setting up ceph configuration
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Setting up LVM configuration
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Setting up OVN configuration
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Rotating logs
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Unsupported ZFS version (0.7)
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Escaping the systemd cgroups
Apr 14 17:03:10 bionic lxd.daemon[31828]: ====> Detected cgroup V1
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Escaping the systemd process resource limits
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Enabling LXD UI
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Exposing LXD documentation
Apr 14 17:03:10 bionic lxd.daemon[31828]: => Re-using existing LXCFS
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Reloading LXCFS
Apr 14 17:03:10 bionic lxd.daemon[31828]: ==> Cleaning up existing LXCFS namespace
Apr 14 17:03:10 bionic lxd.daemon[31828]: => Starting LXD
Apr 14 17:03:10 bionic lxd.daemon[31828]: time="2024-04-14T17:03:10+02:00" level=warning msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored"
Apr 14 17:03:11 bionic kernel: [22395832.644410] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c96fb0 len 40960 err no 10
Apr 14 17:03:11 bionic kernel: [22395832.644424] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c97000 len 65536 err no 10
Apr 14 17:03:11 bionic kernel: [22395832.644429] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c97080 len 8192 err no 10
Apr 14 17:03:11 bionic lxd.daemon[31828]: time="2024-04-14T17:03:11+02:00" level=error msg="Failed to start the daemon" err="Failed to initialize global database: failed to ensure schema: Failed to ensure schema: not an error"
Apr 14 17:03:12 bionic lxd.daemon[31828]: Error: Failed to initialize global database: failed to ensure schema: Failed to ensure schema: not an error
Apr 14 17:03:12 bionic lxd.user-daemon[31734]: Error: Unable to connect to LXD: Get "http://unix.socket/1.0": EOF
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.user-daemon.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.user-daemon.service: Failed with result 'exit-code'.
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.user-daemon.service: Service hold-off time over, scheduling restart.
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.user-daemon.service: Scheduled restart job, restart counter is at 253.
Apr 14 17:03:12 bionic systemd[1]: Stopped Service for snap application lxd.user-daemon.
Apr 14 17:03:12 bionic systemd[1]: Started Service for snap application lxd.user-daemon.
Apr 14 17:03:12 bionic lxd.daemon[31828]: Killed
Apr 14 17:03:12 bionic lxd.daemon[31828]: => LXD failed to start
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.daemon.service: Service hold-off time over, scheduling restart.
Apr 14 17:03:12 bionic systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 253.
Apr 14 17:03:12 bionic systemd[1]: Stopped Service for snap application lxd.daemon.
```

# Steps to reproduce
Not sure

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Hi,

I've taken a look in the LXD source code and cannot see "not an error" as an error that LXD generates.

One thing that certainly looks problematic are those BTRFS errors coming from the kernel:

```
Apr 14 17:03:11 bionic kernel: [22395832.644410] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c96fb0 len 40960 err no 10
Apr 14 17:03:11 bionic kernel: [22395832.644424] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c97000 len 65536 err no 10
Apr 14 17:03:11 bionic kernel: [22395832.644429] BTRFS warning (device dm-0): direct IO failed ino 615 rw 1,2131969 sector 0x24c97080 len 8192 err no 10
```

I'm wondering if this is a dqlite issue with direct I/O.

**Comment by chuegel** [comment]
Thanks for your reply. I overlooked those BTRFS errors...Indeed that doesn't look good.
Interesting thing is that the containers are still online. Wonder if this is related to the latest kernel update I did.

**Comment by haryHuds0n** [comment]
Hi,
I am also facing the same problem in this issue now
The log I got is exactly the same

`level=error msg="Failed to start the daemon" err="Failed to initialize global database: failed to ensure schema: Failed to ensure schema: not an error"`

LXD and services in container are still running after I restart LXD several time, but I can't do anything else. That's odd.

**Comment by roosterfish** [comment]
@haryHuds0n do you also see those BTRFS related errors? Which version of Ubuntu (and kernel) are you using?

**Comment by haryHuds0n** [comment]
> @haryHuds0n do you also see those BTRFS related errors? Which version of Ubuntu (and kernel) are you using?

Thank for your reply,

No, I don't see those BTRFS related errors.
The error log line I have only the above line
FYI, I am using Ubuntu 20.04.6 LTS and kernel version 5.4.0-40-generic.

**Comment by haryHuds0n** [comment]
UPDATE
After performing an update and upgrading the kernel, as well as installing the HWE kernel, my LXD is now functioning normally. Here is the link to the [discourse](https://discourse.ubuntu.com/t/lxd-5-21-1-lts-has-been-released/43823/15) I referenced.

**Comment by tomponline** [comment]
If you have further issues please can you post over in the forum https://discourse.ubuntu.com/c/lxd/support/149

Thanks

**Comment by chuegel** [comment]
Unfortunately I cannot create new topics in the forum.
I installed the HWE kernel with 
`apt-get install --install-recommends linux-generic-hwe-18.04`

```
uname -r
5.4.0-150-generic
```
but the error still persists. Now the containers are not even starting.

**Comment by tomponline** [comment]
@cole-miller is there a fix we can apply to the dqlite build in lxd to avoid this error?

**Comment by tomponline** [comment]
Also see https://discourse.ubuntu.com/t/lxd-5-21-1-lts-has-been-released/43823/61

**Comment by tomponline** [comment]
> Unfortunately I cannot create new topics in the forum. I installed the HWE kernel with `apt-get install --install-recommends linux-generic-hwe-18.04`
> 
> ```
> uname -r
> 5.4.0-150-generic
> ```
> 
> but the error still persists. Now the containers are not even starting.

As it doesn’t appear that the schema changes have been applied you could try switching to the 5.20/stable channel using:

`sudo snap refresh lxd --channel=5.20/stable`

**Comment by chuegel** [comment]
Downgrading to 5.20 worked like a charm. Also the BTRFS errors are gone.
Thanks

**Comment by tomponline** [comment]
@MggMuggins if you have any time would be great to see if we can get a reproducer for this one.

**Comment by tomponline** [comment]
@MggMuggins also see https://chat.canonical.com/canonical/pl/j33w411ydibnpcj67bwtidnzya for more context

**Comment by cole-miller** [comment]
Hi! If you're affected by this issue, you can help us troubleshoot by following the instructions here: https://discourse.ubuntu.com/t/lxd-5-21-1-lts-has-been-released/43823/67. Thanks!

**Comment by tomponline** [comment]
Hi @chuegel @haryHuds0n 

Would you mind trying to refresh to `5.21/edge` channel, this has a reverted dqlite version in it (https://github.com/canonical/dqlite/pull/641) and we would like to see if this fixes the issue for you. We've not been able to reproduce the issue locally, even using Bionic on BTRFS.

If that works you can remain on 5.21/edge until we have fixed 5.21/stable (we will let you know).

The snap revision you want is `git-d15f111`.

`sudo snap refresh lxd --channel=5.21/edge`

**Comment by chuegel** [comment]
Hi @tomponline ,
As we already copied all container to a new production server (Ubuntu 22.04 with ZFS backend), I can do the tests later this day.

**Comment by ValdikSS** [comment]
> @haryHuds0n do you also see those BTRFS related errors? Which version of Ubuntu (and kernel) are you using?

I'm not @haryHuds0n, but I was hit with this issue on Ubuntu 20.04.6 Focal, with 5.4.0-177-generic kernel. Rootfs is btrfs.
The kernel log was spammed with:

```
[9688106.385766] new mount options do not match the existing superblock, will be ignored
[9688125.318143] new mount options do not match the existing superblock, will be ignored
[9688129.778376] new mount options do not match the existing superblock, will be ignored
[9688134.244518] proc: Bad value for 'hidepid'
[9688135.519693] new mount options do not match the existing superblock, will be ignored
[9688139.266611] new mount options do not match the existing superblock, will be ignored
[9688145.013936] new mount options do not match the existing superblock, will be ignored
[9688150.900361] new mount options do not match the existing superblock, will be ignored
[9688155.654297] new mount options do not match the existing superblock, will be ignored
[9688161.267383] new mount options do not match the existing superblock, will be ignored
[9688166.514346] new mount options do not match the existing superblock, will be ignored
[9688172.289809] new mount options do not match the existing superblock, will be ignored
```

**Comment by chuegel** [comment]
Hi @tomponline,

```
snap list --all lxd core20 core22 core24 snapd
Name    Version       Rev    Tracking       Publisher   Notes
core20  20240111      2182   latest/stable  canonical✓  base,disabled
core20  20240227      2264   latest/stable  canonical✓  base
core22  20231123      1033   latest/stable  canonical✓  base,disabled
core22  20240111      1122   latest/stable  canonical✓  base
lxd     5.20-f3dd836  27049  5.21/edge      canonical✓  disabled
lxd     git-d15f111   28446  5.21/edge      canonical✓  -
snapd   2.61.2        21184  latest/stable  canonical✓  snapd,disabled
snapd   2.62          21465  latest/stable  canonical✓  snapd
```

container start just fine. No BTRFS errors logged.

**Comment by tomponline** [comment]
> container start just fine. No BTRFS errors logged.

Excellent. Good news @cole-miller , so whats the next step, do you want to keep the revert in dqlite and do a release or do you need to develop it further to address the reason it was removed in the first place?

**Comment by tomponline** [comment]
> Apr 25 22:08:17 homenuc lxd.daemon[427426]: time="2024-04-25T22:08:17+03:00" level=error msg="Failed to start the daemon" err="Failed to initialize global database: failed to ensure schema: Failed to ensure schema: not an error"

@ValdikSS please can you try doing `sudo snap refresh lxd --channel=5.21/edge` and let us know if it fixes it.

**Comment by tomponline** [comment]
The revert to dqlite has been pushed to the `5.21/stable` snap channel now.
