### ISSUE TITLE
The only AMD64 architecture images are available at LXD Image server

### ISSUE THREAD

**Issue by tregubovav-dev** [canonical/lxd#13333]
After splitting Incus and LXD project images availability have been reducing drastically, Linux Containers Community server restricts access to LXD users and LXD Image server (**images:** remote) does not provide images for non X86 platforms. This means, LXD users who uses non-X86 platforms are not able to deploy containers and VMs other than Ubuntu using **ubuntu:** remote.

Please add aarch64 and riskv64 container/vm images  to LXD Image server.

**Comment by tomponline** [comment]
We are planning arm64 image builds soon, but no plans at this time for other architectures.

**Comment by tregubovav-dev** [comment]
Thank you Tom for quick update.
arm64 is most important images for the community (as well as many enterprises uses arm64 platforms already).
I would appreciate for raw estimation, days, weeks, months ? :)

**Comment by tomponline** [comment]
We enabled them today and are ironing out the initial builds now.

**Comment by tregubovav-dev** [comment]
Thank you Tom for the confirmation. 💯 
Looking for the images availability.

**Comment by MusicDin** [comment]
We have added arm64 container images for majority of distributions. There is more to come.
https://images.lxd.canonical.com/

**Comment by tregubovav-dev** [comment]
Great job folks!

**Comment by MusicDin** [comment]
Maybe the page is cached. Try hard refreshing. I can see them on the page.

**Comment by tregubovav-dev** [comment]
Thank you Din for a quick check.
However, I sill do see only the amd64 images on the page.

It might relay to Canonical DNS configuration or load balancing.

My system resolves images.lxd.canonical.com as:
```
$host images.lxd.canonical.com
images.lxd.canonical.com has address 185.125.189.121
images.lxd.canonical.com has IPv6 address 2620:2d:4000:100c::147
```
The browser and curl provide the similar content on my system which consists of amd64 images.

quick check with curl:

```
$ curl https://images.lxd.canonical.com/ | grep amd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                    <td>amd64</td>
                    <td class="text-end"><a href="/images/almalinux/8/amd64/cloud/20240419_0010">2024-04-19 (00:10)</a></td>
                    <td>amd64</td>
                    <td class="text-end"><a href="/images/almalinux/8/amd64/default/20240419_0010">2024-04-19 (00:10)</a></td>
                    <td>amd64</td>
                    <td class="text-end"><a href="/images/almalinux/9/amd64/cloud/20240419_0010">2024-04-19 (00:10)</a></td>
...
```

```
$ curl https://images.lxd.canonical.com/ | grep aarch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79475  100 79475    0     0   102k      0 --:--:-- --:--:-- --:--:--  102k

```

**Comment by MusicDin** [comment]
ARM images are tagged as `arm64` not `aarch`, so this should be why you can't grep them.

**Comment by tregubovav-dev** [comment]
> ARM images are tagged as `arm64` not `aarch`, so this should be why you can't grep them.

Sorry, these are my fogged eyes :)

**Comment by MusicDin** [comment]
I'm closing this issue as all currently expected container images for arm64 are available. We are expecting to add VM images once we can properly test them, but currently arm64 runners do not support nested virtualization, therefore, we cannot guarantee that published images work.
