### ISSUE TITLE
Can lxd bridge create logical L2 subnet across L3 switches?

### ISSUE THREAD

**Issue by sl901744** [canonical/lxd#13340]
My lxd cluster physical hosts are in different L3 switches, there’re 2 vms: vmA (on hostA) and vmB (on hostB):

vmA and vmB are in same subnet (xxx/24), but their hosts (hostA & hostB) are in different L3 switches with different subnet address.

I found vmA and vmB cannot ping each other, by tcpdump and ip neigh, I found it cannot find ARP mac address.

Each cases other than the above are fine if:
vmA & vmB are in different lxd bridge subnet (although host across L3)
vmA & vmB are in the same lxdbr subnet (but their hosts are in the same L3 switch set)

I want to know the reason, can anyone help me? This has been bothering me for a long time.
Did I miss lxd bridge configs? (bgp configured)
Does bridge type network not support logical L2 across physical L3?
Is ovn type network required for this case?

Any help or tips are greatly appreciated!

**Comment by tomponline** [comment]
> Is ovn type network required for this case?

Yes if you want to span a LXD managed network across cluster members you should use `ovn` or `bridge` in fan mode.

https://documentation.ubuntu.com/lxd/en/latest/howto/network_ovn_setup/
https://documentation.ubuntu.com/lxd/en/latest/explanation/networks/#recommendations

We have a forum for support discussions here https://discourse.ubuntu.com/c/lxd/support/149

Thanks

**Comment by sl901744** [comment]
> > Is ovn type network required for this case?
> 
> Yes if you want to span a LXD managed network across cluster members you should use `ovn` or `bridge` in fan mode.
> 
> https://documentation.ubuntu.com/lxd/en/latest/howto/network_ovn_setup/ https://documentation.ubuntu.com/lxd/en/latest/explanation/networks/#recommendations
> 
> We have a forum for support discussions here https://discourse.ubuntu.com/c/lxd/support/149
> 
> Thanks

Thank you, I don't want to use ovn because some unstable incident occured on it. Just want to confirm that only bridge can also work.

Thanks for the share of forum, actually I post a topic here but nobody notice it:
https://discuss.linuxcontainers.org/t/can-lxd-bridge-create-logical-l2-subnet-across-l3-switches/19625

**Comment by tomponline** [comment]
> Thanks for the share of forum, actually I post a topic here but nobody notice it:

That isn't the LXD forum. The LXD forum is here https://discourse.ubuntu.com/c/lxd/support/149
