### ISSUE TITLE
images: CentOS 7 and Stream9

### ISSUE THREAD

**Issue by MusicDin** [canonical/lxd#13351]
CentOS (7 and Stream9) daily builds are unstable. They are occasionally failing the VM tests because they do not boot get ready withing a predetermined timeout of 3 minutes. When the build succeeds, VM is created and ready well under a minute (which is default timeout for all other images) but it seems that VMs get sometime stuck while booting and reach the timeout of 3 minutes.

Needs investigation.

**Comment by simondeziel** [comment]
> CentOS (7 and Stream9) daily builds are unstable.

I wouldn't care too much about CentOS 7 as it goes EOL on June 30th 2024 so only ~2 months left.

**Comment by simondeziel** [comment]
Things seem to have improved lately. There were 10 successful builds of Stream9. The last one to fail was because the cloud variant was too slow to boot which I think we could attribute to a slow runner.

With CentOS 7 going EOL in 11 days, I think we can close this one.
