### ISSUE TITLE
lxd recover error, Instance in project "default" has no volume information in its backup file

### ISSUE THREAD

**Issue by amir5142** [canonical/lxd#13369]
After the automatic update of LXD to version 5.21.1 and the requirement for the new version of ZFS and a new kernel, I had to upgrade my operating system from Ubuntu 20.04 to Ubuntu 22.04. After this procedure on two servers and executing the command lxd recover, the issue was resolved, and access to the virtual machines was restored. However, on another server, I encountered the following error: (the servers were separate and not clustered)

`Error: Failed validation request: Failed checking volumes on pool "StoragePool1": Failed parsing backup file "/var/snap/lxd/common/lxd/storage-pools/StoragePool1/virtual-machines/vm-78/backup.yaml": open /var/snap/lxd/common/lxd/storage-pools/StoragePool1/virtual-machines/vm-78/backup.yaml: no such file or directory`

After research, I realized that vm-78, which I had deleted a long time ago, was not properly removed, and two parts of it remained in the output of zfs list | grep vm-78:

```
zfs list | grep vm-78
StoragePool1/virtual-machines/vm-78                                                        56K  99.9M      112K  legacy
StoragePool1/virtual-machines/vm-78.block                                                   8K  5.95T     1.55G  -
```

I attempted to create the backup.yaml file similar to other instances by mounting it with the following command:
`mount -t zfs StoragePool1/virtual-machines/vm-78 /mnt/StoragePool1`
However, this time I encountered the following error. What should I do?

```
lxd recover
This LXD server currently has the following storage pools:
Would you like to recover another storage pool? (yes/no) [default=no]: yes
Name of the storage pool: StoragePool1
Name of the storage backend (ceph, cephfs, cephobject, dir, lvm, powerflex, zfs, btrfs): zfs
Source of the storage pool (block device, volume group, dataset, path, ... as applicable): /dev/mapper/lxc--storage--pool--vg-lxc--storage--pool--lv
Additional storage pool configuration property (KEY=VALUE, empty when done):
Would you like to recover another storage pool? (yes/no) [default=no]:
The recovery process will be scanning the following storage pools:
 - NEW: "StoragePool1" (backend="zfs", source="/dev/mapper/lxc--storage--pool--vg-lxc--storage--pool--lv")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]:
Scanning for unknown volumes...
Error: Failed validation request: Failed checking volumes on pool "StoragePool1": Instance "vm-78" in project "default" has no volume information in its backup file
```
# Required information
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240111        2182   latest/stable  canonical✓  base,disabled
core20  20240227        2264   latest/stable  canonical✓  base
core22  20231123        1033   latest/stable  canonical✓  base,disabled
core22  20240111        1122   latest/stable  canonical✓  base
lxd     5.21.1-f9da96a  28269  5.21/stable    canonical✓  disabled
lxd     5.21.1-98dad8f  28323  5.21/stable    canonical✓  -
snapd   2.61.2          21184  latest/stable  canonical✓  snapd,disabled
snapd   2.62            21465  latest/stable  canonical✓  snapd
Description:    Ubuntu 22.04.4 LTS / 5.15.0-105-generic

**Comment by tomponline** [comment]
Have you tried removing those ZFS datasets related to the partially removed VM?

**Comment by amir5142** [comment]
> Have you tried removing those ZFS datasets related to the partially removed VM?

Thank you, for completely remove the vm-78, I executed the following command:
`zfs destroy -r StoragePool1/virtual-machines/vm-78 & zfs destroy -r StoragePool1/virtual-machines/vm-78.block `
after that i ran the `lxd recover` command again. all the machines came back to life without any problems.
