### ISSUE TITLE
Potentially redundant entity types for permissions

### ISSUE THREAD

**Issue by mas-who** [canonical/lxd#13372]
# Required information

- Distribution: 5.21 LTS
- Distribution version: snap

# Issue description

Currently in lxd the `identity` and `certificate` entity type from the authorisation model may relate to the same entities. An `identity` entity refers to oidc and tls entities and a `certificate` entity refers to tls entities only. Therefore, certificate entities is a subset of identity entities. Permissions can be created for both entity types currently, but ideally we should consider combining both entity types in the authorisation model to minimise the possibility of conflicting permissions.

**Comment by tomponline** [comment]
@markylaing what's your thoughts on this one?

**Comment by markylaing** [comment]
I agree completely. We should remove `certificates` from the model and use identities, this is an oversight on my part.

To do this, I think we can patch the `permissions` table to change any `certificate` entity types and change the auth logic in the certificates API.

**Comment by markylaing** [comment]
> I agree completely. We should remove `certificates` from the model and use identities, this is an oversight on my part.
> 
> To do this, I think we can patch the `permissions` table to change any `certificate` entity types and change the auth logic in the certificates API.

By "change" I mean replace the `certificate` entity type code with the `identity` entity type code. When we regenerate code from the OpenFGA model it should no longer be possible to create permissions on certificates.
