### ISSUE TITLE
Ubuntu Desktop images and systemd-networkd  (from images.lxd.canonical.com)

### ISSUE THREAD

**Issue by daniloegea** [canonical/lxd#13387]
Sorry if this is not the best place to start this conversation (but images.lxd.canonical.com told me to open an issue here).

# Issue description

Due to changes in how networkd-wait-online deals with interfaces, wait-online started to block during boot when there is no interfaces to wait for. See https://bugs.launchpad.net/netplan/+bug/2060311

The Ubuntu Desktop images from images.lxd.canonical.com used by LXD have the networkd service enabled by default, even though Network Manager is the default network manager ( :thinking: ?) for desktop images.

This is not a problem on Mantic, but on Noble networkd-wait-online is blocking for 2 minutes (twice actually).

Ubuntu Desktop doesn't enable networkd by default, so here's my question: should it be disabled on these images too?

# Steps to reproduce

 1. Launch a Mantic Desktop VM

`lxc launch images:ubuntu/mantic/desktop mantic-desktop --vm -c limits.cpu=2 -c limits.memory=4GiB --console=vga`

2. Upgrade to Noble and restart.

3. Wait 4 extra minutes while networkd-wait-online holds the boot twice...

4. Disable networkd and restart again. Check that networkd-wait-online will not block anymore.

**Comment by tomponline** [comment]
Please can you take a look at this @simondeziel ?

**Comment by MusicDin** [comment]
Hi, we are aware of this issue and are looking into it. Seems that it is related to default netplan configuration in Noble: https://bugs.launchpad.net/subiquity/+bug/2063331

**Comment by tomponline** [comment]
> Hi, we are aware of this issue and are looking into it. Seems that it is related to default netplan configuration in Noble: https://bugs.launchpad.net/subiquity/+bug/2063331

Do we have an existing GH issue for this?

**Comment by MusicDin** [comment]
> Do we have an existing GH issue for this?

No (besides this one). We are actively working on this and should be resolved asap.

**Comment by tomponline** [comment]
OK will leave this open then so we can track the outstanding issues with images
