### ISSUE TITLE
Fallback to QEMU software emulation if no KVM

### ISSUE THREAD

**Issue by liyafe1997** [canonical/lxd#13393]
I see LXD actually is using qemu & kvm for the VM containers, but now it required KVM. Is it possible to use pure qemu software emulation when KVM/Hardware Virtualization not avaliable?

**Comment by simondeziel** [comment]
No, hardware support for virtualization is a hard requirement. Out of curiosity, what host CPU/arch do you have that doesn't support KVM? I'm asking because on x86_64, this has been supported in CPUs since 2005 (Intel VT) and 2006 (AMD-V) according to wikipedia.

**Comment by liyafe1997** [comment]
> No, hardware support for virtualization is a hard requirement. Out of curiosity, what host CPU/arch do you have that doesn't support KVM? I'm asking because on x86_64, this has been supported in CPUs since 2005 (Intel VT) and 2006 (AMD-V) according to wikipedia.

For example, the host already running in an VM :)

**Comment by tomponline** [comment]
> For example, the host already running in an VM :)

Nested VMs are possible if the host and guest are running sufficiently newer kernels on amd64 (Ubuntu Jammy and upwards I believe). We use it for our LXD VM testing on Github runners for example :)

**Comment by liyafe1997** [comment]
> > For example, the host already running in an VM :)
> 
> Nested VMs are possible if the host and guest are running sufficiently newer kernels on amd64 (Ubuntu Jammy and upwards I believe). We use it for our LXD VM testing on Github runners for example :)


This is a little bit off topic I guess :)

We should discuss about why we should force checking KVM support, is it there any technical limitations if we use software emulation, as my understanding they are all running based on QEMU.

**Comment by tomponline** [comment]
> > > For example, the host already running in an VM :)
> > 
> > 
> > Nested VMs are possible if the host and guest are running sufficiently newer kernels on amd64 (Ubuntu Jammy and upwards I believe). We use it for our LXD VM testing on Github runners for example :)
> 
> This is a little bit off topic I guess :)
> 
> We should discuss about why we should force checking KVM support, is it there any technical limitations if we use software emulation, as my understanding they are all running based on QEMU.

Its a product design choice to only support hardware virtualisation.

**Comment by simondeziel** [comment]
@liyafe1997 QEMU upstream is clear about the different security guaranties (or absence thereof) when emulation is used.

https://www.qemu.org/docs/master/system/security.html#non-virtualization-use-case:
> Bugs affecting the non-virtualization use case are not considered security bugs at this time. Users with non-virtualization use cases must not rely on QEMU to provide guest isolation or any security guarantees.
