### ISSUE TITLE
docs: improve quick tutorial experience

### ISSUE THREAD

**Issue by boukendesho** [canonical/lxd#13400]
*Please describe the question or issue you're facing with "First steps with LXD".*

In this section, tutorial suggest run lxd init --minimal at last.

> 3. Enter the following command to initialize LXD:
> `lxd init --minimal`

But in desktop environment, this actually dont work.
It will return
`Error: Failed to connect to local LXD: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied`

I guess its a desktop specific problem. 
In desktop, user's group wouldn't change during a login session.
So the new group **lxd** not attach to our current normal user until we log out and login again.

But luckly, we have this useful command **newgrp** , it can let us change the current group ID during a login session.

So i suggest adding one more step before we run lxd init. like:
3. add your user to the `lxd` group instantly
`newgrp lxd`

---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/tutorial/first_steps/*

**Comment by tomponline** [comment]
Fixed by https://github.com/canonical/lxd/pull/13382
