### ISSUE TITLE
Missing snap plug/interface for LXD to receive MicroOVN logs

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13426]
While LXD can [receive logs from OVN](https://documentation.ubuntu.com/lxd/en/latest/howto/network_ovn_setup/#send-ovn-logs-to-lxd), we are missing an easy way to get MicroOVN logs. On the MicroOVN side, all I could find is for [local log files](https://canonical-microovn.readthedocs-hosted.com/en/latest/how-to/logs/).

Looking at the interfaces on both sides, it seems we are missing an `ovn-logs` one:

```
# snap connections lxd | grep ovn
content[ovn-certificates]  lxd:ovn-certificates  microovn:ovn-certificates  -
content[ovn-chassis]       lxd:ovn-chassis       microovn:ovn-chassis       -

# snap connections microovn | grep lxd
content[ovn-certificates]  lxd:ovn-certificates          microovn:ovn-certificates  -
content[ovn-chassis]       lxd:ovn-chassis               microovn:ovn-chassis       -
```

I think this (eventual) interface should only be manually connected as we would not want to always receive OVN logs. On the LXD side, this should also be conditional to having `core.syslog_socket=true`.

This would be a joint effort with the MicroOVN team.

**Comment by tomponline** [comment]
@simondeziel is this related to https://github.com/canonical/lxd/issues/12836 ? 

If so can we close one/other and combine the info?

**Comment by simondeziel** [comment]
Thanks for finding this dup. I'm gonna close this one now that I added the gist of the interface idea to #12836.
