### ISSUE TITLE
OVN Failed deleting forward - ... Use a UUID

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/lxd#13462]
# Required information

 * Distribution: Ubuntu 22.04
 * Distribution version: 
 * The output of "snap list --all lxd core20 core22 core24 snapd":
snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240111        2182   latest/stable  canonical✓  base,disabled
core20  20240227        2264   latest/stable  canonical✓  base
core22  20240111        1122   latest/stable  canonical✓  base,disabled
core22  20240408        1380   latest/stable  canonical✓  base
lxd     5.21.1-10f4115  28322  latest/stable  canonical✓  in-cohort,held
snapd   2.61.2          21184  latest/stable  canonical✓  snapd,held
snapd   2.62            21465  latest/stable  canonical✓  snapd,disabled,held

 * The output of "lxc info" or if that fails:
   * Kernel version:
 uname -r
5.15.0-102-generic
   * LXC version: see above
   * LXD version: see above
   * Storage backend in use: ceph via microceph

# Issue description

A network forward created on a VM port fails to delete

OVN Output
```
sudo microovn.ovn-nbctl --timeout=10 --db ssl:xxx.xxx.xxx.15:6641,ssl:xxx.xxx.xxx.16:6641,ssl:xxx.xxx.xxx.17:6641 list load_balancer
_uuid               : ac2285f0-ad85-4dbe-8748-9953af4498e0
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net26-lb-1xxx.xxx.xxx.100-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"1xxx.xxx.xxx.100:443"="xxx.xxx.xxx.2:443"}

_uuid               : bc1a56d4-701a-4651-a507-a2ad670925d0
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net26-lb-1xxx.xxx.xxx.100-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"1xxx.xxx.xxx.100:22"="xxx.xxx.xxx.2:22"}

_uuid               : 3297ff2e-d7fa-43bd-9985-27a14ad3d3cf
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net18-lb-xxx.xxx.xxx.197-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"xxx.xxx.xxx.197"="xxx.xxx.xxx.4"}

_uuid               : 6db07dcb-a5d7-4385-ab25-3f866f561437
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net2-lb-xxx.xxx.xxx.201-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"xxx.xxx.xxx.201"="10.223.115.6"}

_uuid               : 4eb503af-b0ff-447d-b4c7-f760084c892a
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net26-lb-1xxx.xxx.xxx.105-tcp
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"1xxx.xxx.xxx.105"="xxx.xxx.xxx.2"}
````

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
```
lxc network forward delete ovn_NetworkMgmt 10.205.16.100
Error: Failed deleting forward: Failed deleting OVN r: Failed to run: ovn-nbctl --timeout=10 --db ssl:10.205.20.15:6641,ssl:10.205.20.16:6641,ssl:10.205.20.17:6641 -c /proc/self/fd/3 -p /proc/self/fd/4 -C /proc/self/fd/5 --wait=sb --if-exists lb-del lxd-net26-lb-10.205.16.100-tcp -- lb-del lxd-net26-lb-10.205.16.100-udp: exit status 1 (ovn-nbctl: Multiple load balancers named 'lxd-net26-lb-10.205.16.100-tcp'.  Use a UUID.)
```

**Comment by tomponline** [comment]
Ive not been able to reproduce this issue without manually creating the additional record in the ovn db.

Normally the ovn-nbctl lb-add command will modify the existing record if already existing. However in this case a new record with same name has been created.

However we can change the way LXD deletes these records to handle this situation.

**Comment by tomponline** [comment]
In the meantime you can remove any problematic OVN load balancer entries using the following commands:

```
# List existing load balancers and find records that have the name being removed, identity the UUID of those record(s).
ovn-nbctl find load_balancer

# Remove each record using
ovn-nbctl destroy load_balancer <uuid>
```

**Comment by FrancescoDeSimone** [comment]
@tomponline thanks, I manage to remove the ovn load balancer. 

Further information about this issue: when this problem happen the forwards route are not working properly
