### ISSUE TITLE
Arch Linux reported architecture and metadata.yaml contradict

### ISSUE THREAD

**Issue by fireflowerr** [canonical/lxd#13472]
# Required information

 * Distribution: Arch Linux 
 * Distribution version: current/arm64 (2024-05-06 (00:06))
 * The output of "snap list --all lxd core20 core22 core24 snapd": not applicable
 * The output of "lxc info" or if that fails: not applicable 
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description
The image host for Arch Linux at https://images.lxd.canonical.com/ is reported to be both aarch64 and arm64. On the site UI the image is listed as being an arm64 image. Decompressing the lxd.tar.xz archive associated with the image and inspecting metadata.yaml reveals the architecture is defined as aarch64. Using lxc image list on the remote reports the same result. 

I had used a previous version of this image as arm64.  Trying to use the current version reported that my host architecture is incompatabile which led me to this issue. 

# Steps to reproduce

 1. Inspect listing for Arch Linux at https://images.lxd.canonical.com/ , note architecture is reported as arm64
 2. Inspect metadata.yaml of the lxd.tar.xz associated with the image, note architecture is reported as aarch64

# Information to attach

 - [Link](https://images.lxd.canonical.com/images/archlinux/current/arm64/default/20240506_0006/) to image directory at time of writing

**Comment by tomponline** [comment]
@MusicDin are you able to investigate this please?

**Comment by MusicDin** [comment]
`aarch64` and `arm64` refer to the same architecture. We use the name `arm64` on images.lxd.canonical.com and as an image label as it is more commonly used. Similar to `x86_64` and `amd64`.

```
$ lxc image ls images:archlinux -c la
+----------------------------------+--------------+
|              ALIAS               | ARCHITECTURE |
+----------------------------------+--------------+
| archlinux (5 more)               | x86_64       |
+----------------------------------+--------------+
| archlinux/arm64 (2 more)         | aarch64      |
+----------------------------------+--------------+
```

Is there an issue running that image?

**Comment by MusicDin** [comment]
The arch images should work as expected. Therefore, I will close this issue.
