### ISSUE TITLE
[lxd-ci] Debian sid and trixie fail to build

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13499]
https://github.com/canonical/lxd-ci/actions/runs/9294703886

I suspect that's due to systemd's version now including a `~` as hinted in https://github.com/lxc/incus/issues/887

This might also require https://github.com/lxc/distrobuilder/pull/850

**Comment by MusicDin** [comment]
Thanks. This has been fixed in https://github.com/canonical/lxd-imagebuilder/pull/63 and the images are uploaded (see [Build Debian image action](https://github.com/canonical/lxd-ci/actions/runs/9358895128/job/25775974273)).
