### ISSUE TITLE
Pi Zero 2 W - websocket: close 1006

### ISSUE THREAD

**Issue by snamikas** [canonical/lxd#13515]
Checking if at all possible to have Core use LXD to run Ubuntu Jammy 22.0 without getting websocket: close 1006 error?

Error: Failed instance creation: websocket: close 1006 (abnormal closure): unexpected EOF

Model: Raspberry Pi Zero 2 W
Architecture: armv7l

Ubuntu Core 22 (32-bit)

Steps to reproduce:
snap install lxd
lxd (5.21/stable) 5.21.1-d46c406 from Canonical✓ installed
getent group lxd | grep -qwF "$USER" || sudo usermod -aG lxd "$USER"
sudo lxd init --auto
sudo lxc launch ubuntu:22.04 jammy

then the close 1006 error happens consistently on every try.

thank-you,

**Comment by tomponline** [comment]
What do the LXD logs show?

https://documentation.ubuntu.com/lxd/en/latest/howto/instances_troubleshoot/#how-to-troubleshoot-failing-instances

**Comment by snamikas** [comment]
not much detail for these first two logs,

1) lxc info jammy --show-log
Name: jammy
Status: STOPPED
Type: container
Architecture: armv7l
Created: 2024/06/03 21:07 UTC
Log:

2) lxc console jammy --show-log
Error: open /var/snap/lxd/common/lxd/logs/jammy/console.log: no such file or directory

3) sudo lxd.buginfo (attached as lxd.buginfo-1.txt)
[lxd.buginfo-1.txt](https://github.com/user-attachments/files/15743576/lxd.buginfo-1.txt)
more detail here, which could be that I'm requesting the wrong architecture of the image (maybe, not sure),
sudo lxc launch ubuntu:22.04 jammy

```
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+-----------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 | ARCHITECTURE |   TYPE    |   SIZE    |         UPLOAD DATE         |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+-----------------------------+
|       | 78ee5723f34f | no     | ubuntu 22.04 LTS armhf (release) (20240514) | armv7l       | CONTAINER | 353.82MiB | Jun 7, 2024 at 5:32pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+-----------------------------+
```
