### ISSUE TITLE
Replace `square/go-jose` by `go-jose/go-jose`

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13526]
`square/go-jose.v2` is affected by https://github.com/canonical/lxd/security/dependabot/13 and the module is deprecated and superseded/replaced by `go-jose/go-jose`:

https://github.com/square/go-jose?tab=readme-ov-file:
> Go JOSE v1/v2 (DEPRECATED)
> Development of Go JOSE has continued in a [new organization](https://github.com/go-jose):
> 
> https://github.com/go-jose/go-jose

We already depend on `github.com/go-jose/go-jose/v4` for LXD and `github.com/go-jose/go-jose/v3` for the `mini-oidc`.

Ideally, we'd probably settle on `github.com/go-jose/go-jose/v4` for all.

**Comment by MusicDin** [comment]
This deprecated dependency is from `zitadel/oidc`.

```sh
$ go mod why -m gopkg.in/square/go-jose.v2
# gopkg.in/square/go-jose.v2
github.com/canonical/lxd/client
github.com/zitadel/oidc/v2/pkg/client/rp
gopkg.in/square/go-jose.v2
```

Is there any blocker that prevents us from moving to `zitadel/oidc/v3`?

**Comment by markylaing** [comment]
> Is there any blocker that prevents us from moving to `zitadel/oidc/v3`?

This is on my to-do list for this pulse :smiley:

**Comment by simondeziel** [comment]
https://github.com/canonical/lxd/pull/13566 is a temporary fix for the security issue but it would be nice to keep this issue around until a proper fix lands.

**Comment by tomponline** [comment]
@markylaing @simondeziel did this get completed by https://github.com/canonical/lxd/pull/13602 ?

**Comment by MusicDin** [comment]
Yes, this is done. There is no `square/go-jose` dependency anymore and security issue is also closed.
