### ISSUE TITLE
Potential duplicate QEMU device ID when using long device names

### ISSUE THREAD

**Issue by hamistao** [canonical/lxd#13597]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * snap: latest/stable
 * LXC version: 5.21.1 LTS
 * LXD version: 5.21.1 LTS

# Issue description

This is related to #13596.
If a QEMU device name is too long, QEMU will trim it down to 64 characters. For LXD, this means that two devices named "{long_name}1" and "{long_name}2"  may end up with the same QEMU device ID `dev-lxd_{trimmed_long_name}`, which will result in the VM failing to start.

# Steps to reproduce
 1. `LONG_DEVICE_NAME="device-with-very-long-name-for-long-qemu-property-handling-test"`
 2. `mkdir -p $HOME/device-test && mkdir -p $HOME/device-test && lxc init ubuntu:n vm --vm`
 4. `lxc config device add v2 "${LONG_DEVICE_NAME}1" pci address=01:00.0 # Requires having an available PCI device.`
 5. `lxc config device add v2 "${LONG_DEVICE_NAME}2" pci address=02:00.0`
 6. `lxc start vm`

**Comment by hamistao** [comment]
@tomponline I did not fix this in #13596 because:
1. To get the fix for the tests in faster
2. This may impact the behavior of devices that are currently working so I decided it woudl be better to take some time to decide on an approach

**Comment by tomponline** [comment]
@hamistao is this confirmed as a bug? If so please can you add the Bug label to the issue.

**Comment by hamistao** [comment]
@tomponline still to be confirmed after some recent changes that have altered the scope of this problem by improving device ID generation, but is still probably a bug

**Comment by hamistao** [comment]
Indeed the duplication happens with PCI and GPU passthrough devices only.
After some tests with Testflinger, I concluded that the device ID does not affect the device information as seen from inside the insatance and is just a reference for LXD and QEMU.
[This](https://github.com/canonical/lxd/pull/13928) PR fixes this.
