### ISSUE TITLE
`security.devlxd.images` regressed somewhere after `5.0`

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13595]
[`5.0/edge`](https://github.com/canonical/lxd-ci/actions/runs/9489218457/job/26150022823?pr=191#step:7:852) shows a super fast download indicating it was pulling from the parent LXD.
[`5.21/edge`](https://github.com/canonical/lxd-ci/actions/runs/9489218457/job/26150011226?pr=191#step:7:903) shows the image download speed to indicating a download from the Internet.
[`latest/edge`](https://github.com/canonical/lxd-ci/actions/runs/9489218457/job/26150039410?pr=191#step:7:905) shows similarly slow download indicating a download from the Internet.

The `tests/cluster` should always have `u1` image downloaded from the parent LXD as the test is using the same image for both the parent and child instances.

**Comment by MusicDin** [comment]
Is `security.devlxd` also enabled or just `security.devlxd.images`? 
The latter should not have effect if `security.devlxd` is disabled or empty.

**Comment by MusicDin** [comment]
Ignore me.. The latter has no effect only if `security.devlxd` is `false`

**Comment by markylaing** [comment]
Closed via https://github.com/canonical/lxd/pull/13730
