### ISSUE TITLE
storage pool create failure due to ext4's lost+found directory

### ISSUE THREAD

**Issue by dwbfox** [canonical/lxd#13630]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 (Jammy)
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
 snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240227        2264   latest/stable  canonical✓  base,disabled
core20  20240416        2318   latest/stable  canonical✓  base
core22  20240111        1122   latest/stable  canonical✓  base,disabled
core22  20240408        1380   latest/stable  canonical✓  base
lxd     5.21.1-98dad8f  28323  5.21/stable    canonical✓  disabled
lxd     5.21.1-d46c406  28460  5.21/stable    canonical✓  -
snapd   2.62            21465  latest/stable  canonical✓  snapd,disabled
snapd   2.63            21759  latest/stable  canonical✓  snapd
```
 * The output of "lxc info" or if that fails:
 https://paste.ubuntu.com/p/mK7FsqdP5R/

# Issue description

When an empty ext4 filesystem is created, normally it creates 
a special `lost+found` directory to put broken/recovered data when `fsck` is run.

However, LXD seems to see this file and treat it as a `used` directory, hence
storage creation attempts appear to fail
```
➜  ~ ls -la /iscsistore
drwx------  2 root root 16384 Jun 17 15:48 lost+found

➜  ~ lxc storage create iscsistore dir source=/iscsistore
Error: Source path '/var/lib/snapd/hostfs/iscsistore' isn't empty
```

# Steps to reproduce

 1. Create an empty ext4 filesystem (`mkfs.ext4 /dev/<device>`) and mount it.
 2. Create a `dir` pool on the mount: `lxc storage create iscsistore dir source=/iscsistore`
 3. Observe failure

While one can remove the lost+found directory, it is still a documented function of the filesystem and thus something LXD should be able to be aware of or otherwise ignore.

**Comment by MusicDin** [comment]
Thanks for opening an issue and the reproducer.

The `dir` storage pool expects an empty directory to prevent potential overwrite or removal of user's content. This can be mitigated by creating a subdirectory that is used as source. However, if the entire device is being used, what is the reason for using plain directory storage pool?

---

Quick reproducer with loopback device:
```
$ mkdir ~/tmp
$ dd if=/dev/zero of=~/tmp/disk.img bs=1G count=1
$ sudo losetup -f ~/tmp/disk.img
$ device=$(sudo losetup -a | grep ~/tmp/disk.img | cut -d: -f1)
$ sudo mkfs.ext4 $device
$ sudo mkdir /mnt/s1
$ sudo mount $device /mnt/s1

$ lxc storage create s1 dir source=/mnt/s1/dir
Error: Source path '/var/lib/snapd/hostfs/mnt/s1' isn't empty

$ sudo mkdir /mnt/s1/dir
$ lxc storage create s1 dir source=/mnt/s1/dir
```

@tomponline What do you think, should we consider `lost+found` as if the directory is empty?

**Comment by tomponline** [comment]
@MusicDin as discussed, I think as long as we confirm that the lost+found dir is at the root of the mount then we can allow it to be ignored.
