### ISSUE TITLE
Kali and Arch linux build failuers

### ISSUE THREAD

**Issue by MusicDin** [canonical/lxd#13666]
Kali and Arch Linux are not building lately.

Failed builds:
- Kali (amd64): https://github.com/canonical/lxd-ci/actions/runs/9671301225 
- Kali (arm64): https://github.com/canonical/lxd-ci/actions/runs/9637512779
- Arch (amd64): https://github.com/canonical/lxd-ci/actions/runs/9671245928

**Comment by simondeziel** [comment]
I think you fixed them in https://github.com/canonical/lxd-ci/pull/217. I triggered a build for Kali/arm64 that was missing and retried the Arch desktop image. Both are now published so thanks!
