### ISSUE TITLE
 fix(deps): update github.com/openfga/api/proto digest to f5a955a #13649 

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#13667]
fix(deps): update github.com/openfga/api/proto digest to f5a955a #13649

**Comment by tomponline** [comment]
@hamistao please can you also look at this one. Ta

**Comment by hamistao** [comment]
This is blocked until a new `openfga` version is released. See https://github.com/canonical/lxd/pull/13684#issuecomment-2210933317
