### ISSUE TITLE
Clarify the availability of optimized backups for the storage drivers

### ISSUE THREAD

**Issue by roosterfish** [canonical/lxd#13752]
Currently when viewing https://documentation.ubuntu.com/lxd/en/latest/reference/storage_drivers/ we cannot see if a specific storage driver has support for the creation of optimized backups.

We should add another row `Optimized backups` which indicates that this feature is currently only available for the `zfs` and `Btrfs` driver.

**Comment by ru-fu** [comment]
Fixed with https://github.com/canonical/lxd/pull/13745
