### ISSUE TITLE
Spelling error in instance snapshot deletion trigger name

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#13862]
See https://github.com/canonical/lxd/pull/13846#discussion_r1701870013_

We'll need a DB patch to fix this.

**Comment by tomponline** [comment]
@markylaing can @kadinsayani help with this?

**Comment by markylaing** [comment]
> @markylaing can @kadinsayani help with this?

Yes that would be great. For this, we need a patch see `lxd/patches.go` to be applied at stage `patchPreLoadClusterConfig` that deletes the `on_instance_snaphot_delete` trigger (note spelling error) if it exists. The [deletion trigger](https://github.com/canonical/lxd/blob/1e0b3535f2c0e0559205b019831bea7af1af21fb/lxd/db/cluster/entity_type_instance_snapshot.go#L43) for the `instance_snapshot` entity type needs to be updated to have the correct spelling.
