### ISSUE TITLE
Handling of project `features.*` in authorization

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#13863]
When any `features.*` are disabled on a project, entities of that type are created in the default project instead. 

Authorization checks are made with specific entity URLs. If the authorizer is not aware that the entity may not be in the project specified by the project query parameter in the URL, the authorization check may fail with a "not found" error.

I've investigated the work that is needed for this and outlined it below:
- [ ] In the embedded OpenFGA authorization driver, check for `request.CtxEffectiveProjectName` in the request context and handle appropriately.
- [ ] For `features.profiles`, the effective project is only set in the request context when listing profiles. If `features.profiles` is disabled for a project, getting/updating/deleting a single profile in that project works because the access check is using the request project. This will not work with the OpenFGA authorization driver, so we'll need to always set the effective project in the request context.
- [ ] For `features.networks` and `features.networks.zones` we have the same situation as with `features.profiles` above.
- [ ] For `features.images` we have a similar situation as with `features.profiles`, however we need to be careful to two key areas. Firstly, the process of getting the effective project is not standardised like it is for other entity types (with a function in the `lxd/project` package). Secondly, the database methods for getting/listing images are quite convoluted, and reperform this check on each call. I think we'll need to refactor a bit to simplify these methods by determining the effective project beforehand and passing it in.

I will treat each item here separately and create a PR for each.

**Comment by tomponline** [comment]
> I will treat each item here separately and create a PR for each.

Should this issue remain open as only 1 PR has closed it?

**Comment by markylaing** [comment]
> > I will treat each item here separately and create a PR for each.
> 
> Should this issue remain open as only 1 PR has closed it?

I had thought the PRs would be much larger but I've ticked all the bullets off here with the one PR.
