### ISSUE TITLE
Token can be created with name `--help`

### ISSUE THREAD

**Issue by MusicDin** [canonical/lxd#13887]
I've accidentally created a token with name `--help`, but I cannot remove it using `lxc` because actual help message will be shown.

```
$ lxc config trust add --name --help

$ lxc config trust list-tokens
+-----------+-------+------------+
| NAME      | TOKEN | EXIPRES AT |
+-----------+-------+------------+
| --help    |  ...  |            |
+-----------+-------+------------+

$ lxc config trust revoke-token '--help'
Description:
  Revoke certificate add token

Usage:
  lxc config trust revoke-token [<remote>:] <name> [flags]

Global Flags:
      --debug          Show all debug messages
      --force-local    Force using the local unix socket
  -h, --help           Print help
      --project        Override the source project
  -q, --quiet          Don't show progress information
      --sub-commands   Use with help or --help to view sub-commands
  -v, --verbose        Show all information messages
      --version        Print version number
```

**Comment by MusicDin** [comment]
The token can be removed using `lxc config trust revoke-token -- --help`, but I still think we should prevent such names?

**Comment by kadinsayani** [comment]
Should we just disallow names including ```--help```, or any name with the prefix ```--``` or ```-```?

**Comment by kadinsayani** [comment]
Alternatively, we can disallow all names that are also command or global flags.

**Comment by tomponline** [comment]
Option 2 at least please

**Comment by kadinsayani** [comment]
The ```--help``` flag is defined as a ```PersistentFlag``` in ```lxc/main.go```, which correctly applies the help flag across all commands. However, the ```lxc``` cli uses ```Flags().StringVar()``` to accept input when the ```--name``` flag is passed, which allows any input to be accepted without validation.

I think we have two solutions here:
1. Add input validation to the ```lxc config trust add``` command; and/or
2. Add input validation on the LXD server side.
