### ISSUE TITLE
Improve remote token handling

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13891]
When trying to add a remote using a token, I got this unexpected prompt for fingerprint verification:

```bash
$ lxc remote add joliet 10.245.130.24 --token eyJjbGllbnRfbmFtZSI6InNkZXppZWwiLCJmaW5nZXJwcmludCI6IjQ2MzVlZjZkN2I0OTFlNjUxNTRiYjljYzA3MGMxZTJhMGFkYzM4NmViNGE3NGU1MWMxNzk2YmRkNDgzYmRmYWQiLCJhZGRyZXNzZXMiOlsiMTAuMS4xMC4xMDU6ODQ0MyIsIjEwLjI0NS4xMzAuMjQ6ODQ0MyIsIjEwLjY5LjIzLjE6ODQ0MyIsIltmZDQyOmE3Yzk6N2NkZjo4NGQ6OjFdOjg0NDMiXSwic2VjcmV0IjoiMGM3OWFkZTE5YjVkYTQ5YTNhMTAwNWZjMmJmOTk3Njc4MjFjZTg3MWI4NTgwOWE0ZGU4NjYxZGZjMDgwMjg4ZiIsImV4cGlyZXNfYXQiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9
Certificate fingerprint: 4635ef6d7b491e65154bb9cc070c1e2a0adc386eb4a74e51c1796bdd483bdfad
ok (y/n/[fingerprint])? n
Error: Server certificate NACKed by user
```

The token embeds the fingerprint so why ask for verification?

```bash
$ base64 -d <<< 'eyJjbGllbnRfbmFtZSI6InNkZXppZWwiLCJmaW5nZXJwcmludCI6IjQ2MzVlZjZkN2I0OTFlNjUxNTRiYjljYzA3MGMxZTJhMGFkYzM4NmViNGE3NGU1MWMxNzk2YmRkNDgzYmRmYWQiLCJhZGRyZXNzZXMiOlsiMTAuMS4xMC4xMDU6ODQ0MyIsIjEwLjI0NS4xMzAuMjQ6ODQ0MyIsIjEwLjY5LjIzLjE6ODQ0MyIsIltmZDQyOmE3Yzk6N2NkZjo4NGQ6OjFdOjg0NDMiXSwic2VjcmV0IjoiMGM3OWFkZTE5YjVkYTQ5YTNhMTAwNWZjMmJmOTk3Njc4MjFjZTg3MWI4NTgwOWE0ZGU4NjYxZGZjMDgwMjg4ZiIsImV4cGlyZXNfYXQiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9' | jq -r
{
  "client_name": "sdeziel",
  "fingerprint": "4635ef6d7b491e65154bb9cc070c1e2a0adc386eb4a74e51c1796bdd483bdfad",
  "addresses": [
    "10.1.10.105:8443",
    "10.245.130.24:8443",
    "10.69.23.1:8443",
    "[fd42:a7c9:7cdf:84d::1]:8443"
  ],
  "secret": "0c79ade19b5da49a3a1005fc2bf99767821ce871b85809a4de8661dfc080288f",
  "expires_at": "0001-01-01T00:00:00Z"
}
```

Also, the IP address needs to be provided despite being one of the `addresses`. Here's what happens if the IP isn't provided when adding the remote:

```
$ lxc remote add joliet --token eyJjbGllbnRfbmFtZSI6InNkZXppZWwiLCJmaW5nZXJwcmludCI6IjQ2MzVlZjZkN2I0OTFlNjUxNTRiYjljYzA3MGMxZTJhMGFkYzM4NmViNGE3NGU1MWMxNzk2YmRkNDgzYmRmYWQiLCJhZGRyZXNzZXMiOlsiMTAuMS4xMC4xMDU6ODQ0MyIsIjEwLjI0NS4xMzAuMjQ6ODQ0MyIsIjEwLjY5LjIzLjE6ODQ0MyIsIltmZDQyOmE3Yzk6N2NkZjo4NGQ6OjFdOjg0NDMiXSwic2VjcmV0IjoiMGM3OWFkZTE5YjVkYTQ5YTNhMTAwNWZjMmJmOTk3Njc4MjFjZTg3MWI4NTgwOWE0ZGU4NjYxZGZjMDgwMjg4ZiIsImV4cGlyZXNfYXQiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9
Error: Get "https://joliet:8443": lookup joliet on 127.0.0.53:53: server misbehaving
```

IMHO, all addresses should be tried in parallel or in quick succession.

**Comment by tomponline** [comment]
Agree, it would need to be sequential not parallel/concurrent though as the token is single use.

**Comment by Regis-Caelum** [comment]
Hey @tomponline , I want to work on this issue and learn the code through it. So far, I understand that it shouldn't prompt for fingerprint verification since the token already embeds the fingerprint.
https://github.com/canonical/lxd/blob/96043b1ad3e5c61092b30977ae7344fd90793f0b/lxc/remote.go#L321-L324
https://github.com/canonical/lxd/blob/96043b1ad3e5c61092b30977ae7344fd90793f0b/shared/cert.go#L507-L511
I looked at the code and found that remote addr is being passed to the CertificateTokenDecode func, which then tries to decode it but gets `llegal base64 data at input...` err. please correct me if I've misunderstood. :)

**Comment by markylaing** [comment]
@Regis-Caelum Yes that's where the CLI would process a token if the command were invoked like `lxc remote add <name> <token>`. However in this case the `--token` flag is being passed in. I think this can be fixed by adding an additional check just after this line:
```go
if c.flagToken != "" {
    rawToken, err := shared.CertificateTokenDecode(c.flagToken)
    if err != nil {
        // Return the error here rather than skipping as we did in the previous case, as the token has been explicitly provided.
        return fmt.Errorf("Failed to parse token: %w", err)
    }

    return c.runToken(server, c.flagToken, rawToken)
}
```

@roosterfish IIRC you implemented the explicit trust token logic, does this sound correct?

**Comment by roosterfish** [comment]
> @roosterfish IIRC you implemented the explicit trust token logic, does this sound correct?

Yes you can either provide the token directly as a positional argument or via the `--token` flag.
The latter allows you to specify a different `<IP|FQDN|URL>` as the ones inside the actual token. 

@simondeziel I understand the current behavior is if you don't specify the IP as a positional argument, it tries to lookup the LXD server based on the given name of the `<remote>` as you have shown in your example above.
Now if we also consider the IPs from the `--token`, how would LXD decide whether or not to pick one of the IPs or the name of the remote? 
As providing the `--token` is optional, maybe we should keep this flag dedicated for providing the "secret" (even though it still contains other information like the IP).
If you want to specify another name/IP you can use the second positional argument to do so:

`lxc remote add foo 1.2.3.4 --token ...`

**Comment by Regis-Caelum** [comment]
@markylaing, did I understand you correctly? The condition below checks for the flag first; if not, the token is in the addr, as pointed out by @roosterfish . I'm assuming that by 'positional argument', he meant that the token is in the place of 'addr'?

```go
if c.flagToken != "" {
    rawToken, err := shared.CertificateTokenDecode(c.flagToken)
    if err != nil {
        return fmt.Errorf("Failed to parse token: %w", err)
    }
    return c.runToken(server, c.flagToken, rawToken)
}

rawToken, err := shared.CertificateTokenDecode(addr)
if err == nil {
    return c.runToken(server, addr, rawToken)
}

**Comment by Regis-Caelum** [comment]
it's minor changes, should i open a pr then?

**Comment by markylaing** [comment]
> changes look minor, should i open a pr then?

Yes please! Note @roosterfish's comment that when the `--token` flag is used, it is used for specifying the secret. So if the user specifies an address as well as the `--token` flag we want to use the supplied address as the LXD remote when creating the certificate.

**Comment by Regis-Caelum** [comment]
> Yes please! Note @roosterfish's comment that when the `--token` flag is used, it is used for specifying the secret. So if the user specifies an address as well as the `--token` flag we want to use the supplied address as the LXD remote when creating the certificate.

I think i got it wrong, the prompt for fingerprint is happening here, should it just comapre the digest with token's fingerprint?
https://github.com/canonical/lxd/blob/7a07abaec6ed712f70abacaaabb27ff51a40e374/lxc/remote.go#L450-L468

**Comment by roosterfish** [comment]
@Regis-Caelum that is also my understanding. The `digest` has to match the fingerprint inside the token.

The `c.flagAcceptCert` makes me thinking. Is there ever a case where you would provide a token which doesn't contain the servers fingerprint? 
Because if not we could also think about getting rid of the `--accept` flag entirely.

I assume it had it's purpose for earlier versions of LXD that contained the trust password option.
But now it feels we don't need it anymore as you can only authenticate using a token.

**Comment by simondeziel** [comment]
> @simondeziel I understand the current behavior is if you don't specify the IP as a positional argument, it tries to lookup the LXD server based on the given name of the `<remote>` as you have shown in your example above. Now if we also consider the IPs from the `--token`, how would LXD decide whether or not to pick one of the IPs or the name of the remote?

The name of the remote is a short name (no `.`) so I wouldn't be surprised if most hostname lookup fail as it either requires a `/etc/hosts` alias of a search domain that happens to work.

While I'd keep the short name lookup logic, I'd probably use the address list as hints to send probes to, no?

I must admit I'm quite confuse as to what's the actual/current purpose of the `addresses` field in the JSON payload if not a list of "potentially reachable LXD listeners" for the new remote being added.

> As providing the `--token` is optional, maybe we should keep this flag dedicated for providing the "secret" (even though it still contains other information like the IP).

If we are to ignore some bits of the token (JSON payload), we should at the bare minimum keep and use the `fingerprint` and `secret` bits.

> If you want to specify another name/IP you can use the second positional argument to do so:
> 
> `lxc remote add foo 1.2.3.4 --token ...`

Indeed, that's the workaround I ended up using.

**Comment by roosterfish** [comment]
> While I'd keep the short name lookup logic, I'd probably use the address list as hints to send probes to, no?

Do you think the client should first do the lookup based on the given name and continue on with the IPs from the `--token` if the lookup didn't produce any results? 

> I must admit I'm quite confuse as to what's the actual/current purpose of the addresses field in the JSON payload if not a list of "potentially reachable LXD listeners" for the new remote being added.

The addresses are used for exactly this, but it depends on where the token is specified.
If you run `lxc remote add <name> <tokenWithAddresses>` then those are probed one after another until the client fiends a reachable listener. See [here](https://github.com/canonical/lxd/blob/main/lxc/remote.go#L166).

But if you specify `--token`, then either the given `<name>` has to be resolvable or you specify the address using the second positional argument `<IP|FQDN|URL|token>`. But in this case the addresses inside the token aren't considered.

**Comment by markylaing** [comment]
> The `c.flagAcceptCert` makes me thinking. Is there ever a case where you would provide a token which doesn't contain the servers fingerprint? Because if not we could also think about getting rid of the `--accept` flag entirely.
> 
> I assume it had it's purpose for earlier versions of LXD that contained the trust password option. But now it feels we don't need it anymore as you can only authenticate using a token.

@roosterfish there is still a case for `--accept-certificate`, the client's public certificate may have been added to the trust store by an administrator. In which case `lxc remote add <name> <address> --accept-certificate` should work with no prompt.

**Comment by Regis-Caelum** [comment]
```go
if !c.flagAcceptCert {
	digest := shared.CertFingerprint(certificate)
	if c.flagToken == "" {
		fmt.Printf(i18n.G("Certificate fingerprint: %s")+"\n", digest)
		fmt.Printf(i18n.G("ok (y/n/[fingerprint])?") + " ")
		line, err := shared.ReadStdin()
		if err != nil {
			return err
		}

		if string(line) != digest {
			if len(line) < 1 || strings.ToLower(string(line[0])) == i18n.G("n") {
				return fmt.Errorf(i18n.G("Server certificate NACKed by user"))
			} else if strings.ToLower(string(line[0])) != i18n.G("y") {
				return fmt.Errorf(i18n.G("Please type 'y', 'n' or the fingerprint:"))
			}
		}
	} else {
		rawToken, err = shared.CertificateTokenDecode(c.flagToken)
		if err != nil {
			return err
		}
		if digest != rawToken.Fingerprint {
			return fmt.Errorf(i18n.G("Server certificate NACKed by user"))
		}
	}
}
```
does this impl look good?

**Comment by simondeziel** [comment]
> > While I'd keep the short name lookup logic, I'd probably use the address list as hints to send probes to, no?
> 
> Do you think the client should first do the lookup based on the given name and continue on with the IPs from the `--token` if the lookup didn't produce any results?

I was surprised by the different behaviour when using the `--token` flag vs not using it but still providing a token. This `lxc remote add` command provides too much flexibility with too little builtin help IMHO ;)

> > I must admit I'm quite confuse as to what's the actual/current purpose of the addresses field in the JSON payload if not a list of "potentially reachable LXD listeners" for the new remote being added.
> 
> The addresses are used for exactly this, but it depends on where the token is specified. If you run `lxc remote add <name> <tokenWithAddresses>` then those are probed one after another until the client fiends a reachable listener. See [here](https://github.com/canonical/lxd/blob/main/lxc/remote.go#L166).
> 
> But if you specify `--token`, then either the given `<name>` has to be resolvable or you specify the address using the second positional argument `<IP|FQDN|URL|token>`. But in this case the addresses inside the token aren't considered.

I don't remember if I tried without the `--token` flag but I just checked and when you don't use it, it indeed goes on to try the addresses in the token.

This command could benefit from some more builtin documentation IMHO as there are some subtle differences in how it's invoked.

**Comment by simondeziel** [comment]
> > The `c.flagAcceptCert` makes me thinking. Is there ever a case where you would provide a token which doesn't contain the servers fingerprint? Because if not we could also think about getting rid of the `--accept` flag entirely.
> > I assume it had it's purpose for earlier versions of LXD that contained the trust password option. But now it feels we don't need it anymore as you can only authenticate using a token.
> 
> @roosterfish there is still a case for `--accept-certificate`, the client's public certificate may have been added to the trust store by an administrator. In which case `lxc remote add <name> <address> --accept-certificate` should work with no prompt.

I'm confused by this admin doing something. Are you referring to an admin having seeded the server's cert onto the client machine prior to the client consuming the token? In other words the admin in question would have pre-created `~/snap/lxd/common/config/servercerts/<rmt>.crt>`?


Either way, when token are concerned, I really don't see why `--accept-certificate` would be needed nor wanted.

My understanding of that `--accept-certificate` flag is just a shorthand for "I, as a client, don't care about MITM, just blindly accept whatever fingerprint I received". If that description is accurate, then `--accept-certificate` should be refused or at least ignored when a token is used as one of the selling point of the token is to protect against MITM.
