### ISSUE TITLE
doc: Token argument is not known in lxc remote add

### ISSUE THREAD

**Issue by jmlich** [canonical/lxd#13893]
Token argument is not known:
```
# lxc remote add name IP_address --token token
Error: unknown flag: --token
```

Token doesn't seem to be recognized when entered after prompt:
```
# lxc remote add name 172.28.1.211 --debug
DEBUG  [2024-08-08T15:24:41+02:00] Connecting to a remote LXD over HTTPS         url="https://172.28.1.211:8443"
DEBUG  [2024-08-08T15:24:41+02:00] Sending request to LXD                        etag= method=GET url="https://172.28.1.211:8443/1.0"
...
Admin password (or token) for name: 
DEBUG  [2024-08-08T15:24:47+02:00] Sending request to LXD                        etag= method=POST url="https://172.28.1.211:8443/1.0/certificates"
DEBUG  [2024-08-08T15:24:47+02:00] 
	{
		"name": "",
		"type": "client",
		"restricted": false,
		"projects": null,
		"certificate": "",
		"password": "HERE_WAS_TOKEN_I_HAVE_REMOVED_IT_MANUALY",
		"token": false
	} 
Error: Password authentication is no longer supported, please update your client
```

```
# lxc --version
5.20
```

---
Document: howto/server_expose.md

**Comment by roosterfish** [comment]
Hi @jmlich, the `--token` command line flag isn't available in your version of LXD (5.20). 

Please consider updating your version of LXD or check with `lxc remote add --help` which options are available in your specific version.

**Comment by jmlich** [comment]
I have latest and greatest version available for fedora 40 from https://copr.fedorainfracloud.org/coprs/ganto/lxc4/packages/

I have noticed same trouble for Ubuntu 24.04 users. Please consider backport this into those versions.

**Comment by tomponline** [comment]
> I have noticed same trouble for Ubuntu 24.04 users. Please consider backport this into those versions.

What does `snap list` show for those users?

**Comment by tomponline** [comment]
LXD 6.1 removed password support and switched to a dedicated token field, see https://discourse.ubuntu.com/t/lxd-6-1-has-been-released/46259#removal-of-trust-password-feature

LXD 5.21.x retains the password feature.

**Comment by tomponline** [comment]
On ubuntu 24.04 what version is the `lxc` CLI and what version is the server?

**Comment by jmlich** [comment]
I am sorry, I had wrong information. It works properly on ubuntu
