### ISSUE TITLE
“key=value” is undocumented for “lxc image import” help

### ISSUE THREAD

**Issue by adam-vest** [canonical/lxd#13936]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Any
 * The output of "snap list --all lxd core20 core22 core24 snapd":
```
:~$ snap list --all lxd core20 core22 core24 snapd
Name    Version      Rev    Tracking       Publisher   Notes
core20  20240227     2264   latest/stable  canonical✓  base,disabled
core20  20240416     2318   latest/stable  canonical✓  base
core22  20240408     1380   latest/stable  canonical✓  base,disabled
core22  20240419     1439   latest/stable  canonical✓  base
core24  20240528     423    latest/stable  canonical✓  base
lxd     6.1-c14927a  29551  latest/stable  canonical✓  disabled
lxd     6.1-4cd98ce  29727  latest/stable  canonical✓  -
snapd   2.62         21465  latest/stable  canonical✓  snapd,disabled
snapd   2.63         21759  latest/stable  canonical✓  snapd
```

# Issue description
Redirected here from [Discourse](https://discourse.ubuntu.com/t/key-value-is-undocumented-for-lxc-image-import-help/46832)!

When one runs `lxd image import --help`, the following usage is provided:
```
Usage:
  lxc image import <tarball>|<directory>|<URL> [<rootfs tarball>] [<remote>:] [key=value...] [flags]
```

The `[key=value...]` in there appears to be undocumented - either in the same help output, or in the broader [web documentation](https://documentation.ubuntu.com/lxd/en/latest/howto/images_copy/). Since its usage isn't self-explanatory, just requesting that this be documented somewhere what it's used for. Thanks!

# Steps to reproduce

 1. `lxc image import --help`

**Comment by tomponline** [comment]
@kadinsayani as you're focusing on the LXD CLI right now, please can you take a look at this one too?

**Comment by kadinsayani** [comment]
> @kadinsayani as you're focusing on the LXD CLI right now, please can you take a look at this one too?

Sure thing!
