### ISSUE TITLE
Question: how can I configure /1.0 metadata endpoint to answer with server_version to unauthenticated requests?

### ISSUE THREAD

**Issue by gchamon** [canonical/lxd#13955]
The title is pretty much self explanatory. Context for this question can be seen in this issue https://github.com/terraform-lxd/terraform-provider-lxd/issues/515

Current LXD servers I have access to are all >5.0, so I have to support versions 5.0 and 6.1

**Comment by tomponline** [comment]
@MusicDin @simondeziel do you want to discuss this issue over on the linked terraform-lxd issue rather than this duplicate?

**Comment by MusicDin** [comment]
Yes, let's discuss there.
