### ISSUE TITLE
Ability to launch armhf VMs on arm64 hosts

### ISSUE THREAD

**Issue by panlinux** [canonical/lxd#14001]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 24.04.1
 * The output of "snap list --all lxd core20 core22 core24 snapd":
```
Name    Version      Rev    Tracking       Publisher   Notes
core20  20240227     2267   latest/stable  canonical✓  base,disabled
core20  20240416     2321   latest/stable  canonical✓  base
core22  20240731     1568   latest/stable  canonical✓  base,disabled
core22  20240809     1590   latest/stable  canonical✓  base
lxd     6.1-4cd98ce  29733  latest/stable  canonical✓  disabled
lxd     6.1-efad198  29946  latest/stable  canonical✓  -
snapd   2.62         21467  latest/stable  canonical✓  snapd,disabled
snapd   2.63         21761  latest/stable  canonical✓  snapd
```
 * The output of "lxc info" or if that fails: not relevant, since this is a feature request I believe, but let me know if you still want it. It's long.

# Issue description
I would like to be able to launch armhf VMs on my arm64 host. I can launch armhf containers on that host already, but sometimes I need a VM.

Currently I get an error:
```
andreas@pi4:~$ lxc launch ubuntu-daily:jammy/armhf j-armhf-vm --vm
Creating j-armhf-vm
Starting j-armhf-vm
Error: Architecture isn't supported for virtual machines
Try `lxc info --show-log local:j-armhf-vm` for more info

andreas@pi4:~$ lxc list j-armhf-vm
+------------+---------+------+------+-----------------+-----------+
|    NAME    |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+------------+---------+------+------+-----------------+-----------+
| j-armhf-vm | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+------------+---------+------+------+-----------------+-----------+
```
A container is launched just fine:
```
andreas@pi4:~$ lxc launch ubuntu-daily:jammy/armhf j-armhf-container 
Creating j-armhf-container
Starting j-armhf-container
andreas@pi4:~$ lxc list j-armhf-container
+-------------------+---------+------+------+-----------+-----------+
|       NAME        |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+-------------------+---------+------+------+-----------+-----------+
| j-armhf-container | RUNNING |      |      | CONTAINER | 0         |
+-------------------+---------+------+------+-----------+-----------+
```
Host is a raspberry pi4 with this kernel:
```
andreas@pi4:~$ uname -a
Linux pi4 6.8.0-1010-raspi #11-Ubuntu SMP PREEMPT_DYNAMIC Thu Aug  8 23:22:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

# Steps to reproduce

 1. lxc launch ubuntu-daily:jammy/armhf j-armhf-vm --vm

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
@simondeziel I wonder if you could show @kadinsayani how to use testflinger to test a custom build with the check in question modified to pass and see if this works:

https://github.com/canonical/lxd/blob/d1e275234995a822e91de48cf3c734f1522126b2/lxd/instance/drivers/driver_qemu.go#L2040-L2077

**Comment by kadinsayani** [comment]
Please see the below code snippet and resulting output.

```
else if true || arch == osarch.ARCH_64BIT_ARMV8_LITTLE_ENDIAN {
		path, err := exec.LookPath(basePath + "qemu-system-aarch64")
		if err != nil {
			return "", "", err
		}

		return path, "pcie", nil
	}
```
```
ubuntu@ubuntu:~/canonical/lxd$ lxc launch ubuntu-daily:jammy/armhf j-armhf-vm --vm
Launching j-armhf-vm
Error: Failed instance creation: Failed to run: forklimits limit=memlock:unlimited:unlimited fd=3 -- /snap/lxd/30059/bin/qemu-system-aarch64 -S -name j-armhf-vm -uuid 4dd034b5-d6aa-4c96-a88c-daeb63670028 -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=allow,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.pid -D /var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.log -runas lxd: : exit status 1
```

I've also tried adding a check for `ARCH_32BIT_ARMV7_LITTLE_ENDIAN` - this produces the same output.

**Comment by tomponline** [comment]
Does /var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.log contain anything?

**Comment by panlinux** [comment]
In my case, the directory is empty:
```
$ sudo ls -lah /var/snap/lxd/common/lxd/logs/j-armhf-vm/
total 8.0K
drwx------  2 root root 4.0K Aug 28 19:59 .
drwx------ 14 root root 4.0K Aug 28 19:59 ..
```

**Comment by kadinsayani** [comment]
> /var/snap/lxd/common/lxd/logs/j-armhf-vm/qemu.log

Here's what I'm seeing:

```
qemu-system-aarch64: No machine specified, and there is no default
Use -machine help to list supported machines
```

**Comment by simondeziel** [comment]
@kadinsayani I think the machine type is something that ends up in the `qemu.conf` which AFAIK would be identical between an `aarch64` and a `armhf` VM. So I'd check what the `armhf` `qemu.conf` looks like and try to reason about every difference from one of `aarch64`.

**Comment by kadinsayani** [comment]
Adding a machine type in the below snippet seems to allow for instance creation:

```
func qemuMachineType(architecture int) string {
	var machineType string

	switch architecture {
	case osarch.ARCH_64BIT_INTEL_X86:
		machineType = "q35"
	case osarch.ARCH_64BIT_ARMV8_LITTLE_ENDIAN:
		machineType = "virt"
	case osarch.ARCH_32BIT_ARMV7_LITTLE_ENDIAN:
		machineType = "virt"
	case osarch.ARCH_64BIT_POWERPC_LITTLE_ENDIAN:
		machineType = "pseries"
	case osarch.ARCH_64BIT_S390_BIG_ENDIAN:
		machineType = "s390-ccw-virtio"
	}

	return machineType
}
```

```
ubuntu@ubuntu:~/canonical/lxd$ lxc launch ubuntu-daily:jammy/armhf j-armhf-container 
Launching j-armhf-container
ubuntu@ubuntu:~/canonical/lxd$ lxc ls                
+-------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
|       NAME        |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+-------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| j-armhf-container | RUNNING | 10.88.159.145 (eth0) | fd42:8255:67f4:4515:216:3eff:fed1:926f (eth0) | CONTAINER | 0         |
+-------------------+---------+----------------------+-----------------------------------------------+-----------+-----------+
```

However, I'm getting the wrong processor type:

```
ubuntu@ubuntu:~/canonical/lxd$ lxc exec j-armhf-container -- uname -p
armv8l
```

I'll look further into this.

**Comment by kadinsayani** [comment]
> @kadinsayani I think the machine type is something that ends up in the `qemu.conf` which AFAIK would be identical between an `aarch64` and a `armhf` VM. So I'd check what the `armhf` `qemu.conf` looks like and try to reason about every difference from one of `aarch64`.

Here's what the `[machine]` section of the `qemu.conf` for a `aarch64` and `armhf` vm look like respectively (with the check modified to pass):

# Machine                                                                         # Machine
[machine]                                                                          [machine]
graphics = "off"                                                                graphics = "off"
type = "virt"                                                                      accel = "kvm"
gic-version = "max"                                                         usb = "off"
accel = "kvm"                                                                      
usb = "off"   

Both machine types should be `virt`.

Interestingly, adding the checks for `ARM_32BIT` to `qemuMachineType()` seems to resolve the issue, albeit I'm not yet sure if the `qemu.conf` is correct. 

```
func qemuMachineType(architecture int) string {
	var machineType string

	switch architecture {
	case osarch.ARCH_64BIT_INTEL_X86:
		machineType = "q35"
	case osarch.ARCH_64BIT_ARMV8_LITTLE_ENDIAN :
		machineType = "virt"
	case osarch.ARCH_32BIT_ARMV7_LITTLE_ENDIAN :
		machineType = "virt"
	case osarch.ARCH_32BIT_ARMV8_LITTLE_ENDIAN :
		machineType = "virt"
	case osarch.ARCH_64BIT_POWERPC_LITTLE_ENDIAN:
		machineType = "pseries"
	case osarch.ARCH_64BIT_S390_BIG_ENDIAN:
		machineType = "s390-ccw-virtio"
	}

	return machineType
}
```

```
ubuntu@ubuntu:~/canonical/lxd$ lxc launch ubuntu-daily:jammy/armhf j-armhf-vm --vm
Launching j-armhf-vm
ubuntu@ubuntu:~/canonical/lxd$ lxc ls
+------------+---------+------+-----------------------------------------------+-----------------+-----------+
|    NAME    |  STATE  | IPV4 |                     IPV6                      |      TYPE       | SNAPSHOTS |
+------------+---------+------+-----------------------------------------------+-----------------+-----------+
| j-armhf-vm | RUNNING |      | fd42:7aca:827b:9197:216:3eff:fe85:877c (eth0) | VIRTUAL-MACHINE | 0         |
+------------+---------+------+-----------------------------------------------+-----------------+-----------+
```

Note that there are issues with using the instance created this way:

```
ubuntu@ubuntu:~/canonical/lxd$ lxc exec j-armhf-vm -- shell
Error: LXD VM agent isn't currently running
```

I'll continue investigating and see what I can find.

**Comment by kadinsayani** [comment]
> I'll continue investigating and see what I can find. I am guessing that there is an issue with identifying the supported personalities for the host architecture, and/or identifying the host architecture.

I have confirmed that the host architecture and supported personalities are correctly identified.

**Comment by simondeziel** [comment]
I think you are on the right path. That `lxc exec` not working is likely due to our config disk only having a 64 bit client binary.

**Comment by tomponline** [comment]
Use lxc console to see it booting

**Comment by simondeziel** [comment]
@kadinsayani I'll try to have the `arm64` snap include a `lxd-agent` binary built for `armhf`. This should provide some usability back to that arch that's being phased out but folks still need a way to run it.

@kadinsayani in the meantime, you can also rely on `cloud-init` to seed your SSH key into the instance:

```
config:
  cloud-init.user-data: |-
    #cloud-config
    ssh_import_id: [lp:sdeziel]
```
