### ISSUE TITLE
Allow setting `ceph.osd.pool_size` on pool creation

### ISSUE THREAD

**Issue by masnax** [canonical/lxd#14006]
At least with MicroCeph, OSD pools will default to a replication size of 3. That means if there are fewer than that many OSDs available for replication, LXD will fail to create the pool when running `lxc storage create pool ceph`. The command will block as the OSD pool will try to replicate unsuccessfully during initialization. 

In such cases (admittedly usually testing setups), it may be useful to specify `ceph.osd.pool_size` to apply as an initial argument when creating the pool. This may also be useful in the LXD test suite as well, where we need to set [`microceph.ceph config set global osd_pool_default_size 1`](https://github.com/canonical/lxd/blob/bd35d6d2cc3c550e2c1a4920f390437c398a910e/.github/workflows/tests.yml#L360) to change the default behaviour for all OSD pools in the test suite to disable replication.

Somewhat related to the MicroCloud OSD replication discussions going on, but MicroCloud would not leverage this capability in LXD because it also needs to be able to update the value when adding new cluster members, and it seems the ceph storage pool has [no update implementation either.](https://github.com/canonical/lxd/blob/bd35d6d2cc3c550e2c1a4920f390437c398a910e/lxd/storage/drivers/driver_ceph.go#L361)

**Comment by tomponline** [comment]
> Somewhat related to the MicroCloud OSD replication discussions going on, but MicroCloud would not leverage this capability in LXD because it also needs to be able to update the value when adding new cluster members, and it seems the ceph storage pool has [no update implementation either.](https://github.com/canonical/lxd/blob/bd35d6d2cc3c550e2c1a4920f390437c398a910e/lxd/storage/drivers/driver_ceph.go#L361)

@masnax wouldn't it be useful to add such capability rather than working around it in microcloud?

**Comment by masnax** [comment]
> @masnax wouldn't it be useful to add such capability

I thought there might be some reason why it's unimplemented, but if the only reason is that we haven't had a good reason yet, then yes I think implementing updates would be useful too. 

> rather than working around it in microcloud?

The approach in MicroCloud isn't exactly 1:1 with this because MicroCeph also sets some global ceph configuration (`osd_pool_default_size`, and `mon_allow_pool_size_one`) , which is beyond LXD's scope (limited to just OSD pools).

In MicroCloud, we set the replication size equal to the number of OSDs, up to 3. Beyond this point, If OSD pools have a replication factor greater than 3, we should leave them alone because it's a user configuration. But if they have a replication factor less than 3, particularly if it is 1 (no replication), these are dangerous configurations so we should try to increment the value once we see (from MicroCeph) that we have enough OSDs to support it. 

 initially thought we should make the size setting in MicroCloud limited to just LXD storage pool OSD pools but I'm having doubts about that now. If we have support for replication, then we should try to enable it for all pools, rather than just the LXD pools.

However, we need to be able to query the _current size_ of these pools to skip OSD pools that have been manually increased _above_ MicroCloud/MicroCeph's recommendations. 

So LXD doesn't cover all the use cases:
* It only exposes a subset of OSD pools which it knows about
* Its OSD pool size values may be out of date
