### ISSUE TITLE
Not able to persist a `description` field when creating a new storage volume snapshot

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/lxd#14011]
The `Description` field from `api.StorageVolumeSnapshotPut` is not used (when creating a storage volume snapshot from a YAML config in the CLI ) by `api.StorageVolumeSnapshotsPost`, which does not contain a `Description` field. This leads to the fact that when a volume snapshot is being taken, the created volume entry in the DB uses the description of the parent volume and not the description  of the snapshot. Do we want to fix this or is it not a bug?

**Comment by tomponline** [comment]
Yes I think its a bug. We likely need to add a new field to `api.StorageVolumeSnapshotsPost`

@MusicDin please could you remind me of the PR you worked on last year to separate some of the Post and Put structs so the former didn't embed the latter, I would like to refresh myself on that discussion. Ta

**Comment by MusicDin** [comment]
Here: https://github.com/canonical/lxd/pull/13035

**Comment by gabrielmougard** [comment]
@MusicDin @tomponline #14016 should solve that
