### ISSUE TITLE
Executing with docker commands in lxc is very slow

### ISSUE THREAD

**Issue by lwh504530121** [canonical/lxd#14177]
The execution of other commands such as docker command and DOCKER COPY in lxc is very slow. The storage pool currently used is zfs. How can I troubleshoot the problem? I think using docker on another computer with the same configuration is fine, but the storage pool type is dir. As long as it is a zfs storage pool type of several computers have the same situation. lxd version 3.0.3

**Comment by simondeziel** [comment]
@lwh504530121 such questions are best directed to the [LXD forum](https://discourse.ubuntu.com/c/lxd/126) (which happens to be down ATM :/).  Once the forum is available again, please search for suggested storage backend driver to use with Docker as I seem to recall that ZFS is indeed not the best one, at least not in its default configuration.

That said, LXD 3.0 has long reached its end of life, see https://documentation.ubuntu.com/lxd/en/latest/installing/#choose-your-release for the list of still supported LXD version. You should be able to upgrade your existing server(s) to the snap version of your choice. Please be mindful that if you want to go to LXD newer than 5.0, you will still need to hop by the `5.0/stable` snap for the `lxd.migrate` tool to be available, this is all explained in https://documentation.ubuntu.com/lxd/en/latest/installing/#snap-package

**Comment by simondeziel** [comment]
Now that the forum is functional again, this solution might be useful to you https://discourse.ubuntu.com/t/never-ending-import-docker-and-btrfs/47697

**Comment by lwh504530121** [comment]
Version 3.0.0 was installed through apt

**Comment by lwh504530121** [comment]
First of all thank you very much for your recovery, now you have upgraded lxc to 4.0 via snap and migrated 3.0 data via lxd.migrate. How can I quickly and safely change the zfs storage pool type of an existing container to dir? And the data is not lost

**Comment by lwh504530121** [comment]
It is best not to change the unique code of the container (CPU ID, container IP, etc.), because my software license is associated with these characteristics, so I hope to be able to change the storage pool of the container based on the original container.

**Comment by simondeziel** [comment]
Yes, you can `lxc copy a1 a1-zfs --storage zfs`. This will create an identical copy with the caveat that upon starting `a1-zfs`, it would change the container name to `a1-zfs`. If you think that risks causing problem with the license, you can avoid that renaming with `lxc config unset a1-zfs volatile.apply_template` before starting it.

**Comment by lwh504530121** [comment]
According to your suggestion, it is still a new container after I execute it, because the software I bought binds the unique code of the CPU, hard disk and other hardware of the old container, so is there any way to change the storage pool type to dir on the basis of the old container?

**Comment by simondeziel** [comment]
@lwh504530121 I encourage you to move the discussion to the forum as this is not a bug with LXD :)
On the forum, your question will be visible to many more so someone might have another idea to work with your constrains assuming the `lxc copy` didn't work.
