### ISSUE TITLE
docs: Wrong order of arguments in examples

### ISSUE THREAD

**Issue by mpurg** [canonical/lxd#14304]
I believe two examples in the [docs](https://documentation.ubuntu.com/lxd/en/latest/howto/projects_confine/#how-to-confine-users-to-specific-projects) have the arguments in a wrong order:
```
lxc auth group permission add <group_name> project operator <project_name>
```
Should be
```
lxc auth group permission add <group_name> project <project_name> operator
```

Thanks,
Miha
---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/howto/projects_confine/

**Comment by markylaing** [comment]
Yes you are correct, thank you!
