### ISSUE TITLE
docs: Migration tool documentation does not match binary

### ISSUE THREAD

**Issue by rptb1** [canonical/lxd#14334]
*Please describe the question or issue you're facing with "How to import physical or virtual machines to LXD instances".*

The instructions do not apply to the binary tool they tell you to download.

The documented flags and examples do not work with the tool.

For example:
```
rb@kiwi:~$ Downloads/bin.linux.lxd-migrate --name test --storage kiwi-tmp --source test.qcow2 --non-interactive
Error: unknown flag: --name
rb@kiwi:~$ sudo Downloads/bin.linux.lxd-migrate --non-interactive
Error: unknown flag: --non-interactive
```

Both the documentation and download URLs contain the word "latest" so I assume they're supposed to match.

---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/howto/import_machines_to_instances/*

**Comment by rptb1** [comment]
Looking at the latest source, I see that these flags are there, suggesting that the tool itself may have been broken.

https://github.com/canonical/lxd/blob/13db9807ec12ca5811c519761a90ebdc989659f3/lxd-migrate/main_migrate.go#L78-L100

**Comment by tomponline** [comment]
The conversion functionality will be released shortly as part of LXD 6.2.

You can try using `latest/edge` snap channel for now, and lxd-migrate from one of our recent test actions:

https://github.com/canonical/lxd/actions/runs/11495559624 in the lxd-clients-Linux  file

**Comment by rptb1** [comment]
So this would indicate a different problem: the LXD documentation published as "latest" (which seems to be found by search engines) is actually still in development.  That seems wrong.  At the very least it should have a big warning label on it.

**Comment by tomponline** [comment]
Yes its a known issue.

**Comment by rptb1** [comment]
Also, if you do go to https://documentation.ubuntu.com/lxd/en/stable-5.21/howto/import_machines_to_instances/ it still points to an incorrectly documented version of the binary.

**Comment by rptb1** [comment]
Righto. Good luck :)
