### ISSUE TITLE
doc: Missing documentation for quota management

### ISSUE THREAD

**Issue by rptb1** [canonical/lxd#14349]
[Reference / Storage Drivers / ZFS / Quotas](https://documentation.ubuntu.com/lxd/en/latest/reference/storage_zfs/#quotas) says:

> By default, LXD uses the quota property when you set up a quota for your storage volume.

But [How to manage storage volumes](https://documentation.ubuntu.com/lxd/en/latest/howto/storage_volumes/#how-to-manage-storage-volumes) makes no mention of quotas.  (It would be nice if the phrase "set up a quota" and all similar phrases were linked, btw.)

A [search of the documentation for quota](https://documentation.ubuntu.com/lxd/en/latest/search/?q=quota&check_keywords=yes&area=default) does not reveal anything.

I'm guessing there are secret configuration keywords on containers and storage volumes that controls quotas.  We have [zfs.use_refquota](https://documentation.ubuntu.com/lxd/en/latest/reference/storage_zfs/#storage-zfs-volume-conf:zfs.use_refquota) that says:

> Use refquota instead of quota for space

but again this does not link to how to actually use set or manage a "quota for space".

The only clue I've found is [in an *example*](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/storage/volume/unset/#examples):

>   lxc storage volume unset default data size
>       Remotes the size/quota of a custom volume "data" in pool "default".

All of the above applies for instances and profiles as well as "storage volumes".  For example [How to manage instances](https://documentation.ubuntu.com/lxd/en/latest/howto/instances_manage/) does not mention quotas.

Please could we have some documentation for size quotas.

Thanks.

---
Document: reference/storage_zfs.md

**Comment by minaelee** [comment]
https://github.com/canonical/lxd/pull/14604 addresses the issue of not finding mentions of quotas in the documentation. Wherever `size` is mentioned in regard to storage, the word `quota` is mentioned alongside it at least once.
