### ISSUE TITLE
cdi: Disable LXC hook env variables NVIDIA_* if CDI is enabled

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/lxd#14372]
When starting a container with a GPU device using CDI mode, we need to disable the `NVIDIA_*` environment variables (i.e, not call `lxcSetConfigItem(cc, "lxc.environment", "NVIDIA_*")` if CDI is enabled and log a warning for why this hasn't been set in the LXC Nvidia hook. CDI and the native Nvidia LXC hook are two separate methods for doing GPU passthrough, they should not be mixed together.

see: https://documentation.ubuntu.com/lxd/en/latest/reference/instance_options/#instance-options-nvidia

**Comment by tomponline** [comment]
@gabrielmougard shouldnt we prevent all of the `nvidia.*` keys when using CDI mode?

**Comment by gabrielmougard** [comment]
Yes we should. But what should be shown to the user: a warning (and we ignore setting these keys)? an error?

**Comment by tomponline** [comment]
> Yes we should. But what should be shown to the user: a warning (and we ignore setting these keys)? an error?

Arent we already blocking the concurrent use of nvidia.runtime, so wouldnt we do the same with the other keys?

**Comment by tomponline** [comment]
https://github.com/canonical/lxd/pull/14348/commits/a267ed1574cd3b0fb3a6e2f3cab3b9858d849217

**Comment by tomponline** [comment]
@gabrielmougard lets get this in before 6.2 is released as the CDI functionality lands then too

**Comment by gabrielmougard** [comment]
@tomponline here it is https://github.com/canonical/lxd/pull/14407
