### ISSUE TITLE
Systemd’s CPU affinity not honored when LXD snap is installed in Ubuntu 22.04.

### ISSUE THREAD

**Issue by al3jandrosg** [canonical/lxd#14418]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":

```
ubuntu@test:~$ snap list --all lxd core20 core22 core24 snapd
Name    Version        Rev    Tracking       Publisher   Notes
core20  20240111       2182   latest/stable  canonical✓  base
lxd     5.0.3-9a1d904  27428  5.0/stable/…   canonical✓  -
snapd   2.61.2         21184  latest/stable  canonical✓  snapd
```

 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-101-generic
   * LXC version: 5.0.3
   * LXD version: 5.0.3-9a1d904
   * Storage backend in use: default

# Issue description

When `systemd`’s `CPUaffinity` is used in Ubuntu 22.04, it is not enforced if the LXD snap version `<6.1` is installed.

# Steps to reproduce

1. get a host (or VM) with lxd snap installed and `systemd`'s `CPUaffinity` configured to bound systemd and its childs to some CPUs, e.g., `CPUs=0-1`:

```
uvt-kvm create test release=jammy arch=amd64 --memory 4096 --cpu 4 --disk 50  
uvt-kvm ssh test
```

2. Within the instance:

```
ubuntu@test:~$ echo "CPUAffinity=0-1" | sudo tee -a /etc/systemd/system.conf
ubuntu@test:~$ sudo systemctl daemon-reexec

ubuntu@test:~$ grep -i affinity /etc/systemd/system.conf
CPUAffinity=0-1
ubuntu@test:~$ sudo taskset -cp 1
pid 1's current affinity list: 0-3
```

since we have `CPUAffinity=0-1` in `/etc/systemd/system.conf`, the expectation would be to get `pid 1's current affinity list: 0-1` from `taskset`, but this is not honored and any CPU (machine below has 4 cores, so `CPU=0-3`) is allowed.

3. Just as a test of persistence for the issue, reboot the system and still no affinity set:

```
ubuntu@test:~$ sudo reboot
...
ubuntu@test:~$ sudo taskset -cp 1
pid 1's current affinity list: 0-3
```

4. Remove the `lxd` snap then the CPUaffinity starts to get enforced:

```
ubuntu@test:~$ snap list
Name Version Rev Tracking Publisher Notes
core20 20240111 2182 latest/stable canonical✓ base
lxd 5.0.3-9a1d904 27428 5.0/stable/… canonical✓ -
snapd 2.61.2 21184 latest/stable canonical✓ snapd
ubuntu@test:~$ sudo snap remove lxd
lxd removed
ubuntu@test:~$ grep -i affinity /etc/systemd/system.conf
CPUAffinity=0-1
ubuntu@test:~$ sudo taskset -cp 1
pid 1's current affinity list: 0,1
```

Notice above that after the `lxd` snap is removed then `pid 1's current affinity list: 0,1` meaning that `systemd` and its childs are bound to `CPU=0-1`

**Comment by tomponline** [comment]
@mihalicyn want to investugate this one?

**Comment by al3jandrosg** [comment]
closing as this does not seem related to LXD or any snap for that matter.
