### ISSUE TITLE
Missing instance config suggestions from tab completion

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#14537]
```
$ lxc init --empty c1
Creating c1
$ lxc config set c1 linux<tab>   # completes to linux.kernel_modules
$ lxc config set c1 linux.kernel_modules
```

But it skips the `linux.sysctl.` key prefix. Same for `user.` and `environment.`. Please note that for those key prefix, it's only possible to complete up to the trailing `.` as afterward it's all unknown/user provided.

**Comment by kadinsayani** [comment]
Thanks for putting this issue up! Would you prefer if `linux.sysctl.*` was completed, or `linux.sysctl.`?

**Comment by simondeziel** [comment]
> Would you prefer if `linux.sysctl.*` was completed, or `linux.sysctl.`?

Completing up to the 2nd `.` makes sense to me.

Also while playing around it, I noticed that `lxc config unset <inst> <tab>` could be made smarter in proposing to complete only the config keys that are already `set` and thus `unset`'able. Happy to fill this one as a separated issue if you want.

**Comment by simondeziel** [comment]
> Should we also throw in a no space directive for `lxc config get/set/unset`?

Definitely as those don't accept dir/file arguments anyway
