### ISSUE TITLE
Check whether `security.shared` makes sense for `cephfs` and if not remove

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#14534]
The security.shared volume setting is only relevant for custom block volumes (you can see there is a "condition: custom block volume " section in the drop down for that setting.

https://documentation.ubuntu.com/lxd/en/latest/reference/storage_cephfs/#storage-cephfs-volume-conf:security.shared

However as cephfs storage driver doesn't support block volumes this doesn't make sense to me.

https://documentation.ubuntu.com/lxd/en/latest/reference/storage_cephfs/#storage-cephfs-volume-conf:security.shared

Discussion: https://chat.canonical.com/canonical/pl/6wry93xjcfn78g8tbitstp4fmw

**Comment by tomponline** [comment]
Looks like it was this commit

https://github.com/canonical/lxd/pull/13183/commits/362734e5ae886b43310b9a42fa01cec4345cbe73

@hamistao was this an oversight or added for cephfs particularly?

Thanks

**Comment by hamistao** [comment]
This was one of my very first contributions to LXD, it was definitely an oversight. Will fix in a minute.
